IF
    Heard([ANYONE],111)
THEN
    RESPONSE #100
        MoveToObject(NearestEnemyOf(Myself))
END

IF
    AttackedBy([GOODCUTOFF],DEFAULT)
    !Allegiance(Myself,ENEMY)
THEN
    RESPONSE #100
        Enemy()
END

IF
    ActionListEmpty()
THEN
    RESPONSE #100
        AttackReevaluate(LastAttackerOf("AC#PP70Z"),30)  // Fallen Tree
END

IF
    ActionListEmpty()
    AttackedBy([ANYONE],DEFAULT)
THEN
    RESPONSE #100
        Attack(LastAttackerOf(Myself))
END

