IF
    OnCreation()
    GlobalGT("CutsceneAmbush","ACPP30",1)
THEN
    RESPONSE #100
        PlayDeadInterruptable(100000)
        Continue()
END

IF
    Global("Die_Eldath","ACPP30",1)
    HasItem("MINHP1",Myself)  // No such index
THEN
    RESPONSE #100
        DestroyItem("MINHP1")  // No such index
END

IF
    Global("CutsceneAmbush","ACPP30",10)
    Delay(3)
THEN
    RESPONSE #100
        ApplyDamage(Myself,1,POISON)
END

