/////////////////////////////////////////////////////////////////////
// True Sight Check
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_EnemyTrueSightTimer","GLOBAL")
  Global("MO_EnemyTrueSight","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("MO_EnemyTrueSight","GLOBAL",0)
END

IF
  Global("MO_TrueSightActive","LOCALS",1)
  CheckStat(Myself,0,TRUE_SIGHT)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",0)
    SetGlobal("MO_EnemyTrueSight","GLOBAL",0)
END

/////////////////////////////////////////////////////////////////////
// Prep 
/////////////////////////////////////////////////////////////////////
IF
  See(NearestEnemyOf(Myself))
  Global("Prep","LOCALS",0)
THEN
  RESPONSE #100
    ApplySpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
    ApplySpell(Myself,WIZARD_MINOR_SPELL_TURNING)  // SPWI522.SPL (Minor Spell Turning)
    Spell(Myself,WIZARD_MISLEAD)  // SPWI607.SPL (Mislead)
    SetGlobal("Prep","LOCALS",1)
END

/////////////////////////////////////////////////////////////////////
// Contingency
/////////////////////////////////////////////////////////////////////
IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
  CheckStatLT(Myself,1,STONESKINS)
  Global("Prep","LOCALS",1)
THEN
  RESPONSE #100
    DisplayString(Myself,29736)  // Contingency—Stoneskin
    SetGlobal("Prep","LOCALS",2)
    ApplySpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
END

/////////////////////////////////////////////////////////////////////
// Spell: Vocalize (if silenced)
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_VOCALIZE)
  StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_VOCALIZE)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// True Sight
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_LocalTimeStopTimer","LOCALS")
  Global("MO_EnemyTrueSight","GLOBAL",0)
  Allegiance(Myself,ENEMY)
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
  OR(6)
    SpellCast([GOODCUTOFF],WIZARD_PROJECT_IMAGE)  // SPWI703.SPL (Project Image)
    SpellCast([GOODCUTOFF],WIZARD_SIMULACRUM)  // SPWI804.SPL (Simulacrum)
    SpellCast([GOODCUTOFF],WIZARD_MISLEAD)  // SPWI607.SPL (Mislead)
    SpellCast([GOODCUTOFF],WIZARD_SHADOW_DOOR)  // SPWI505.SPL (Shadow Door)
    SpellCast([GOODCUTOFF],WIZARD_IMPROVED_INVISIBILITY)  // SPWI405.SPL (Improved Invisibility)
    SpellCast([GOODCUTOFF],WIZARD_INVISIBILITY)  // SPWI206.SPL (Invisibility)
  !CheckSpellState([GOODCUTOFF],SI_DIVINATION)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_EnemyTrueSight","GLOBAL",1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_EnemyTrueSightTimer","GLOBAL",60)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_LocalTimeStopTimer","LOCALS")
  Global("MO_EnemyTrueSight","GLOBAL",0)
  Allegiance(Myself,ENEMY)
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
  Detect([GOODCUTOFF])
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !CheckSpellState([GOODCUTOFF],SI_DIVINATION)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_EnemyTrueSight","GLOBAL",1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_EnemyTrueSightTimer","GLOBAL",60)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_LocalTimeStopTimer","LOCALS")
  Global("MO_EnemyTrueSight","GLOBAL",0)
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
  OR(4)
    StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(SixthNearestEnemyOf(Myself),STATE_INVISIBLE)
    CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
    Gender(SixthNearestEnemyOf(Myself),ILLUSIONARY)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_SLEEPING)
  !CheckStat(SixthNearestEnemyOf(Myself),3,WIZARD_SPELL_IMMUNITY)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_LocalTimeStopTimer","LOCALS")
  Global("MO_EnemyTrueSight","GLOBAL",0)
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
  OR(4)
    StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(FifthNearestEnemyOf(Myself),STATE_INVISIBLE)
    CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
    Gender(FifthNearestEnemyOf(Myself),ILLUSIONARY)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
  !CheckStat(FifthNearestEnemyOf(Myself),3,WIZARD_SPELL_IMMUNITY)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_LocalTimeStopTimer","LOCALS")
  Global("MO_EnemyTrueSight","GLOBAL",0)
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
  OR(4)
    StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(FourthNearestEnemyOf(Myself),STATE_INVISIBLE)
    CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
    Gender(FourthNearestEnemyOf(Myself),ILLUSIONARY)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
  !CheckStat(FourthNearestEnemyOf(Myself),3,WIZARD_SPELL_IMMUNITY)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_LocalTimeStopTimer","LOCALS")
  Global("MO_EnemyTrueSight","GLOBAL",0)
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
  OR(4)
    StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(ThirdNearestEnemyOf(Myself),STATE_INVISIBLE)
    CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
    Gender(ThirdNearestEnemyOf(Myself),ILLUSIONARY)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
  !CheckStat(ThirdNearestEnemyOf(Myself),3,WIZARD_SPELL_IMMUNITY)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_LocalTimeStopTimer","LOCALS")
  Global("MO_EnemyTrueSight","GLOBAL",0)
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
  OR(4)
    StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(SecondNearestEnemyOf(Myself),STATE_INVISIBLE)
    CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
    Gender(SecondNearestEnemyOf(Myself),ILLUSIONARY)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
  !CheckStat(SecondNearestEnemyOf(Myself),3,WIZARD_SPELL_IMMUNITY)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_LocalTimeStopTimer","LOCALS")
  Global("MO_EnemyTrueSight","GLOBAL",0)
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
  OR(4)
    StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
    CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
    Gender(NearestEnemyOf(Myself),ILLUSIONARY)
  !StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
  !CheckStat(NearestEnemyOf(Myself),3,WIZARD_SPELL_IMMUNITY)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_LocalTimeStopTimer","LOCALS")
  Global("MO_EnemyTrueSight","GLOBAL",0)
  See(LastSeenBy(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_EnemyTrueSight","GLOBAL",1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_EnemyTrueSightTimer","GLOBAL",60)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Chaos
/////////////////////////////////////////////////////////////////////
IF  
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChaosTimer","LOCALS")
  HaveSpell(WIZARD_CHAOS)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
  CheckStatLT(SixthNearestEnemyOf(Myself),20,RESISTMAGIC)
  CheckStatGT(SixthNearestEnemyOf(Myself),-2,SAVEVSSPELL)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !CheckSpellState(SixthNearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(SixthNearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(SixthNearestEnemyOf(Myself),POTION_OF_CLARITY)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !HasItemEquiped("AMUL17",SixthNearestEnemyOf(Myself)) // Greenstone Amulet
  !HasItemEquiped("LEAT20",SixthNearestEnemyOf(Myself)) // Aeger's Hide +3
  !HasItemEquiped("SHLD25",SixthNearestEnemyOf(Myself)) // Shield of Harmony +2
  !HasItemEquipedReal("SW1H54",SixthNearestEnemyOf(Myself)) // The Equalizer
  !HasItemEquipedReal("SW2H14",SixthNearestEnemyOf(Myself)) // Lilarcor
  !HasItemEquipedReal("SW2H21",SixthNearestEnemyOf(Myself)) // Psion's Blade +5
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF  
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChaosTimer","LOCALS")
  HaveSpell(WIZARD_CHAOS)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
  CheckStatLT(FifthNearestEnemyOf(Myself),20,RESISTMAGIC)
  CheckStatGT(FifthNearestEnemyOf(Myself),-2,SAVEVSSPELL)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !CheckSpellState(FifthNearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(FifthNearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(FifthNearestEnemyOf(Myself),POTION_OF_CLARITY)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !HasItemEquiped("AMUL17",FifthNearestEnemyOf(Myself)) // Greenstone Amulet
  !HasItemEquiped("LEAT20",FifthNearestEnemyOf(Myself)) // Aeger's Hide +3
  !HasItemEquiped("SHLD25",FifthNearestEnemyOf(Myself)) // Shield of Harmony +2
  !HasItemEquipedReal("SW1H54",FifthNearestEnemyOf(Myself)) // The Equalizer
  !HasItemEquipedReal("SW2H14",FifthNearestEnemyOf(Myself)) // Lilarcor
  !HasItemEquipedReal("SW2H21",FifthNearestEnemyOf(Myself)) // Psion's Blade +5
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF  
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChaosTimer","LOCALS")
  HaveSpell(WIZARD_CHAOS)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
  CheckStatLT(FourthNearestEnemyOf(Myself),20,RESISTMAGIC)
  CheckStatGT(FourthNearestEnemyOf(Myself),-2,SAVEVSSPELL)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !CheckSpellState(FourthNearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(FourthNearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(FourthNearestEnemyOf(Myself),POTION_OF_CLARITY)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !HasItemEquiped("AMUL17",FourthNearestEnemyOf(Myself)) // Greenstone Amulet
  !HasItemEquiped("LEAT20",FourthNearestEnemyOf(Myself)) // Aeger's Hide +3
  !HasItemEquiped("SHLD25",FourthNearestEnemyOf(Myself)) // Shield of Harmony +2
  !HasItemEquipedReal("SW1H54",FourthNearestEnemyOf(Myself)) // The Equalizer
  !HasItemEquipedReal("SW2H14",FourthNearestEnemyOf(Myself)) // Lilarcor
  !HasItemEquipedReal("SW2H21",FourthNearestEnemyOf(Myself)) // Psion's Blade +5
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF  
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChaosTimer","LOCALS")
  HaveSpell(WIZARD_CHAOS)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
  CheckStatLT(ThirdNearestEnemyOf(Myself),20,RESISTMAGIC)
  CheckStatGT(ThirdNearestEnemyOf(Myself),-2,SAVEVSSPELL)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),POTION_OF_CLARITY)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !HasItemEquiped("AMUL17",ThirdNearestEnemyOf(Myself)) // Greenstone Amulet
  !HasItemEquiped("LEAT20",ThirdNearestEnemyOf(Myself)) // Aeger's Hide +3
  !HasItemEquiped("SHLD25",ThirdNearestEnemyOf(Myself)) // Shield of Harmony +2
  !HasItemEquipedReal("SW1H54",ThirdNearestEnemyOf(Myself)) // The Equalizer
  !HasItemEquipedReal("SW2H14",ThirdNearestEnemyOf(Myself)) // Lilarcor
  !HasItemEquipedReal("SW2H21",ThirdNearestEnemyOf(Myself)) // Psion's Blade +5
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF  
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChaosTimer","LOCALS")
  HaveSpell(WIZARD_CHAOS)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
  CheckStatLT(SecondNearestEnemyOf(Myself),20,RESISTMAGIC)
  CheckStatGT(SecondNearestEnemyOf(Myself),-2,SAVEVSSPELL)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !CheckSpellState(SecondNearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(SecondNearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(SecondNearestEnemyOf(Myself),POTION_OF_CLARITY)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !HasItemEquiped("AMUL17",SecondNearestEnemyOf(Myself)) // Greenstone Amulet
  !HasItemEquiped("LEAT20",SecondNearestEnemyOf(Myself)) // Aeger's Hide +3
  !HasItemEquiped("SHLD25",SecondNearestEnemyOf(Myself)) // Shield of Harmony +2
  !HasItemEquipedReal("SW1H54",SecondNearestEnemyOf(Myself)) // The Equalizer
  !HasItemEquipedReal("SW2H14",SecondNearestEnemyOf(Myself)) // Lilarcor
  !HasItemEquipedReal("SW2H21",SecondNearestEnemyOf(Myself)) // Psion's Blade +5
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF  
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChaosTimer","LOCALS")
  HaveSpell(WIZARD_CHAOS)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
  CheckStatLT(NearestEnemyOf(Myself),20,RESISTMAGIC)
  CheckStatGT(NearestEnemyOf(Myself),-2,SAVEVSSPELL)
  !CheckStatGT(NearestEnemyOf(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckSpellState(NearestEnemyOf(Myself),SI_ENCHANTMENT)
  !CheckSpellState(NearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(NearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(NearestEnemyOf(Myself),POTION_OF_CLARITY)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !HasItemEquiped("AMUL17",NearestEnemyOf(Myself)) // Greenstone Amulet
  !HasItemEquiped("LEAT20",NearestEnemyOf(Myself)) // Aeger's Hide +3
  !HasItemEquiped("SHLD25",NearestEnemyOf(Myself)) // Shield of Harmony +2
  !HasItemEquipedReal("SW1H54",NearestEnemyOf(Myself)) // The Equalizer
  !HasItemEquipedReal("SW2H14",NearestEnemyOf(Myself)) // Lilarcor
  !HasItemEquipedReal("SW2H21",NearestEnemyOf(Myself)) // Psion's Blade +5
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChaosTimer","LOCALS")
  HaveSpell(WIZARD_CHAOS)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_DISABLED)
  CheckStatLT(LastSeenBy(Myself),20,RESISTMAGIC)
  CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckSpellState(LastSeenBy(Myself),SI_ENCHANTMENT)
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),POTION_OF_CLARITY)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !HasItemEquiped("AMUL17",LastSeenBy(Myself)) // Greenstone Amulet
  !HasItemEquiped("LEAT20",LastSeenBy(Myself)) // Aeger's Hide +3
  !HasItemEquiped("SHLD25",LastSeenBy(Myself)) // Shield of Harmony +2
  !HasItemEquipedReal("SW1H54",LastSeenBy(Myself)) // The Equalizer
  !HasItemEquipedReal("SW2H14",LastSeenBy(Myself)) // Lilarcor
  !HasItemEquipedReal("SW2H21",LastSeenBy(Myself)) // Psion's Blade +5
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_ChaosTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_CHAOS)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Shadow Door
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ShadowCast","LOCALS")
  HaveSpell(WIZARD_SHADOW_DOOR)
  See(Myself)
  Allegiance(Myself,ENEMY)
  OR(2)
    See(NearestEnemyOf(Myself))
    HitBy([GOODCUTOFF],CRUSHING)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_ShadowCast","LOCALS",32)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_SHADOW_DOOR)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Confusion 
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ConfusionTimer","LOCALS")
  HaveSpell(WIZARD_CONFUSION)  // SPWI401.SPL (Confusion)
  !General(SixthNearestEnemyOf(Myself),UNDEAD)
  !General(SixthNearestEnemyOf(Myself),PLANT)
  !Race(SixthNearestEnemyOf(Myself),DEMONIC)
  !Race(SixthNearestEnemyOf(Myself),TROLL)
  !Race(SixthNearestEnemyOf(Myself),SLIME)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
  CheckStatLT(SixthNearestEnemyOf(Myself),20,RESISTMAGIC)
  CheckStatGT(SixthNearestEnemyOf(Myself),-2,SAVEVSSPELL)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !CheckSpellState(SixthNearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(SixthNearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(SixthNearestEnemyOf(Myself),POTION_OF_CLARITY)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  !HasItem("MORSWORD",SixthNearestEnemyOf(Myself))  // Mordenkainen's Sword
  !HasItemEquiped("LEAT20",SixthNearestEnemyOf(Myself))
  !HasItemEquiped("OHRHELM1",SixthNearestEnemyOf(Myself))
  !HasItemEquiped("OHDMASK",SixthNearestEnemyOf(Myself))
  !HasItemEquiped("SHLD25",SixthNearestEnemyOf(Myself))
  !HasItemEquiped("SW2H14",SixthNearestEnemyOf(Myself))
  !HasItemEquiped("SW2H21",SixthNearestEnemyOf(Myself))
  !HasItemEquiped("SW1H54",SixthNearestEnemyOf(Myself))
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ConfusionTimer","LOCALS")
  HaveSpell(WIZARD_CONFUSION)  // SPWI401.SPL (Confusion)
  !General(FifthNearestEnemyOf(Myself),UNDEAD)
  !General(FifthNearestEnemyOf(Myself),PLANT)
  !Race(FifthNearestEnemyOf(Myself),DEMONIC)
  !Race(FifthNearestEnemyOf(Myself),TROLL)
  !Race(FifthNearestEnemyOf(Myself),SLIME)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
  CheckStatLT(FifthNearestEnemyOf(Myself),20,RESISTMAGIC)
  CheckStatGT(FifthNearestEnemyOf(Myself),-2,SAVEVSSPELL)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !CheckSpellState(FifthNearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(FifthNearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(FifthNearestEnemyOf(Myself),POTION_OF_CLARITY)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  !HasItem("MORSWORD",FifthNearestEnemyOf(Myself))  // Mordenkainen's Sword
  !HasItemEquiped("LEAT20",FifthNearestEnemyOf(Myself))
  !HasItemEquiped("OHRHELM1",FifthNearestEnemyOf(Myself))
  !HasItemEquiped("OHDMASK",FifthNearestEnemyOf(Myself))
  !HasItemEquiped("SHLD25",FifthNearestEnemyOf(Myself))
  !HasItemEquiped("SW2H14",FifthNearestEnemyOf(Myself))
  !HasItemEquiped("SW2H21",FifthNearestEnemyOf(Myself))
  !HasItemEquiped("SW1H54",FifthNearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ConfusionTimer","LOCALS")
  HaveSpell(WIZARD_CONFUSION)  // SPWI401.SPL (Confusion)
  !General(FourthNearestEnemyOf(Myself),UNDEAD)
  !General(FourthNearestEnemyOf(Myself),PLANT)
  !Race(FourthNearestEnemyOf(Myself),DEMONIC)
  !Race(FourthNearestEnemyOf(Myself),TROLL)
  !Race(FourthNearestEnemyOf(Myself),SLIME)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
  CheckStatLT(FourthNearestEnemyOf(Myself),20,RESISTMAGIC)
  CheckStatGT(FourthNearestEnemyOf(Myself),-2,SAVEVSSPELL)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !CheckSpellState(FourthNearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(FourthNearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(FourthNearestEnemyOf(Myself),POTION_OF_CLARITY)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  !HasItem("MORSWORD",FourthNearestEnemyOf(Myself))  // Mordenkainen's Sword
  !HasItemEquiped("LEAT20",FourthNearestEnemyOf(Myself))
  !HasItemEquiped("OHRHELM1",FourthNearestEnemyOf(Myself))
  !HasItemEquiped("OHDMASK",FourthNearestEnemyOf(Myself))
  !HasItemEquiped("SHLD25",FourthNearestEnemyOf(Myself))
  !HasItemEquiped("SW2H14",FourthNearestEnemyOf(Myself))
  !HasItemEquiped("SW2H21",FourthNearestEnemyOf(Myself))
  !HasItemEquiped("SW1H54",FourthNearestEnemyOf(Myself))
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ConfusionTimer","LOCALS")
  HaveSpell(WIZARD_CONFUSION)  // SPWI401.SPL (Confusion)
  !General(ThirdNearestEnemyOf(Myself),UNDEAD)
  !General(ThirdNearestEnemyOf(Myself),PLANT)
  !Race(ThirdNearestEnemyOf(Myself),DEMONIC)
  !Race(ThirdNearestEnemyOf(Myself),TROLL)
  !Race(ThirdNearestEnemyOf(Myself),SLIME)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
  CheckStatLT(ThirdNearestEnemyOf(Myself),20,RESISTMAGIC)
  CheckStatGT(ThirdNearestEnemyOf(Myself),-2,SAVEVSSPELL)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),POTION_OF_CLARITY)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  !HasItem("MORSWORD",ThirdNearestEnemyOf(Myself))  // Mordenkainen's Sword
  !HasItemEquiped("LEAT20",ThirdNearestEnemyOf(Myself))
  !HasItemEquiped("OHRHELM1",ThirdNearestEnemyOf(Myself))
  !HasItemEquiped("OHDMASK",ThirdNearestEnemyOf(Myself))
  !HasItemEquiped("SHLD25",ThirdNearestEnemyOf(Myself))
  !HasItemEquiped("SW2H14",ThirdNearestEnemyOf(Myself))
  !HasItemEquiped("SW2H21",ThirdNearestEnemyOf(Myself))
  !HasItemEquiped("SW1H54",ThirdNearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ConfusionTimer","LOCALS")
  HaveSpell(WIZARD_CONFUSION)  // SPWI401.SPL (Confusion)
  !General(SecondNearestEnemyOf(Myself),UNDEAD)
  !General(SecondNearestEnemyOf(Myself),PLANT)
  !Race(SecondNearestEnemyOf(Myself),DEMONIC)
  !Race(SecondNearestEnemyOf(Myself),TROLL)
  !Race(SecondNearestEnemyOf(Myself),SLIME)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
  CheckStatLT(SecondNearestEnemyOf(Myself),20,RESISTMAGIC)
  CheckStatGT(SecondNearestEnemyOf(Myself),-2,SAVEVSSPELL)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !CheckSpellState(SecondNearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(SecondNearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(SecondNearestEnemyOf(Myself),POTION_OF_CLARITY)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  !HasItem("MORSWORD",SecondNearestEnemyOf(Myself))  // Mordenkainen's Sword
  !HasItemEquiped("LEAT20",SecondNearestEnemyOf(Myself))
  !HasItemEquiped("OHRHELM1",SecondNearestEnemyOf(Myself))
  !HasItemEquiped("OHDMASK",SecondNearestEnemyOf(Myself))
  !HasItemEquiped("SHLD25",SecondNearestEnemyOf(Myself))
  !HasItemEquiped("SW2H14",SecondNearestEnemyOf(Myself))
  !HasItemEquiped("SW2H21",SecondNearestEnemyOf(Myself))
  !HasItemEquiped("SW1H54",SecondNearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ConfusionTimer","LOCALS")
  HaveSpell(WIZARD_CONFUSION)  // SPWI401.SPL (Confusion)
  !General(NearestEnemyOf(Myself),UNDEAD)
  !General(NearestEnemyOf(Myself),PLANT)
  !Race(NearestEnemyOf(Myself),DEMONIC)
  !Race(NearestEnemyOf(Myself),TROLL)
  !Race(NearestEnemyOf(Myself),SLIME)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
  CheckStatLT(NearestEnemyOf(Myself),20,RESISTMAGIC)
  CheckStatGT(NearestEnemyOf(Myself),-2,SAVEVSSPELL)
  !CheckStatGT(NearestEnemyOf(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckSpellState(NearestEnemyOf(Myself),SI_ENCHANTMENT)
  !CheckSpellState(NearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(NearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(NearestEnemyOf(Myself),POTION_OF_CLARITY)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  !HasItem("MORSWORD",NearestEnemyOf(Myself))  // Mordenkainen's Sword
  !HasItemEquiped("LEAT20",NearestEnemyOf(Myself))
  !HasItemEquiped("OHRHELM1",NearestEnemyOf(Myself))
  !HasItemEquiped("OHDMASK",NearestEnemyOf(Myself))
  !HasItemEquiped("SHLD25",NearestEnemyOf(Myself))
  !HasItemEquiped("SW2H14",NearestEnemyOf(Myself))
  !HasItemEquiped("SW2H21",NearestEnemyOf(Myself))
  !HasItemEquiped("SW1H54",NearestEnemyOf(Myself))
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ConfusionTimer","LOCALS")
  HaveSpell(WIZARD_CONFUSION)  // SPWI401.SPL (Confusion)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !General(LastSeenBy(Myself),UNDEAD)
  !General(LastSeenBy(Myself),PLANT)
  !Race(LastSeenBy(Myself),DEMONIC)
  !Race(LastSeenBy(Myself),TROLL)
  !Race(LastSeenBy(Myself),SLIME)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_DISABLED)
  CheckStatLT(LastSeenBy(Myself),20,RESISTMAGIC)
  CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckSpellState(LastSeenBy(Myself),SI_ENCHANTMENT)
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),POTION_OF_CLARITY)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
  !HasItemEquiped("LEAT20",LastSeenBy(Myself))
  !HasItemEquiped("OHRHELM1",LastSeenBy(Myself))
  !HasItemEquiped("OHDMASK",LastSeenBy(Myself))
  !HasItemEquiped("SHLD25",LastSeenBy(Myself))
  !HasItemEquiped("SW2H14",LastSeenBy(Myself))
  !HasItemEquiped("SW2H21",LastSeenBy(Myself))
  !HasItemEquiped("SW1H54",LastSeenBy(Myself))
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_ConfusionTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_CONFUSION)  // SPWI401.SPL (Confusion)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Mental Domination
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_DominationTimer","LOCALS")
  HaveSpell(WIZARD_DOMINATION)
  !Class(SixthNearestEnemyOf(Myself),MONK)
  !Kit(SixthNearestEnemyOf(Myself),INQUISITOR)
  !Kit(SixthNearestEnemyOf(Myself),CAVALIER)
  !Race(SixthNearestEnemyOf(Myself),ELF)
  !HasItemEquiped("HELM06",SixthNearestEnemyOf(Myself)) // Helm of Charm Protection
  !HasItemEquiped("MISCBC",SixthNearestEnemyOf(Myself)) // Blackrazor
  !HasItemEquiped("NPCHAN",SixthNearestEnemyOf(Myself)) // Corthala Family Armor
  !HasItemEquiped("REAVER",SixthNearestEnemyOf(Myself)) // Unholy Reaver
  !HasItemEquiped("SHLD25",SixthNearestEnemyOf(Myself)) // Shield of Harmony +2
  !HasItemEquipedReal("SPER07",SixthNearestEnemyOf(Myself)) // Spear of the Unicorn +2           
  !HasItemEquipedReal("STAF11",SixthNearestEnemyOf(Myself)) // Staff of the Magi
  !HasItemEquipedReal("SW1H35",SixthNearestEnemyOf(Myself)) // Adjatha the Drinker +2
  !HasItemEquipedReal("SW1H54",SixthNearestEnemyOf(Myself)) // The Equalizer
  !HasItemEquipedReal("SW2H14",SixthNearestEnemyOf(Myself)) // Lilarcor
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !Gender(SixthNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(SixthNearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(SixthNearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(SixthNearestEnemyOf(Myself),MINSC_BERSERK)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_HARMLESS)
  !CheckSpellState(SixthNearestEnemyOf(Myself),POTION_OF_CLARITY)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(SixthNearestEnemyOf(Myself),25,RESISTMAGIC)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_DominationTimer","LOCALS")
  HaveSpell(WIZARD_DOMINATION)
  !Class(FifthNearestEnemyOf(Myself),MONK)
  !Kit(FifthNearestEnemyOf(Myself),INQUISITOR)
  !Kit(FifthNearestEnemyOf(Myself),CAVALIER)
  !Race(FifthNearestEnemyOf(Myself),ELF)
  !HasItemEquiped("HELM06",FifthNearestEnemyOf(Myself)) // Helm of Charm Protection
  !HasItemEquiped("MISCBC",FifthNearestEnemyOf(Myself)) // Blackrazor
  !HasItemEquiped("NPCHAN",FifthNearestEnemyOf(Myself)) // Corthala Family Armor
  !HasItemEquiped("REAVER",FifthNearestEnemyOf(Myself)) // Unholy Reaver
  !HasItemEquiped("SHLD25",FifthNearestEnemyOf(Myself)) // Shield of Harmony +2
  !HasItemEquipedReal("SPER07",FifthNearestEnemyOf(Myself)) // Spear of the Unicorn +2           
  !HasItemEquipedReal("STAF11",FifthNearestEnemyOf(Myself)) // Staff of the Magi
  !HasItemEquipedReal("SW1H35",FifthNearestEnemyOf(Myself)) // Adjatha the Drinker +2
  !HasItemEquipedReal("SW1H54",FifthNearestEnemyOf(Myself)) // The Equalizer
  !HasItemEquipedReal("SW2H14",FifthNearestEnemyOf(Myself)) // Lilarcor
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !Gender(FifthNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(FifthNearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(FifthNearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(FifthNearestEnemyOf(Myself),MINSC_BERSERK)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_HARMLESS)
  !CheckSpellState(FifthNearestEnemyOf(Myself),POTION_OF_CLARITY)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(FifthNearestEnemyOf(Myself),25,RESISTMAGIC)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_DominationTimer","LOCALS")
  HaveSpell(WIZARD_DOMINATION)
  !Class(FourthNearestEnemyOf(Myself),MONK)
  !Kit(FourthNearestEnemyOf(Myself),INQUISITOR)
  !Kit(FourthNearestEnemyOf(Myself),CAVALIER)
  !Race(FourthNearestEnemyOf(Myself),ELF)
  !HasItemEquiped("HELM06",FourthNearestEnemyOf(Myself)) // Helm of Charm Protection
  !HasItemEquiped("MISCBC",FourthNearestEnemyOf(Myself)) // Blackrazor
  !HasItemEquiped("NPCHAN",FourthNearestEnemyOf(Myself)) // Corthala Family Armor
  !HasItemEquiped("REAVER",FourthNearestEnemyOf(Myself)) // Unholy Reaver
  !HasItemEquiped("SHLD25",FourthNearestEnemyOf(Myself)) // Shield of Harmony +2
  !HasItemEquipedReal("SPER07",FourthNearestEnemyOf(Myself)) // Spear of the Unicorn +2           
  !HasItemEquipedReal("STAF11",FourthNearestEnemyOf(Myself)) // Staff of the Magi
  !HasItemEquipedReal("SW1H35",FourthNearestEnemyOf(Myself)) // Adjatha the Drinker +2
  !HasItemEquipedReal("SW1H54",FourthNearestEnemyOf(Myself)) // The Equalizer
  !HasItemEquipedReal("SW2H14",FourthNearestEnemyOf(Myself)) // Lilarcor
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !Gender(FourthNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(FourthNearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(FourthNearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(FourthNearestEnemyOf(Myself),MINSC_BERSERK)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_HARMLESS)
  !CheckSpellState(FourthNearestEnemyOf(Myself),POTION_OF_CLARITY)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(FourthNearestEnemyOf(Myself),25,RESISTMAGIC)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_DominationTimer","LOCALS")
  HaveSpell(WIZARD_DOMINATION)
  !Class(ThirdNearestEnemyOf(Myself),MONK)
  !Kit(ThirdNearestEnemyOf(Myself),INQUISITOR)
  !Kit(ThirdNearestEnemyOf(Myself),CAVALIER)
  !Race(ThirdNearestEnemyOf(Myself),ELF)
  !HasItemEquiped("HELM06",ThirdNearestEnemyOf(Myself)) // Helm of Charm Protection
  !HasItemEquiped("MISCBC",ThirdNearestEnemyOf(Myself)) // Blackrazor
  !HasItemEquiped("NPCHAN",ThirdNearestEnemyOf(Myself)) // Corthala Family Armor
  !HasItemEquiped("REAVER",ThirdNearestEnemyOf(Myself)) // Unholy Reaver
  !HasItemEquiped("SHLD25",ThirdNearestEnemyOf(Myself)) // Shield of Harmony +2
  !HasItemEquipedReal("SPER07",ThirdNearestEnemyOf(Myself)) // Spear of the Unicorn +2           
  !HasItemEquipedReal("STAF11",ThirdNearestEnemyOf(Myself)) // Staff of the Magi
  !HasItemEquipedReal("SW1H35",ThirdNearestEnemyOf(Myself)) // Adjatha the Drinker +2
  !HasItemEquipedReal("SW1H54",ThirdNearestEnemyOf(Myself)) // The Equalizer
  !HasItemEquipedReal("SW2H14",ThirdNearestEnemyOf(Myself)) // Lilarcor
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !Gender(ThirdNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),MINSC_BERSERK)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_HARMLESS)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),POTION_OF_CLARITY)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),25,RESISTMAGIC)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_DominationTimer","LOCALS")
  HaveSpell(WIZARD_DOMINATION)
  !Class(SecondNearestEnemyOf(Myself),MONK)
  !Kit(SecondNearestEnemyOf(Myself),INQUISITOR)
  !Kit(SecondNearestEnemyOf(Myself),CAVALIER)
  !Race(SecondNearestEnemyOf(Myself),ELF)
  !HasItemEquiped("HELM06",SecondNearestEnemyOf(Myself)) // Helm of Charm Protection
  !HasItemEquiped("MISCBC",SecondNearestEnemyOf(Myself)) // Blackrazor
  !HasItemEquiped("NPCHAN",SecondNearestEnemyOf(Myself)) // Corthala Family Armor
  !HasItemEquiped("REAVER",SecondNearestEnemyOf(Myself)) // Unholy Reaver
  !HasItemEquiped("SHLD25",SecondNearestEnemyOf(Myself)) // Shield of Harmony +2
  !HasItemEquipedReal("SPER07",SecondNearestEnemyOf(Myself)) // Spear of the Unicorn +2           
  !HasItemEquipedReal("STAF11",SecondNearestEnemyOf(Myself)) // Staff of the Magi
  !HasItemEquipedReal("SW1H35",SecondNearestEnemyOf(Myself)) // Adjatha the Drinker +2
  !HasItemEquipedReal("SW1H54",SecondNearestEnemyOf(Myself)) // The Equalizer
  !HasItemEquipedReal("SW2H14",SecondNearestEnemyOf(Myself)) // Lilarcor
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !Gender(SecondNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(SecondNearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(SecondNearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(SecondNearestEnemyOf(Myself),MINSC_BERSERK)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_HARMLESS)
  !CheckSpellState(SecondNearestEnemyOf(Myself),POTION_OF_CLARITY)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(SecondNearestEnemyOf(Myself),25,RESISTMAGIC)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_DominationTimer","LOCALS")
  HaveSpell(WIZARD_DOMINATION)
  !Class(NearestEnemyOf(Myself),MONK)
  !Kit(NearestEnemyOf(Myself),INQUISITOR)
  !Kit(NearestEnemyOf(Myself),CAVALIER)
  !Race(NearestEnemyOf(Myself),ELF)
  !HasItemEquiped("HELM06",NearestEnemyOf(Myself)) // Helm of Charm Protection
  !HasItemEquiped("MISCBC",NearestEnemyOf(Myself)) // Blackrazor
  !HasItemEquiped("NPCHAN",NearestEnemyOf(Myself)) // Corthala Family Armor
  !HasItemEquiped("REAVER",NearestEnemyOf(Myself)) // Unholy Reaver
  !HasItemEquiped("SHLD25",NearestEnemyOf(Myself)) // Shield of Harmony +2
  !HasItemEquipedReal("SPER07",NearestEnemyOf(Myself)) // Spear of the Unicorn +2           
  !HasItemEquipedReal("STAF11",NearestEnemyOf(Myself)) // Staff of the Magi
  !HasItemEquipedReal("SW1H35",NearestEnemyOf(Myself)) // Adjatha the Drinker +2
  !HasItemEquipedReal("SW1H54",NearestEnemyOf(Myself)) // The Equalizer
  !HasItemEquipedReal("SW2H14",NearestEnemyOf(Myself)) // Lilarcor
  !CheckSpellState(NearestEnemyOf(Myself),SI_ENCHANTMENT)
  !Gender(NearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(NearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(NearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(NearestEnemyOf(Myself),MINSC_BERSERK)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(NearestEnemyOf(Myself),STATE_HARMLESS)
  !CheckSpellState(NearestEnemyOf(Myself),POTION_OF_CLARITY)
  !CheckStatGT(NearestEnemyOf(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(NearestEnemyOf(Myself),25,RESISTMAGIC)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_DominationTimer","LOCALS")
  HaveSpell(WIZARD_DOMINATION)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !Class(LastSeenBy(Myself),MONK)
  !Kit(LastSeenBy(Myself),INQUISITOR)
  !Kit(LastSeenBy(Myself),CAVALIER)
  !Race(LastSeenBy(Myself),ELF)
  !HasItemEquiped("HELM06",LastSeenBy(Myself)) // Helm of Charm Protection
  !HasItemEquiped("MISCBC",LastSeenBy(Myself)) // Blackrazor
  !HasItemEquiped("NPCHAN",LastSeenBy(Myself)) // Corthala Family Armor
  !HasItemEquiped("REAVER",LastSeenBy(Myself)) // Unholy Reaver
  !HasItemEquiped("SHLD25",LastSeenBy(Myself)) // Shield of Harmony +2
  !HasItemEquipedReal("SPER07",LastSeenBy(Myself)) // Spear of the Unicorn +2           
  !HasItemEquipedReal("STAF11",LastSeenBy(Myself)) // Staff of the Magi
  !HasItemEquipedReal("SW1H35",LastSeenBy(Myself)) // Adjatha the Drinker +2
  !HasItemEquipedReal("SW1H54",LastSeenBy(Myself)) // The Equalizer
  !HasItemEquipedReal("SW2H14",LastSeenBy(Myself)) // Lilarcor
  !CheckSpellState(LastSeenBy(Myself),SI_ENCHANTMENT)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),MINSC_BERSERK)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckSpellState(LastSeenBy(Myself),POTION_OF_CLARITY)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_DominationTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_DOMINATION)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Animate Dead
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SummonTimer","LOCALS")
  See(NearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_ANIMATE_DEAD)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_SummonTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_ANIMATE_DEAD)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Hold Person 
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_HoldTimer","LOCALS")
  HaveSpell(WIZARD_HOLD_PERSON)
  !HasItem("MORSWORD",SecondNearest([GOODCUTOFF.0.0.THIEF]))  // Mordenkainen's Sword
  !HasItemEquiped("RING09",SecondNearest([GOODCUTOFF.0.0.THIEF]))  // Edventar's Gift
  !HasItemEquipedReal("SW2H06",SecondNearest([GOODCUTOFF.0.0.THIEF]))  // Spider's Bane +2
  !HasItemEquiped("NPSW01",SecondNearest([GOODCUTOFF.0.0.THIEF])) // Sword of Avoreen
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.THIEF]),SI_ENCHANTMENT)
  !Gender(SecondNearest([GOODCUTOFF.0.0.THIEF]),SUMMONED)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.THIEF]),BARBARIAN_RAGE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.THIEF]),BERSERKER_RAGE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.THIEF]),MINSC_BERSERK)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.THIEF]),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.THIEF]),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.THIEF]),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.THIEF]),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.THIEF]),STATE_HARMLESS)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.THIEF]),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.THIEF]),0,CLERIC_FREE_ACTION)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.THIEF]),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.THIEF]),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.THIEF]),0,SANCTUARY)
  CheckStat(SecondNearest([GOODCUTOFF.0.0.THIEF]),0,MINORGLOBE)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.THIEF]),25,RESISTMAGIC)
  See(SecondNearest([GOODCUTOFF.0.0.THIEF]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_HoldTimer","LOCALS")
  HaveSpell(WIZARD_HOLD_PERSON)
  !HasItem("MORSWORD",[GOODCUTOFF.0.0.THIEF])  // Mordenkainen's Sword
  !HasItemEquiped("RING09",[GOODCUTOFF.0.0.THIEF])  // Edventar's Gift
  !HasItemEquipedReal("SW2H06",[GOODCUTOFF.0.0.THIEF])  // Spider's Bane +2
  !HasItemEquiped("NPSW01",[GOODCUTOFF.0.0.THIEF]) // Sword of Avoreen
  !CheckSpellState([GOODCUTOFF.0.0.THIEF],SI_ENCHANTMENT)
  !Gender([GOODCUTOFF.0.0.THIEF],SUMMONED)
  !CheckSpellState([GOODCUTOFF.0.0.THIEF],BARBARIAN_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.THIEF],BERSERKER_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.THIEF],MINSC_BERSERK)
  CheckStatLT([GOODCUTOFF.0.0.THIEF],1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT([GOODCUTOFF.0.0.THIEF],1,WIZARD_SPELL_TURNING)
  !CheckStat([GOODCUTOFF.0.0.THIEF],1,WIZARD_SPELL_TRAP)
  !CheckStat([GOODCUTOFF.0.0.THIEF],1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck([GOODCUTOFF.0.0.THIEF],STATE_HARMLESS)
  !CheckStatGT([GOODCUTOFF.0.0.THIEF],0,CLERIC_CHAOTIC_COMMANDS)
  !CheckStatGT([GOODCUTOFF.0.0.THIEF],0,CLERIC_FREE_ACTION)
  !StateCheck([GOODCUTOFF.0.0.THIEF],STATE_NOT_TARGETABLE)
  !StateCheck([GOODCUTOFF.0.0.THIEF],STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT([GOODCUTOFF.0.0.THIEF],0,SANCTUARY)
  CheckStat([GOODCUTOFF.0.0.THIEF],0,MINORGLOBE)
  !CheckStatGT([GOODCUTOFF.0.0.THIEF],25,RESISTMAGIC)
  See([GOODCUTOFF.0.0.THIEF])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_HoldTimer","LOCALS")
  HaveSpell(WIZARD_HOLD_PERSON)
  !HasItem("MORSWORD",SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]))  // Mordenkainen's Sword
  !HasItemEquiped("RING09",SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]))  // Edventar's Gift
  !HasItemEquipedReal("SW2H06",SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]))  // Spider's Bane +2
  !HasItemEquiped("NPSW01",SecondNearest([GOODCUTOFF.0.0.RANGER_ALL])) // Sword of Avoreen
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),SI_ENCHANTMENT)
  !Gender(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),SUMMONED)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),BARBARIAN_RAGE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),BERSERKER_RAGE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),MINSC_BERSERK)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),STATE_HARMLESS)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),0,CLERIC_FREE_ACTION)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),0,SANCTUARY)
  CheckStat(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),0,MINORGLOBE)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),25,RESISTMAGIC)
  See(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_HoldTimer","LOCALS")
  HaveSpell(WIZARD_HOLD_PERSON)
  !HasItem("MORSWORD",[GOODCUTOFF.0.0.RANGER_ALL])  // Mordenkainen's Sword
  !HasItemEquiped("RING09",[GOODCUTOFF.0.0.RANGER_ALL])  // Edventar's Gift
  !HasItemEquipedReal("SW2H06",[GOODCUTOFF.0.0.RANGER_ALL])  // Spider's Bane +2
  !HasItemEquiped("NPSW01",[GOODCUTOFF.0.0.RANGER_ALL]) // Sword of Avoreen
  !CheckSpellState([GOODCUTOFF.0.0.RANGER_ALL],SI_ENCHANTMENT)
  !Gender([GOODCUTOFF.0.0.RANGER_ALL],SUMMONED)
  !CheckSpellState([GOODCUTOFF.0.0.RANGER_ALL],BARBARIAN_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.RANGER_ALL],BERSERKER_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.RANGER_ALL],MINSC_BERSERK)
  CheckStatLT([GOODCUTOFF.0.0.RANGER_ALL],1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT([GOODCUTOFF.0.0.RANGER_ALL],1,WIZARD_SPELL_TURNING)
  !CheckStat([GOODCUTOFF.0.0.RANGER_ALL],1,WIZARD_SPELL_TRAP)
  !CheckStat([GOODCUTOFF.0.0.RANGER_ALL],1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck([GOODCUTOFF.0.0.RANGER_ALL],STATE_HARMLESS)
  !CheckStatGT([GOODCUTOFF.0.0.RANGER_ALL],0,CLERIC_CHAOTIC_COMMANDS)
  !CheckStatGT([GOODCUTOFF.0.0.RANGER_ALL],0,CLERIC_FREE_ACTION)
  !StateCheck([GOODCUTOFF.0.0.RANGER_ALL],STATE_NOT_TARGETABLE)
  !StateCheck([GOODCUTOFF.0.0.RANGER_ALL],STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT([GOODCUTOFF.0.0.RANGER_ALL],0,SANCTUARY)
  CheckStat([GOODCUTOFF.0.0.RANGER_ALL],0,MINORGLOBE)
  !CheckStatGT([GOODCUTOFF.0.0.RANGER_ALL],25,RESISTMAGIC)
  See([GOODCUTOFF.0.0.RANGER_ALL])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_HoldTimer","LOCALS")
  HaveSpell(WIZARD_HOLD_PERSON)
  !Kit(SecondNearest([GOODCUTOFF.0.0.PALADIN]),INQUISITOR)
  !Kit(SecondNearest([GOODCUTOFF.0.0.PALADIN]),UNDEADHUNTER)
  !HasItem("MORSWORD",SecondNearest([GOODCUTOFF.0.0.PALADIN]))  // Mordenkainen's Sword
  !HasItemEquiped("RING09",SecondNearest([GOODCUTOFF.0.0.PALADIN]))  // Edventar's Gift
  !HasItemEquipedReal("SW2H06",SecondNearest([GOODCUTOFF.0.0.PALADIN]))  // Spider's Bane +2
  !HasItemEquiped("NPSW01",SecondNearest([GOODCUTOFF.0.0.PALADIN])) // Sword of Avoreen
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.PALADIN]),SI_ENCHANTMENT)
  !Gender(SecondNearest([GOODCUTOFF.0.0.PALADIN]),SUMMONED)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.PALADIN]),BARBARIAN_RAGE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.PALADIN]),BERSERKER_RAGE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.PALADIN]),MINSC_BERSERK)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.PALADIN]),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.PALADIN]),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.PALADIN]),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.PALADIN]),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.PALADIN]),STATE_HARMLESS)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.PALADIN]),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.PALADIN]),0,CLERIC_FREE_ACTION)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.PALADIN]),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.PALADIN]),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.PALADIN]),0,SANCTUARY)
  CheckStat(SecondNearest([GOODCUTOFF.0.0.PALADIN]),0,MINORGLOBE)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.PALADIN]),25,RESISTMAGIC)
  See(SecondNearest([GOODCUTOFF.0.0.PALADIN]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_HoldTimer","LOCALS")
  HaveSpell(WIZARD_HOLD_PERSON)
  !Kit([GOODCUTOFF.0.0.PALADIN],INQUISITOR)
  !Kit([GOODCUTOFF.0.0.PALADIN],UNDEADHUNTER)
  !HasItem("MORSWORD",[GOODCUTOFF.0.0.PALADIN])  // Mordenkainen's Sword
  !HasItemEquiped("RING09",[GOODCUTOFF.0.0.PALADIN])  // Edventar's Gift
  !HasItemEquipedReal("SW2H06",[GOODCUTOFF.0.0.PALADIN])  // Spider's Bane +2
  !HasItemEquiped("NPSW01",[GOODCUTOFF.0.0.PALADIN]) // Sword of Avoreen
  !CheckSpellState([GOODCUTOFF.0.0.PALADIN],SI_ENCHANTMENT)
  !Gender([GOODCUTOFF.0.0.PALADIN],SUMMONED)
  !CheckSpellState([GOODCUTOFF.0.0.PALADIN],BARBARIAN_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.PALADIN],BERSERKER_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.PALADIN],MINSC_BERSERK)
  CheckStatLT([GOODCUTOFF.0.0.PALADIN],1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT([GOODCUTOFF.0.0.PALADIN],1,WIZARD_SPELL_TURNING)
  !CheckStat([GOODCUTOFF.0.0.PALADIN],1,WIZARD_SPELL_TRAP)
  !CheckStat([GOODCUTOFF.0.0.PALADIN],1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck([GOODCUTOFF.0.0.PALADIN],STATE_HARMLESS)
  !CheckStatGT([GOODCUTOFF.0.0.PALADIN],0,CLERIC_CHAOTIC_COMMANDS)
  !CheckStatGT([GOODCUTOFF.0.0.PALADIN],0,CLERIC_FREE_ACTION)
  !StateCheck([GOODCUTOFF.0.0.PALADIN],STATE_NOT_TARGETABLE)
  !StateCheck([GOODCUTOFF.0.0.PALADIN],STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT([GOODCUTOFF.0.0.PALADIN],0,SANCTUARY)
  CheckStat([GOODCUTOFF.0.0.PALADIN],0,MINORGLOBE)
  !CheckStatGT([GOODCUTOFF.0.0.PALADIN],25,RESISTMAGIC)
  See([GOODCUTOFF.0.0.PALADIN])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_HoldTimer","LOCALS")
  HaveSpell(WIZARD_HOLD_PERSON)
  !HasItem("MORSWORD",SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]))  // Mordenkainen's Sword
  !HasItemEquiped("RING09",SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]))  // Edventar's Gift
  !HasItemEquipedReal("SW2H06",SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]))  // Spider's Bane +2
  !HasItemEquiped("NPSW01",SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL])) // Sword of Avoreen
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),SI_ENCHANTMENT)
  !Gender(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),SUMMONED)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),BARBARIAN_RAGE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),BERSERKER_RAGE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),MINSC_BERSERK)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),STATE_HARMLESS)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),0,CLERIC_FREE_ACTION)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),0,SANCTUARY)
  CheckStat(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),0,MINORGLOBE)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),25,RESISTMAGIC)
  See(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_HoldTimer","LOCALS")
  HaveSpell(WIZARD_HOLD_PERSON)
  !HasItem("MORSWORD",[GOODCUTOFF.0.0.FIGHTER_ALL])  // Mordenkainen's Sword
  !HasItemEquiped("RING09",[GOODCUTOFF.0.0.FIGHTER_ALL])  // Edventar's Gift
  !HasItemEquipedReal("SW2H06",[GOODCUTOFF.0.0.FIGHTER_ALL])  // Spider's Bane +2
  !HasItemEquiped("NPSW01",[GOODCUTOFF.0.0.FIGHTER_ALL]) // Sword of Avoreen
  !CheckSpellState([GOODCUTOFF.0.0.FIGHTER_ALL],SI_ENCHANTMENT)
  !Gender([GOODCUTOFF.0.0.FIGHTER_ALL],SUMMONED)
  !CheckSpellState([GOODCUTOFF.0.0.FIGHTER_ALL],BARBARIAN_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.FIGHTER_ALL],BERSERKER_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.FIGHTER_ALL],MINSC_BERSERK)
  CheckStatLT([GOODCUTOFF.0.0.FIGHTER_ALL],1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT([GOODCUTOFF.0.0.FIGHTER_ALL],1,WIZARD_SPELL_TURNING)
  !CheckStat([GOODCUTOFF.0.0.FIGHTER_ALL],1,WIZARD_SPELL_TRAP)
  !CheckStat([GOODCUTOFF.0.0.FIGHTER_ALL],1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck([GOODCUTOFF.0.0.FIGHTER_ALL],STATE_HARMLESS)
  !CheckStatGT([GOODCUTOFF.0.0.FIGHTER_ALL],0,CLERIC_CHAOTIC_COMMANDS)
  !CheckStatGT([GOODCUTOFF.0.0.FIGHTER_ALL],0,CLERIC_FREE_ACTION)
  !StateCheck([GOODCUTOFF.0.0.FIGHTER_ALL],STATE_NOT_TARGETABLE)
  !StateCheck([GOODCUTOFF.0.0.FIGHTER_ALL],STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT([GOODCUTOFF.0.0.FIGHTER_ALL],0,SANCTUARY)
  CheckStat([GOODCUTOFF.0.0.FIGHTER_ALL],0,MINORGLOBE)
  !CheckStatGT([GOODCUTOFF.0.0.FIGHTER_ALL],25,RESISTMAGIC)
  See([GOODCUTOFF.0.0.FIGHTER_ALL])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_HoldTimer","LOCALS")
  HaveSpell(WIZARD_HOLD_PERSON)
  !HasItem("MORSWORD",SecondNearest([GOODCUTOFF.0.0.FIGHTER]))  // Mordenkainen's Sword
  !HasItemEquiped("RING09",SecondNearest([GOODCUTOFF.0.0.FIGHTER]))  // Edventar's Gift
  !HasItemEquipedReal("SW2H06",SecondNearest([GOODCUTOFF.0.0.FIGHTER]))  // Spider's Bane +2
  !HasItemEquiped("NPSW01",SecondNearest([GOODCUTOFF.0.0.FIGHTER])) // Sword of Avoreen
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),SI_ENCHANTMENT)
  !Gender(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),SUMMONED)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),BARBARIAN_RAGE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),BERSERKER_RAGE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),MINSC_BERSERK)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),STATE_HARMLESS)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),0,CLERIC_FREE_ACTION)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),0,SANCTUARY)
  CheckStat(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),0,MINORGLOBE)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),25,RESISTMAGIC)
  See(SecondNearest([GOODCUTOFF.0.0.FIGHTER]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_HoldTimer","LOCALS")
  HaveSpell(WIZARD_HOLD_PERSON)
  !HasItem("MORSWORD",[GOODCUTOFF.0.0.FIGHTER])  // Mordenkainen's Sword
  !HasItemEquiped("RING09",[GOODCUTOFF.0.0.FIGHTER])  // Edventar's Gift
  !HasItemEquipedReal("SW2H06",[GOODCUTOFF.0.0.FIGHTER])  // Spider's Bane +2
  !HasItemEquiped("NPSW01",[GOODCUTOFF.0.0.FIGHTER]) // Sword of Avoreen
  !CheckSpellState([GOODCUTOFF.0.0.FIGHTER],SI_ENCHANTMENT)
  !Gender([GOODCUTOFF.0.0.FIGHTER],SUMMONED)
  !CheckSpellState([GOODCUTOFF.0.0.FIGHTER],BARBARIAN_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.FIGHTER],BERSERKER_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.FIGHTER],MINSC_BERSERK)
  CheckStatLT([GOODCUTOFF.0.0.FIGHTER],1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT([GOODCUTOFF.0.0.FIGHTER],1,WIZARD_SPELL_TURNING)
  !CheckStat([GOODCUTOFF.0.0.FIGHTER],1,WIZARD_SPELL_TRAP)
  !CheckStat([GOODCUTOFF.0.0.FIGHTER],1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck([GOODCUTOFF.0.0.FIGHTER],STATE_HARMLESS)
  !CheckStatGT([GOODCUTOFF.0.0.FIGHTER],0,CLERIC_CHAOTIC_COMMANDS)
  !CheckStatGT([GOODCUTOFF.0.0.FIGHTER],0,CLERIC_FREE_ACTION)
  !StateCheck([GOODCUTOFF.0.0.FIGHTER],STATE_NOT_TARGETABLE)
  !StateCheck([GOODCUTOFF.0.0.FIGHTER],STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT([GOODCUTOFF.0.0.FIGHTER],0,SANCTUARY)
  CheckStat([GOODCUTOFF.0.0.FIGHTER],0,MINORGLOBE)
  !CheckStatGT([GOODCUTOFF.0.0.FIGHTER],25,RESISTMAGIC)
  See([GOODCUTOFF.0.0.FIGHTER])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_HoldTimer","LOCALS")
  HaveSpell(WIZARD_HOLD_PERSON)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !Kit(LastSeenBy(Myself),INQUISITOR)
  !Kit(LastSeenBy(Myself),UNDEADHUNTER)
  !HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
  !HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
  !HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2
  !HasItemEquiped("NPSW01",LastSeenBy(Myself)) // Sword of Avoreen
  !CheckSpellState(LastSeenBy(Myself),SI_ENCHANTMENT)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),MINSC_BERSERK)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_HoldTimer","LOCALS",12)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_HOLD_PERSON)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Lightning Bolt 
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_LightningBoltTimer","LOCALS")
  HaveSpell(WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Lightning Bolt)
  !HasItemEquiped("CLCK24",SixthNearestEnemyOf(Myself)) // Cloak of reflection
  !HasItemEquiped("CLCK26",SixthNearestEnemyOf(Myself)) // Cloak of Mirroring
  CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTELECTRICITY)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_LightningBoltTimer","LOCALS")
  HaveSpell(WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Lightning Bolt)
  !HasItemEquiped("CLCK24",FifthNearestEnemyOf(Myself)) // Cloak of reflection
  !HasItemEquiped("CLCK26",FifthNearestEnemyOf(Myself)) // Cloak of Mirroring
  CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTELECTRICITY)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_LightningBoltTimer","LOCALS")
  HaveSpell(WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Lightning Bolt)
  !HasItemEquiped("CLCK24",FourthNearestEnemyOf(Myself)) // Cloak of reflection
  !HasItemEquiped("CLCK26",FourthNearestEnemyOf(Myself)) // Cloak of Mirroring
  CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTELECTRICITY)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_LightningBoltTimer","LOCALS")
  HaveSpell(WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Lightning Bolt)
  !HasItemEquiped("CLCK24",ThirdNearestEnemyOf(Myself)) // Cloak of reflection
  !HasItemEquiped("CLCK26",ThirdNearestEnemyOf(Myself)) // Cloak of Mirroring
  CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTELECTRICITY)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_LightningBoltTimer","LOCALS")
  HaveSpell(WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Lightning Bolt)
  !HasItemEquiped("CLCK24",SecondNearestEnemyOf(Myself)) // Cloak of reflection
  !HasItemEquiped("CLCK26",SecondNearestEnemyOf(Myself)) // Cloak of Mirroring
  CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTELECTRICITY)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_LightningBoltTimer","LOCALS")
  HaveSpell(WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Lightning Bolt)
  !HasItemEquiped("CLCK24",NearestEnemyOf(Myself)) // Cloak of reflection
  !HasItemEquiped("CLCK26",NearestEnemyOf(Myself)) // Cloak of Mirroring
  CheckStatLT(NearestEnemyOf(Myself),50,RESISTELECTRICITY)
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_LightningBoltTimer","LOCALS")
  HaveSpell(WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Lightning Bolt)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !HasItemEquiped("CLCK24",LastSeenBy(Myself)) // Cloak of reflection
  !HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
  CheckStatLT(LastSeenBy(Myself),50,RESISTELECTRICITY)
  !CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_LightningBoltTimer","LOCALS",12)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Skull Trap 
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SkullTrapTimer","LOCALS")
  HaveSpell(WIZARD_SKULL_TRAP)
  !Range(ThirdFarthestEnemyOf(Myself),12)
  !HasItemEquiped("CLCK26",ThirdFarthestEnemyOf(Myself)) // Cloak of Mirroring
  !CheckSpellState(ThirdFarthestEnemyOf(Myself),SI_NECROMANCY)
  CheckStat(ThirdFarthestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(ThirdFarthestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(ThirdFarthestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(ThirdFarthestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(ThirdFarthestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdFarthestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdFarthestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdFarthestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(ThirdFarthestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(ThirdFarthestEnemyOf(Myself),50,MAGICDAMAGERESISTANCE)
  See(ThirdFarthestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SkullTrapTimer","LOCALS")
  HaveSpell(WIZARD_SKULL_TRAP)
  !Range(SecondFarthestEnemyOf(Myself),12)
  !HasItemEquiped("CLCK26",SecondFarthestEnemyOf(Myself)) // Cloak of Mirroring
  !CheckSpellState(SecondFarthestEnemyOf(Myself),SI_NECROMANCY)
  CheckStat(SecondFarthestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(SecondFarthestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(SecondFarthestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(SecondFarthestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SecondFarthestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondFarthestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondFarthestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondFarthestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(SecondFarthestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SecondFarthestEnemyOf(Myself),50,MAGICDAMAGERESISTANCE)
  See(SecondFarthestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SkullTrapTimer","LOCALS")
  HaveSpell(WIZARD_SKULL_TRAP)
  !Range(FarthestEnemyOf(Myself),12)
  !HasItemEquiped("CLCK26",FarthestEnemyOf(Myself)) // Cloak of Mirroring
  !CheckSpellState(FarthestEnemyOf(Myself),SI_NECROMANCY)
  CheckStat(FarthestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(FarthestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(FarthestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(FarthestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FarthestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FarthestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FarthestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FarthestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(FarthestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FarthestEnemyOf(Myself),50,MAGICDAMAGERESISTANCE)
  See(FarthestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SkullTrapTimer","LOCALS")
  HaveSpell(WIZARD_SKULL_TRAP)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !Range(LastSeenBy(Myself),12)
  !HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  CheckStatLT(LastSeenBy(Myself),50,MAGICDAMAGERESISTANCE)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_SkullTrapTimer","LOCALS",12)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SKULL_TRAP)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Magic Missile
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",SixthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SixthNearestEnemyOf(Myself))
  CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),80,MAGICDAMAGERESISTANCE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SixthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(SixthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",FifthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FifthNearestEnemyOf(Myself))
  CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),80,MAGICDAMAGERESISTANCE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FifthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(FifthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",FourthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FourthNearestEnemyOf(Myself))
  CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),80,MAGICDAMAGERESISTANCE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FourthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(FourthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",ThirdNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",ThirdNearestEnemyOf(Myself))
  CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),80,MAGICDAMAGERESISTANCE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",SecondNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SecondNearestEnemyOf(Myself))
  CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),80,MAGICDAMAGERESISTANCE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SecondNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(SecondNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",NearestEnemyOf(Myself))
  !HasItemEquiped("shld24",NearestEnemyOf(Myself))
  CheckStatLT(NearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(NearestEnemyOf(Myself),80,MAGICDAMAGERESISTANCE)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(NearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(NearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",SixthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SixthNearestEnemyOf(Myself))
  CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),40,MAGICDAMAGERESISTANCE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SixthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(SixthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",FifthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FifthNearestEnemyOf(Myself))
  CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),40,MAGICDAMAGERESISTANCE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FifthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(FifthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",FourthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FourthNearestEnemyOf(Myself))
  CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),40,MAGICDAMAGERESISTANCE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FourthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(FourthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",ThirdNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",ThirdNearestEnemyOf(Myself))
  CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),40,MAGICDAMAGERESISTANCE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",SecondNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SecondNearestEnemyOf(Myself))
  CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),40,MAGICDAMAGERESISTANCE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SecondNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(SecondNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",NearestEnemyOf(Myself))
  !HasItemEquiped("shld24",NearestEnemyOf(Myself))
  CheckStatLT(NearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(NearestEnemyOf(Myself),40,MAGICDAMAGERESISTANCE)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(NearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(NearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",SixthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SixthNearestEnemyOf(Myself))
  CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),10,MAGICDAMAGERESISTANCE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SixthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(SixthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",FifthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FifthNearestEnemyOf(Myself))
  CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),10,MAGICDAMAGERESISTANCE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FifthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(FifthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",FourthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FourthNearestEnemyOf(Myself))
  CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),10,MAGICDAMAGERESISTANCE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FourthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(FourthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",ThirdNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",ThirdNearestEnemyOf(Myself))
  CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),10,MAGICDAMAGERESISTANCE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",SecondNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SecondNearestEnemyOf(Myself))
  CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),10,MAGICDAMAGERESISTANCE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SecondNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(SecondNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",NearestEnemyOf(Myself))
  !HasItemEquiped("shld24",NearestEnemyOf(Myself))
  CheckStatLT(NearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(NearestEnemyOf(Myself),10,MAGICDAMAGERESISTANCE)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(NearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(NearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  See(LastSeenBy(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !HasItemEquiped("clck26",LastSeenBy(Myself))
  !HasItemEquiped("shld24",LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  CheckStatLT(LastSeenBy(Myself),80,MAGICDAMAGERESISTANCE)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(LastSeenBy(Myself),ENTROPY_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SHIELD)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Attack
/////////////////////////////////////////////////////////////////////
IF
  OR(6)
    See(Player1)
    See(Player2)
    See(Player3)
    See(Player4)
    See(Player5)
    See(Player6)
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  CheckStatLT(NearestEnemyOf(Myself),1,SANCTUARY)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,SANCTUARY)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,SANCTUARY)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,SANCTUARY)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,SANCTUARY)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,SANCTUARY)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(NearestEnemyOf(Myself),1,SANCTUARY)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,SANCTUARY)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,SANCTUARY)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,SANCTUARY)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,SANCTUARY)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,SANCTUARY)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(NearestEnemyOf(Myself),1,SANCTUARY)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,SANCTUARY)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,SANCTUARY)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,SANCTUARY)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,SANCTUARY)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,SANCTUARY)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
  !StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(NearestEnemyOf(Myself),1,SANCTUARY)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

// EEex - Is Moving Check 1

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,SANCTUARY)
  Range(SixthNearestEnemyOf(Myself),5)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,SANCTUARY)
  Range(FifthNearestEnemyOf(Myself),5)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,SANCTUARY)
  Range(FourthNearestEnemyOf(Myself),5)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,SANCTUARY)
  Range(ThirdNearestEnemyOf(Myself),5)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,SANCTUARY)
  Range(SecondNearestEnemyOf(Myself),5)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
  !StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(NearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(NearestEnemyOf(Myself),1,SANCTUARY)
  Range(NearestEnemyOf(Myself),5)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

// EEex - Is Moving Check 2

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  StateCheck(SixthNearestEnemyOf(Myself),STATE_IMMOBILE)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,SANCTUARY)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
  StateCheck(FifthNearestEnemyOf(Myself),STATE_IMMOBILE)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,SANCTUARY)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
  StateCheck(FourthNearestEnemyOf(Myself),STATE_IMMOBILE)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,SANCTUARY)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
  StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMMOBILE)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,SANCTUARY)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
  StateCheck(SecondNearestEnemyOf(Myself),STATE_IMMOBILE)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,SANCTUARY)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
  StateCheck(NearestEnemyOf(Myself),STATE_IMMOBILE)
  CheckStatLT(NearestEnemyOf(Myself),1,SANCTUARY)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

// EEex - Target Caster (Melee)

IF
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  WeaponEffectiveVs(LastSeenBy(Myself),MAINHAND)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  OR(2)
    CheckStatLT(Myself,1,SANCTUARY)
    HPPercentGT(Myself,49)
THEN
  RESPONSE #100
    SetGlobal("MO_AttackedSomeone","LOCALS",1)
    AttackReevaluate(LastSeenBy(Myself),30)
END

IF
  !Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  Allegiance(LastSeenBy(Myself),ENEMY)
  WeaponEffectiveVs(LastSeenBy(Myself),MAINHAND)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  OR(2)
    CheckStatLT(Myself,1,SANCTUARY)
    HPPercentGT(Myself,49)
THEN
  RESPONSE #100
    SetGlobal("MO_AttackedSomeone","LOCALS",1)
    AttackReevaluate(LastSeenBy(Myself),30)
END