IF
    AttackedBy([GOODCUTOFF],DEFAULT)
    Global("AC#PPFinalBossDialog","ACPP72",0)
THEN
    RESPONSE #100
        SetGlobal("AC#PPFinalBossDialog","ACPP72",1)
END

IF
    NumberOfTimesTalkedTo(0)
    See([PC])
THEN
    RESPONSE #100
        StartDialogueNoSet([PC])
END

IF
    Global("FinalBossBreak","ACPP72",0)
    HPLT(Myself,10)
THEN
    RESPONSE #100
        SetGlobal("FinalBossBreak","ACPP72",1)
        StartDialogueNoSet([PC])
END

IF
    AttackedBy([GOODCUTOFF],DEFAULT)
    !Allegiance(Myself,ENEMY)
THEN
    RESPONSE #100
        Enemy()
END

/////////////////////////////////////////////////////////////////////
// True Sight Check
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_EnemyTrueSightTimer","GLOBAL")
  Global("MO_EnemyTrueSight","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("MO_EnemyTrueSight","GLOBAL",0)
END

IF
  Global("MO_TrueSightActive","LOCALS",1)
  CheckStat(Myself,0,TRUE_SIGHT)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",0)
    SetGlobal("MO_EnemyTrueSight","GLOBAL",0)
END

/////////////////////////////////////////////////////////////////////
// Prep
/////////////////////////////////////////////////////////////////////
IF
  See(NearestEnemyOf(Myself))
  Global("prep","LOCALS",0)
  DifficultyGT(HARD)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,CLERIC_BARKSKIN)  // SPPR202.SPL (Barkskin)
    ReallyForceSpell(Myself,CLERIC_CHANT)  // SPPR203.SPL (Chant))
    ReallyForceSpell(Myself,CLERIC_REGENERATE)  // SPPR711.SPL (Regeneration)
    ReallyForceSpell(Myself,NPC_BLADE_BARRIER)  // SPPR698.SPL (Blade Barrier)
    ReallyForceSpell(Myself,CLERIC_FREE_ACTION)  // SPPR403.SPL (Free Action)
    ReallyForceSpell(Myself,CLERIC_CONJURE_EARTH_ELEMENTAL)  // SPPR702.SPL (Conjure Earth Elemental)
    SetGlobal("prep","LOCALS",1)
END

IF
  See(NearestEnemyOf(Myself))
  Global("prep","LOCALS",0)
  Difficulty(HARD)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,CLERIC_BARKSKIN)  // SPPR202.SPL (Barkskin)
    ReallyForceSpell(Myself,CLERIC_CHANT)  // SPPR203.SPL (Chant))
    ReallyForceSpell(Myself,CLERIC_REGENERATE)  // SPPR711.SPL (Regeneration)
    ReallyForceSpell(Myself,NPC_BLADE_BARRIER)  // SPPR698.SPL (Blade Barrier)
    ReallyForceSpell(Myself,CLERIC_FREE_ACTION)  // SPPR403.SPL (Free Action)
    SetGlobal("prep","LOCALS",1)
END

IF
  See(NearestEnemyOf(Myself))
  Global("prep","LOCALS",0)
  Difficulty(NORMAL)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,CLERIC_BARKSKIN)  // SPPR202.SPL (Barkskin)
    ReallyForceSpell(Myself,CLERIC_CHANT)  // SPPR203.SPL (Chant))
    ReallyForceSpell(Myself,CLERIC_REGENERATE)  // SPPR711.SPL (Regeneration)
    ReallyForceSpell(Myself,CLERIC_FREE_ACTION)  // SPPR403.SPL (Free Action)
    SetGlobal("prep","LOCALS",1)
END

IF
  See(NearestEnemyOf(Myself))
  Global("prep","LOCALS",0)
  DifficultyLT(NORMAL)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,CLERIC_BARKSKIN)  // SPPR202.SPL (Barkskin)
    ReallyForceSpell(Myself,CLERIC_CHANT)  // SPPR203.SPL (Chant))
    ReallyForceSpell(Myself,CLERIC_FREE_ACTION)  // SPPR403.SPL (Free Action)
    SetGlobal("prep","LOCALS",1)
END

/////////////////////////////////////////////////////////////////////
// Spell: Sanctuary (if nearby enemy)
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Allegiance(Myself,ENEMY)
  HaveSpell(CLERIC_SANCTUARY)
  CheckStatLT(Myself,1,SANCTUARY)
  HPPercentLT(Myself,60)
  CheckStatLT(Myself,40,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(Myself,CLERIC_SANCTUARY)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// True Sight
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_EnemyTrueSight","GLOBAL",0)
  Allegiance(Myself,ENEMY)
  HaveSpell(CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
  OR(6)
    SpellCast([GOODCUTOFF],WIZARD_PROJECT_IMAGE)  // SPWI703.SPL (Project Image)
    SpellCast([GOODCUTOFF],WIZARD_SIMULACRUM)  // SPWI804.SPL (Simulacrum)
    SpellCast([GOODCUTOFF],WIZARD_MISLEAD)  // SPWI607.SPL (Mislead)
    SpellCast([GOODCUTOFF],WIZARD_SHADOW_DOOR)  // SPWI505.SPL (Shadow Door)
    SpellCast([GOODCUTOFF],WIZARD_IMPROVED_INVISIBILITY)  // SPWI405.SPL (Improved Invisibility)
    SpellCast([GOODCUTOFF],WIZARD_INVISIBILITY)  // SPWI206.SPL (Invisibility)
  !CheckSpellState([GOODCUTOFF],SI_DIVINATION)
  CheckStatLT(Myself,40,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_EnemyTrueSight","GLOBAL",1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_EnemyTrueSightTimer","GLOBAL",60)
    SetInterrupt(FALSE)
    Spell(Myself,CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_EnemyTrueSight","GLOBAL",0)
  Allegiance(Myself,ENEMY)
  HaveSpell(CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
  Detect([GOODCUTOFF])
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !CheckSpellState([GOODCUTOFF],SI_DIVINATION)
  CheckStatLT(Myself,40,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_EnemyTrueSight","GLOBAL",1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_EnemyTrueSightTimer","GLOBAL",60)
    SetInterrupt(FALSE)
    Spell(Myself,CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_EnemyTrueSight","GLOBAL",0)
  HaveSpell(CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
  OR(4)
    StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(SixthNearestEnemyOf(Myself),STATE_INVISIBLE)
    CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
    Gender(SixthNearestEnemyOf(Myself),ILLUSIONARY)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_SLEEPING)
  !CheckStat(SixthNearestEnemyOf(Myself),3,WIZARD_SPELL_IMMUNITY)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_EnemyTrueSight","GLOBAL",0)
  HaveSpell(CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
  OR(4)
    StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(FifthNearestEnemyOf(Myself),STATE_INVISIBLE)
    CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
    Gender(FifthNearestEnemyOf(Myself),ILLUSIONARY)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
  !CheckStat(FifthNearestEnemyOf(Myself),3,WIZARD_SPELL_IMMUNITY)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_EnemyTrueSight","GLOBAL",0)
  HaveSpell(CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
  OR(4)
    StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(FourthNearestEnemyOf(Myself),STATE_INVISIBLE)
    CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
    Gender(FourthNearestEnemyOf(Myself),ILLUSIONARY)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
  !CheckStat(FourthNearestEnemyOf(Myself),3,WIZARD_SPELL_IMMUNITY)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_EnemyTrueSight","GLOBAL",0)
  HaveSpell(CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
  OR(4)
    StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(ThirdNearestEnemyOf(Myself),STATE_INVISIBLE)
    CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
    Gender(ThirdNearestEnemyOf(Myself),ILLUSIONARY)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
  !CheckStat(ThirdNearestEnemyOf(Myself),3,WIZARD_SPELL_IMMUNITY)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_EnemyTrueSight","GLOBAL",0)
  HaveSpell(CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
  OR(4)
    StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(SecondNearestEnemyOf(Myself),STATE_INVISIBLE)
    CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
    Gender(SecondNearestEnemyOf(Myself),ILLUSIONARY)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
  !CheckStat(SecondNearestEnemyOf(Myself),3,WIZARD_SPELL_IMMUNITY)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_EnemyTrueSight","GLOBAL",0)
  HaveSpell(CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
  OR(4)
    StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
    CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
    Gender(NearestEnemyOf(Myself),ILLUSIONARY)
  !StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
  !CheckStat(NearestEnemyOf(Myself),3,WIZARD_SPELL_IMMUNITY)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_EnemyTrueSight","GLOBAL",0)
  See(LastSeenBy(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
  CheckStatLT(Myself,40,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_EnemyTrueSight","GLOBAL",1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_EnemyTrueSightTimer","GLOBAL",60)
    SetInterrupt(FALSE)
    Spell(Myself,CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Invisibility Purge
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_EnemyFindInvisible","GLOBAL")
  Global("MO_EnemyTrueSight","GLOBAL",0)
  HaveSpell(CLERIC_INVISIBILITY_PURGE)  // SPPR309.SPL (Invisibility Purge)
  Detect([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
  OR(2)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !StateCheck(LastSeenBy(Myself),STATE_NONDETECTION)
  !CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
  CheckStatLT(Myself,40,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_EnemyFindInvisible","GLOBAL",6)
    SetInterrupt(FALSE)
    Spell(Myself,CLERIC_INVISIBILITY_PURGE)  // SPPR309.SPL (Invisibility Purge)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_EnemyFindInvisible","GLOBAL")
  Global("MO_EnemyTrueSight","GLOBAL",0)
  HaveSpell(CLERIC_DISPEL_MAGIC)  // SPPR303.SPL (Dispel Magic)
  Detect([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
  OR(2)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !StateCheck(LastSeenBy(Myself),STATE_NONDETECTION)
  !CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
  CheckStatLT(Myself,40,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_EnemyFindInvisible","GLOBAL",6)
    SetInterrupt(FALSE)
    RemoveSpell(CLERIC_DISPEL_MAGIC)  // SPPR303.SPL (Dispel Magic)
    SpellNoDec(Myself,CLERIC_INVISIBILITY_PURGE)  // SPPR309.SPL (Invisibility Purge)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_EnemyFindInvisible","GLOBAL")
  Global("MO_EnemyTrueSight","GLOBAL",0)
  HaveSpell(CLERIC_INVISIBILITY_PURGE)  // SPPR309.SPL (Invisibility Purge)
  OR(2)
    StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(SixthNearestEnemyOf(Myself),STATE_INVISIBLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NONDETECTION)
  !CheckStat(SixthNearestEnemyOf(Myself),3,WIZARD_SPELL_IMMUNITY)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_EnemyFindInvisible","GLOBAL")
  Global("MO_EnemyTrueSight","GLOBAL",0)
  HaveSpell(CLERIC_INVISIBILITY_PURGE)  // SPPR309.SPL (Invisibility Purge)
  OR(2)
    StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(FifthNearestEnemyOf(Myself),STATE_INVISIBLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NONDETECTION)
  !CheckStat(FifthNearestEnemyOf(Myself),3,WIZARD_SPELL_IMMUNITY)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_EnemyFindInvisible","GLOBAL")
  Global("MO_EnemyTrueSight","GLOBAL",0)
  HaveSpell(CLERIC_INVISIBILITY_PURGE)  // SPPR309.SPL (Invisibility Purge)
  OR(2)
    StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(FourthNearestEnemyOf(Myself),STATE_INVISIBLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NONDETECTION)
  !CheckStat(FourthNearestEnemyOf(Myself),3,WIZARD_SPELL_IMMUNITY)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_EnemyFindInvisible","GLOBAL")
  Global("MO_EnemyTrueSight","GLOBAL",0)
  HaveSpell(CLERIC_INVISIBILITY_PURGE)  // SPPR309.SPL (Invisibility Purge)
  OR(2)
    StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(ThirdNearestEnemyOf(Myself),STATE_INVISIBLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NONDETECTION)
  !CheckStat(ThirdNearestEnemyOf(Myself),3,WIZARD_SPELL_IMMUNITY)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_EnemyFindInvisible","GLOBAL")
  Global("MO_EnemyTrueSight","GLOBAL",0)
  HaveSpell(CLERIC_INVISIBILITY_PURGE)  // SPPR309.SPL (Invisibility Purge)
  OR(2)
    StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(SecondNearestEnemyOf(Myself),STATE_INVISIBLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NONDETECTION)
  !CheckStat(SecondNearestEnemyOf(Myself),3,WIZARD_SPELL_IMMUNITY)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_EnemyFindInvisible","GLOBAL")
  Global("MO_EnemyTrueSight","GLOBAL",0)
  HaveSpell(CLERIC_INVISIBILITY_PURGE)  // SPPR309.SPL (Invisibility Purge)
  OR(2)
    StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_NONDETECTION)
  !CheckStat(NearestEnemyOf(Myself),3,WIZARD_SPELL_IMMUNITY)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_EnemyFindInvisible","GLOBAL")
  Global("MO_EnemyTrueSight","GLOBAL",0)
  See(LastSeenBy(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(CLERIC_INVISIBILITY_PURGE)  // SPPR309.SPL (Invisibility Purge)
  OR(2)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !StateCheck(LastSeenBy(Myself),STATE_NONDETECTION)
  !CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
  CheckStatLT(Myself,40,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_EnemyFindInvisible","GLOBAL",6)
    SetInterrupt(FALSE)
    Spell(Myself,CLERIC_INVISIBILITY_PURGE)  // SPPR309.SPL (Invisibility Purge)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Cloud of Pestilence
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CloudTimer","LOCALS")
  HaveSpellRES("AC#PPCP")  // Cloud of Pestilence
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTPOISON)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CloudTimer","LOCALS")
  HaveSpellRES("AC#PPCP")  // Cloud of Pestilence
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTPOISON)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CloudTimer","LOCALS")
  HaveSpellRES("AC#PPCP")  // Cloud of Pestilence
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTPOISON)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CloudTimer","LOCALS")
  HaveSpellRES("AC#PPCP")  // Cloud of Pestilence
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTPOISON)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CloudTimer","LOCALS")
  HaveSpellRES("AC#PPCP")  // Cloud of Pestilence
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTPOISON)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CloudTimer","LOCALS")
  HaveSpellRES("AC#PPCP")  // Cloud of Pestilence
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(NearestEnemyOf(Myself),50,RESISTPOISON)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CloudTimer","LOCALS")
  HaveSpellRES("AC#PPCP")  // Cloud of Pestilence
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),50,RESISTPOISON)
  CheckStatLT(Myself,40,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_CloudTimer","LOCALS",30)
    SetInterrupt(FALSE)
    SpellRES("AC#PPCP",NearestEnemyOf(Myself))  // Cloud of Pestilence
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Insects
/////////////////////////////////////////////////////////////////////
IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_InsectPlagueTimer","GLOBAL")
  HaveSpell(CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),99,RESISTMAGIC)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),SI_CONJURATION)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),BLUE_FIRESHIELD)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),RED_FIRESHIELD)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),STATE_NOT_TARGETABLE)
  See(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_InsectPlagueTimer","GLOBAL")
  HaveSpell(CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
  !CheckStatGT([GOODCUTOFF.0.0.DRUID_ALL],99,RESISTMAGIC)
  !CheckStatGT([GOODCUTOFF.0.0.DRUID_ALL],0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState([GOODCUTOFF.0.0.DRUID_ALL],SI_CONJURATION)
  !CheckSpellState([GOODCUTOFF.0.0.DRUID_ALL],BLUE_FIRESHIELD)
  !CheckSpellState([GOODCUTOFF.0.0.DRUID_ALL],RED_FIRESHIELD)
  !CheckStatGT([GOODCUTOFF.0.0.DRUID_ALL],0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
  !StateCheck([GOODCUTOFF.0.0.DRUID_ALL],STATE_NOT_TARGETABLE)
  See([GOODCUTOFF.0.0.DRUID_ALL])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_InsectPlagueTimer","GLOBAL")
  HaveSpell(CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),99,RESISTMAGIC)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),SI_CONJURATION)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),BLUE_FIRESHIELD)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),RED_FIRESHIELD)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),STATE_NOT_TARGETABLE)
  See(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_InsectPlagueTimer","GLOBAL")
  HaveSpell(CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
  !CheckStatGT([GOODCUTOFF.0.0.CLERIC_ALL],99,RESISTMAGIC)
  !CheckStatGT([GOODCUTOFF.0.0.CLERIC_ALL],0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState([GOODCUTOFF.0.0.CLERIC_ALL],SI_CONJURATION)
  !CheckSpellState([GOODCUTOFF.0.0.CLERIC_ALL],BLUE_FIRESHIELD)
  !CheckSpellState([GOODCUTOFF.0.0.CLERIC_ALL],RED_FIRESHIELD)
  !CheckStatGT([GOODCUTOFF.0.0.CLERIC_ALL],0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
  !StateCheck([GOODCUTOFF.0.0.CLERIC_ALL],STATE_NOT_TARGETABLE)
  See([GOODCUTOFF.0.0.CLERIC_ALL])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_InsectPlagueTimer","GLOBAL")
  HaveSpell(CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),99,RESISTMAGIC)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),SI_CONJURATION)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),BLUE_FIRESHIELD)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),RED_FIRESHIELD)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),STATE_NOT_TARGETABLE)
  See(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_InsectPlagueTimer","GLOBAL")
  HaveSpell(CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
  !CheckStatGT([GOODCUTOFF.0.0.BARD_ALL],99,RESISTMAGIC)
  !CheckStatGT([GOODCUTOFF.0.0.BARD_ALL],0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState([GOODCUTOFF.0.0.BARD_ALL],SI_CONJURATION)
  !CheckSpellState([GOODCUTOFF.0.0.BARD_ALL],BLUE_FIRESHIELD)
  !CheckSpellState([GOODCUTOFF.0.0.BARD_ALL],RED_FIRESHIELD)
  !CheckStatGT([GOODCUTOFF.0.0.BARD_ALL],0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
  !StateCheck([GOODCUTOFF.0.0.BARD_ALL],STATE_NOT_TARGETABLE)
  See([GOODCUTOFF.0.0.BARD_ALL])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_InsectPlagueTimer","GLOBAL")
  HaveSpell(CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),99,RESISTMAGIC)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),SI_CONJURATION)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),BLUE_FIRESHIELD)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),RED_FIRESHIELD)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),STATE_NOT_TARGETABLE)
  See(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_InsectPlagueTimer","GLOBAL")
  HaveSpell(CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
  !CheckStatGT([GOODCUTOFF.0.0.MAGE_ALL],99,RESISTMAGIC)
  !CheckStatGT([GOODCUTOFF.0.0.MAGE_ALL],0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE_ALL],SI_CONJURATION)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE_ALL],BLUE_FIRESHIELD)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE_ALL],RED_FIRESHIELD)
  !CheckStatGT([GOODCUTOFF.0.0.MAGE_ALL],0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
  !StateCheck([GOODCUTOFF.0.0.MAGE_ALL],STATE_NOT_TARGETABLE)
  See([GOODCUTOFF.0.0.MAGE_ALL])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_InsectPlagueTimer","GLOBAL")
  HaveSpell(CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
  !CheckStatGT([GOODCUTOFF.0.0.MAGE_THIEF],99,RESISTMAGIC)
  !CheckStatGT([GOODCUTOFF.0.0.MAGE_THIEF],0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE_THIEF],SI_CONJURATION)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE_THIEF],BLUE_FIRESHIELD)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE_THIEF],RED_FIRESHIELD)
  !CheckStatGT([GOODCUTOFF.0.0.MAGE_THIEF],0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
  !StateCheck([GOODCUTOFF.0.0.MAGE_THIEF],STATE_NOT_TARGETABLE)
  See([GOODCUTOFF.0.0.MAGE_THIEF])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_InsectPlagueTimer","GLOBAL")
  HaveSpell(CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
  !CheckStatGT([GOODCUTOFF.0.0.MAGE],99,RESISTMAGIC)
  !CheckStatGT([GOODCUTOFF.0.0.MAGE],0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE],SI_CONJURATION)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE],BLUE_FIRESHIELD)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE],RED_FIRESHIELD)
  !CheckStatGT([GOODCUTOFF.0.0.MAGE],0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
  !StateCheck([GOODCUTOFF.0.0.MAGE],STATE_NOT_TARGETABLE)
  See([GOODCUTOFF.0.0.MAGE])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_InsectPlagueTimer","GLOBAL")
  HaveSpell(CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckStatGT(LastSeenBy(Myself),99,RESISTMAGIC)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !CheckSpellState(LastSeenBy(Myself),BLUE_FIRESHIELD)
  !CheckSpellState(LastSeenBy(Myself),RED_FIRESHIELD)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,40,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  OR(2)
    CheckStatLT(Myself,1,SANCTUARY)
    HPPercentGT(Myself,80)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_InsectPlagueTimer","GLOBAL",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Cloak of Fear
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CloakFearTimer","LOCALS")
  See(ThirdNearestEnemyOf(Myself))
  Range(LastSeenBy(Myself),15)
  HaveSpell(CLERIC_CLOAK_OF_FEAR)  // SPPR416.SPL (Cloak of Fear)
  CheckStatLT(Myself,40,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  OR(2)
    CheckStatLT(Myself,1,SANCTUARY)
    HPPercentGT(Myself,80)
THEN
  RESPONSE #60
    IncrementGlobal("MO_CloakFear","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_CloakFearTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(Myself,CLERIC_CLOAK_OF_FEAR)  // SPPR416.SPL (Cloak of Fear)
    SetInterrupt(TRUE)
  RESPONSE #40
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Unholy Blight
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_UnholyBlightTimer","LOCALS")
  HaveSpell(CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unholy Blight)
  !Difficulty(EASIEST)
  Alignment(Myself,MASK_EVIL)
  Alignment(SixthNearestEnemyOf(Myself),MASK_GOOD)
  Range(SixthNearestEnemyOf(Myself),15)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_NECROMANCY)
  CheckStatLT(SixthNearestEnemyOf(Myself),40,RESISTMAGIC)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_UnholyBlightTimer","LOCALS")
  HaveSpell(CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unholy Blight)
  !Difficulty(EASIEST)
  Alignment(Myself,MASK_EVIL)
  Alignment(FifthNearestEnemyOf(Myself),MASK_GOOD)
  Range(FifthNearestEnemyOf(Myself),15)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_NECROMANCY)
  CheckStatLT(FifthNearestEnemyOf(Myself),40,RESISTMAGIC)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_UnholyBlightTimer","LOCALS")
  HaveSpell(CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unholy Blight)
  !Difficulty(EASIEST)
  Alignment(Myself,MASK_EVIL)
  Alignment(FourthNearestEnemyOf(Myself),MASK_GOOD)
  Range(FourthNearestEnemyOf(Myself),15)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_NECROMANCY)
  CheckStatLT(FourthNearestEnemyOf(Myself),40,RESISTMAGIC)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_UnholyBlightTimer","LOCALS")
  HaveSpell(CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unholy Blight)
  !Difficulty(EASIEST)
  Alignment(Myself,MASK_EVIL)
  Alignment(ThirdNearestEnemyOf(Myself),MASK_GOOD)
  Range(ThirdNearestEnemyOf(Myself),15)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_NECROMANCY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),40,RESISTMAGIC)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_UnholyBlightTimer","LOCALS")
  HaveSpell(CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unholy Blight)
  !Difficulty(EASIEST)
  Alignment(Myself,MASK_EVIL)
  Alignment(SecondNearestEnemyOf(Myself),MASK_GOOD)
  Range(SecondNearestEnemyOf(Myself),15)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_NECROMANCY)
  CheckStatLT(SecondNearestEnemyOf(Myself),40,RESISTMAGIC)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_UnholyBlightTimer","LOCALS")
  HaveSpell(CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unholy Blight)
  !Difficulty(EASIEST)
  Alignment(Myself,MASK_EVIL)
  Alignment(NearestEnemyOf(Myself),MASK_GOOD)
  Range(NearestEnemyOf(Myself),15)
  !CheckSpellState(NearestEnemyOf(Myself),SI_NECROMANCY)
  CheckStatLT(NearestEnemyOf(Myself),40,RESISTMAGIC)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_UnholyBlightTimer","LOCALS")
  HaveSpell(CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unholy Blight)
  !Difficulty(EASIEST)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Alignment(Myself,MASK_EVIL)
  Alignment(LastSeenBy(Myself),MASK_GOOD)
  Range(LastSeenBy(Myself),15)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  CheckStatLT(LastSeenBy(Myself),40,RESISTMAGIC)
  CheckStatLT(Myself,40,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  OR(2)
    CheckStatLT(Myself,1,SANCTUARY)
    HPPercentGT(Myself,80)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_UnholyBlightTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(Myself,CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unholy Blight)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Doom
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_DoomTimer","LOCALS")
  HaveSpell(CLERIC_DOOM)  // SPPR113.SPL (Doom)
  !CheckSpellState(SixthNearestEnemyOf(Myself),DOOM)
  !Gender(SixthNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_DoomTimer","LOCALS")
  HaveSpell(CLERIC_DOOM)  // SPPR113.SPL (Doom)
  !CheckSpellState(FifthNearestEnemyOf(Myself),DOOM)
  !Gender(FifthNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_DoomTimer","LOCALS")
  HaveSpell(CLERIC_DOOM)  // SPPR113.SPL (Doom)
  !CheckSpellState(FourthNearestEnemyOf(Myself),DOOM)
  !Gender(FourthNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_DoomTimer","LOCALS")
  HaveSpell(CLERIC_DOOM)  // SPPR113.SPL (Doom)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),DOOM)
  !Gender(ThirdNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_DoomTimer","LOCALS")
  HaveSpell(CLERIC_DOOM)  // SPPR113.SPL (Doom)
  !CheckSpellState(SecondNearestEnemyOf(Myself),DOOM)
  !Gender(SecondNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_DoomTimer","LOCALS")
  HaveSpell(CLERIC_DOOM)  // SPPR113.SPL (Doom)
  !CheckSpellState(NearestEnemyOf(Myself),DOOM)
  !Gender(NearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(NearestEnemyOf(Myself),SI_ENCHANTMENT)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  CheckStatLT(NearestEnemyOf(Myself),50,RESISTMAGIC)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_DoomTimer","LOCALS")
  HaveSpell(CLERIC_DOOM)  // SPPR113.SPL (Doom)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !CheckSpellState(LastSeenBy(Myself),DOOM)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_ENCHANTMENT)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  CheckStatLT(Myself,40,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  OR(2)
    CheckStatLT(Myself,1,SANCTUARY)
    HPPercentGT(Myself,80)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_DoomTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),CLERIC_DOOM)  // SPPR113.SPL (Doom)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Finger of Death
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_FingerDeathTimer","LOCALS")
  HaveSpell(CLERIC_FINGER_OF_DEATH)  // SPPR708.SPL (Finger of Death)
  !HasItemEquiped("clck26",SixthNearestEnemyOf(Myself))  // Cloak of Mirroring
  HPGT(SixthNearestEnemyOf(Myself),20)
  !CheckStat(SixthNearestEnemyOf(Myself),1,DEATH_WARD)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_NECROMANCY)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(SixthNearestEnemyOf(Myself),40,RESISTMAGIC)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_FingerDeathTimer","LOCALS")
  HaveSpell(CLERIC_FINGER_OF_DEATH)  // SPPR708.SPL (Finger of Death)
  !HasItemEquiped("clck26",FifthNearestEnemyOf(Myself))  // Cloak of Mirroring
  HPGT(FifthNearestEnemyOf(Myself),20)
  !CheckStat(FifthNearestEnemyOf(Myself),1,DEATH_WARD)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_NECROMANCY)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(FifthNearestEnemyOf(Myself),40,RESISTMAGIC)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_FingerDeathTimer","LOCALS")
  HaveSpell(CLERIC_FINGER_OF_DEATH)  // SPPR708.SPL (Finger of Death)
  !HasItemEquiped("clck26",FourthNearestEnemyOf(Myself))  // Cloak of Mirroring
  HPGT(FourthNearestEnemyOf(Myself),20)
  !CheckStat(FourthNearestEnemyOf(Myself),1,DEATH_WARD)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_NECROMANCY)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(FourthNearestEnemyOf(Myself),40,RESISTMAGIC)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_FingerDeathTimer","LOCALS")
  HaveSpell(CLERIC_FINGER_OF_DEATH)  // SPPR708.SPL (Finger of Death)
  !HasItemEquiped("clck26",ThirdNearestEnemyOf(Myself))  // Cloak of Mirroring
  HPGT(ThirdNearestEnemyOf(Myself),20)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,DEATH_WARD)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_NECROMANCY)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(ThirdNearestEnemyOf(Myself),40,RESISTMAGIC)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_FingerDeathTimer","LOCALS")
  HaveSpell(CLERIC_FINGER_OF_DEATH)  // SPPR708.SPL (Finger of Death)
  !HasItemEquiped("clck26",SecondNearestEnemyOf(Myself))  // Cloak of Mirroring
  HPGT(SecondNearestEnemyOf(Myself),20)
  !CheckStat(SecondNearestEnemyOf(Myself),1,DEATH_WARD)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_NECROMANCY)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(SecondNearestEnemyOf(Myself),40,RESISTMAGIC)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_FingerDeathTimer","LOCALS")
  HaveSpell(CLERIC_FINGER_OF_DEATH)  // SPPR708.SPL (Finger of Death)
  !HasItemEquiped("clck26",NearestEnemyOf(Myself))  // Cloak of Mirroring
  HPGT(NearestEnemyOf(Myself),20)
  !CheckStat(NearestEnemyOf(Myself),1,DEATH_WARD)
  !CheckSpellState(NearestEnemyOf(Myself),SI_NECROMANCY)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(NearestEnemyOf(Myself),40,RESISTMAGIC)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_FingerDeathTimer","LOCALS")
  HaveSpell(CLERIC_FINGER_OF_DEATH)  // SPPR708.SPL (Finger of Death)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !HasItemEquiped("clck26",LastSeenBy(Myself))  // Cloak of Mirroring
  HPGT(LastSeenBy(Myself),20)
  !CheckStat(LastSeenBy(Myself),1,DEATH_WARD)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),40,RESISTMAGIC)
  CheckStatLT(Myself,40,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  OR(2)
    CheckStatLT(Myself,1,SANCTUARY)
    HPPercentGT(Myself,80)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_FingerDeathTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),CLERIC_FINGER_OF_DEATH)  // SPPR708.SPL (Finger of Death)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Slay Living
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SlayLivingTimer","LOCALS")
  HaveSpell(CLERIC_SLAY_LIVING)  // SPPR511.SPL (Slay Living)
  Range(SixthNearestEnemyOf(Myself),4)
  !HasItemEquiped("clck26",SixthNearestEnemyOf(Myself))  // Cloak of Mirroring
  !CheckStat(SixthNearestEnemyOf(Myself),1,DEATH_WARD)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_NECROMANCY)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(SixthNearestEnemyOf(Myself),40,RESISTMAGIC)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SlayLivingTimer","LOCALS")
  HaveSpell(CLERIC_SLAY_LIVING)  // SPPR511.SPL (Slay Living)
  Range(FifthNearestEnemyOf(Myself),4)
  !HasItemEquiped("clck26",FifthNearestEnemyOf(Myself))  // Cloak of Mirroring
  !CheckStat(FifthNearestEnemyOf(Myself),1,DEATH_WARD)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_NECROMANCY)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(FifthNearestEnemyOf(Myself),40,RESISTMAGIC)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SlayLivingTimer","LOCALS")
  HaveSpell(CLERIC_SLAY_LIVING)  // SPPR511.SPL (Slay Living)
  Range(FourthNearestEnemyOf(Myself),4)
  !HasItemEquiped("clck26",FourthNearestEnemyOf(Myself))  // Cloak of Mirroring
  !CheckStat(FourthNearestEnemyOf(Myself),1,DEATH_WARD)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_NECROMANCY)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(FourthNearestEnemyOf(Myself),40,RESISTMAGIC)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SlayLivingTimer","LOCALS")
  HaveSpell(CLERIC_SLAY_LIVING)  // SPPR511.SPL (Slay Living)
  Range(ThirdNearestEnemyOf(Myself),4)
  !HasItemEquiped("clck26",ThirdNearestEnemyOf(Myself))  // Cloak of Mirroring
  !CheckStat(ThirdNearestEnemyOf(Myself),1,DEATH_WARD)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_NECROMANCY)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(ThirdNearestEnemyOf(Myself),40,RESISTMAGIC)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SlayLivingTimer","LOCALS")
  HaveSpell(CLERIC_SLAY_LIVING)  // SPPR511.SPL (Slay Living)
  Range(SecondNearestEnemyOf(Myself),4)
  !HasItemEquiped("clck26",SecondNearestEnemyOf(Myself))  // Cloak of Mirroring
  !CheckStat(SecondNearestEnemyOf(Myself),1,DEATH_WARD)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_NECROMANCY)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(SecondNearestEnemyOf(Myself),40,RESISTMAGIC)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SlayLivingTimer","LOCALS")
  HaveSpell(CLERIC_SLAY_LIVING)  // SPPR511.SPL (Slay Living)
  Range(NearestEnemyOf(Myself),4)
  !HasItemEquiped("clck26",NearestEnemyOf(Myself))  // Cloak of Mirroring
  !CheckStat(NearestEnemyOf(Myself),1,DEATH_WARD)
  !CheckSpellState(NearestEnemyOf(Myself),SI_NECROMANCY)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(NearestEnemyOf(Myself),40,RESISTMAGIC)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SlayLivingTimer","LOCALS")
  HaveSpell(CLERIC_SLAY_LIVING)  // SPPR511.SPL (Slay Living)
  !HasItem("SLAYLIVE",Myself)  // Slay Living
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),4)
  !HasItemEquiped("clck26",LastSeenBy(Myself))  // Cloak of Mirroring
  !CheckStat(LastSeenBy(Myself),1,DEATH_WARD)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),40,RESISTMAGIC)
  CheckStatLT(Myself,40,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  OR(2)
    CheckStatLT(Myself,1,SANCTUARY)
    HPPercentGT(Myself,80)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_SlayLivingTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(Myself,CLERIC_SLAY_LIVING)  // SPPR511.SPL (Slay Living)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Dolorous Decay
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(CLERIC_DOLOROUS_DECAY)  // SPPR610.SPL (Dolorous Decay)
  !General(SixthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),UNDEAD)
  !General(SixthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),PLANT)
  !Race(SixthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),DEMONIC)
  !Race(SixthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),TROLL)
  !Race(SixthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),SLIME)
  CheckStatLT(SixthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),50,RESISTPOISON)
  !HasItem("AMUL22",SixthNearestEnemyOfType([GOODCUTOFF.HUMANOID]))  // ~Periapt of Proof Against Poison~
  !HasItem("RING46",SixthNearestEnemyOfType([GOODCUTOFF.HUMANOID]))  // ~Ring of Anti-Venom~
  CheckStatGT(SixthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),-2,SAVEVSDEATH)
  !StateCheck(SixthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),STATE_POISONED)
  !StateCheck(SixthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),STATE_NOT_TARGETABLE)
  !CheckSpellState(SixthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),SI_TRANSMUTATION)
  !StateCheck(SixthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(SixthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(SixthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),50,MAGICDAMAGERESISTANCE)
  !HasItem("MORSWORD",SixthNearestEnemyOfType([GOODCUTOFF.HUMANOID]))  // Mordenkainen's Sword
  See(SixthNearestEnemyOfType([GOODCUTOFF.HUMANOID]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(CLERIC_DOLOROUS_DECAY)  // SPPR610.SPL (Dolorous Decay)
  !General(FifthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),UNDEAD)
  !General(FifthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),PLANT)
  !Race(FifthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),DEMONIC)
  !Race(FifthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),TROLL)
  !Race(FifthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),SLIME)
  CheckStatLT(FifthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),50,RESISTPOISON)
  !HasItem("AMUL22",FifthNearestEnemyOfType([GOODCUTOFF.HUMANOID]))  // ~Periapt of Proof Against Poison~
  !HasItem("RING46",FifthNearestEnemyOfType([GOODCUTOFF.HUMANOID]))  // ~Ring of Anti-Venom~
  CheckStatGT(FifthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),-2,SAVEVSDEATH)
  !StateCheck(FifthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),STATE_POISONED)
  !StateCheck(FifthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),STATE_NOT_TARGETABLE)
  !CheckSpellState(FifthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),SI_TRANSMUTATION)
  !StateCheck(FifthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(FifthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(FifthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),50,MAGICDAMAGERESISTANCE)
  !HasItem("MORSWORD",FifthNearestEnemyOfType([GOODCUTOFF.HUMANOID]))  // Mordenkainen's Sword
  See(FifthNearestEnemyOfType([GOODCUTOFF.HUMANOID]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(CLERIC_DOLOROUS_DECAY)  // SPPR610.SPL (Dolorous Decay)
  !General(FourthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),UNDEAD)
  !General(FourthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),PLANT)
  !Race(FourthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),DEMONIC)
  !Race(FourthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),TROLL)
  !Race(FourthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),SLIME)
  CheckStatLT(FourthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),50,RESISTPOISON)
  !HasItem("AMUL22",FourthNearestEnemyOfType([GOODCUTOFF.HUMANOID]))  // ~Periapt of Proof Against Poison~
  !HasItem("RING46",FourthNearestEnemyOfType([GOODCUTOFF.HUMANOID]))  // ~Ring of Anti-Venom~
  CheckStatGT(FourthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),-2,SAVEVSDEATH)
  !StateCheck(FourthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),STATE_POISONED)
  !StateCheck(FourthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),STATE_NOT_TARGETABLE)
  !CheckSpellState(FourthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),SI_TRANSMUTATION)
  !StateCheck(FourthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(FourthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(FourthNearestEnemyOfType([GOODCUTOFF.HUMANOID]),50,MAGICDAMAGERESISTANCE)
  !HasItem("MORSWORD",FourthNearestEnemyOfType([GOODCUTOFF.HUMANOID]))  // Mordenkainen's Sword
  See(FourthNearestEnemyOfType([GOODCUTOFF.HUMANOID]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(CLERIC_DOLOROUS_DECAY)  // SPPR610.SPL (Dolorous Decay)
  !General(ThirdNearestEnemyOfType([GOODCUTOFF.HUMANOID]),UNDEAD)
  !General(ThirdNearestEnemyOfType([GOODCUTOFF.HUMANOID]),PLANT)
  !Race(ThirdNearestEnemyOfType([GOODCUTOFF.HUMANOID]),DEMONIC)
  !Race(ThirdNearestEnemyOfType([GOODCUTOFF.HUMANOID]),TROLL)
  !Race(ThirdNearestEnemyOfType([GOODCUTOFF.HUMANOID]),SLIME)
  CheckStatLT(ThirdNearestEnemyOfType([GOODCUTOFF.HUMANOID]),50,RESISTPOISON)
  !HasItem("AMUL22",ThirdNearestEnemyOfType([GOODCUTOFF.HUMANOID]))  // ~Periapt of Proof Against Poison~
  !HasItem("RING46",ThirdNearestEnemyOfType([GOODCUTOFF.HUMANOID]))  // ~Ring of Anti-Venom~
  CheckStatGT(ThirdNearestEnemyOfType([GOODCUTOFF.HUMANOID]),-2,SAVEVSDEATH)
  !StateCheck(ThirdNearestEnemyOfType([GOODCUTOFF.HUMANOID]),STATE_POISONED)
  !StateCheck(ThirdNearestEnemyOfType([GOODCUTOFF.HUMANOID]),STATE_NOT_TARGETABLE)
  !CheckSpellState(ThirdNearestEnemyOfType([GOODCUTOFF.HUMANOID]),SI_TRANSMUTATION)
  !StateCheck(ThirdNearestEnemyOfType([GOODCUTOFF.HUMANOID]),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(ThirdNearestEnemyOfType([GOODCUTOFF.HUMANOID]),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOfType([GOODCUTOFF.HUMANOID]),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOfType([GOODCUTOFF.HUMANOID]),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOfType([GOODCUTOFF.HUMANOID]),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(ThirdNearestEnemyOfType([GOODCUTOFF.HUMANOID]),50,MAGICDAMAGERESISTANCE)
  !HasItem("MORSWORD",ThirdNearestEnemyOfType([GOODCUTOFF.HUMANOID]))  // Mordenkainen's Sword
  See(ThirdNearestEnemyOfType([GOODCUTOFF.HUMANOID]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(CLERIC_DOLOROUS_DECAY)  // SPPR610.SPL (Dolorous Decay)
  !General(SecondNearestEnemyOfType([GOODCUTOFF.HUMANOID]),UNDEAD)
  !General(SecondNearestEnemyOfType([GOODCUTOFF.HUMANOID]),PLANT)
  !Race(SecondNearestEnemyOfType([GOODCUTOFF.HUMANOID]),DEMONIC)
  !Race(SecondNearestEnemyOfType([GOODCUTOFF.HUMANOID]),TROLL)
  !Race(SecondNearestEnemyOfType([GOODCUTOFF.HUMANOID]),SLIME)
  CheckStatLT(SecondNearestEnemyOfType([GOODCUTOFF.HUMANOID]),50,RESISTPOISON)
  !HasItem("AMUL22",SecondNearestEnemyOfType([GOODCUTOFF.HUMANOID]))  // ~Periapt of Proof Against Poison~
  !HasItem("RING46",SecondNearestEnemyOfType([GOODCUTOFF.HUMANOID]))  // ~Ring of Anti-Venom~
  CheckStatGT(SecondNearestEnemyOfType([GOODCUTOFF.HUMANOID]),-2,SAVEVSDEATH)
  !StateCheck(SecondNearestEnemyOfType([GOODCUTOFF.HUMANOID]),STATE_POISONED)
  !StateCheck(SecondNearestEnemyOfType([GOODCUTOFF.HUMANOID]),STATE_NOT_TARGETABLE)
  !CheckSpellState(SecondNearestEnemyOfType([GOODCUTOFF.HUMANOID]),SI_TRANSMUTATION)
  !StateCheck(SecondNearestEnemyOfType([GOODCUTOFF.HUMANOID]),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(SecondNearestEnemyOfType([GOODCUTOFF.HUMANOID]),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOfType([GOODCUTOFF.HUMANOID]),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOfType([GOODCUTOFF.HUMANOID]),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOfType([GOODCUTOFF.HUMANOID]),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(SecondNearestEnemyOfType([GOODCUTOFF.HUMANOID]),50,MAGICDAMAGERESISTANCE)
  !HasItem("MORSWORD",SecondNearestEnemyOfType([GOODCUTOFF.HUMANOID]))  // Mordenkainen's Sword
  See(SecondNearestEnemyOfType([GOODCUTOFF.HUMANOID]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(CLERIC_DOLOROUS_DECAY)  // SPPR610.SPL (Dolorous Decay)
  !General([GOODCUTOFF.HUMANOID],UNDEAD)
  !General([GOODCUTOFF.HUMANOID],PLANT)
  !Race([GOODCUTOFF.HUMANOID],DEMONIC)
  !Race([GOODCUTOFF.HUMANOID],TROLL)
  !Race([GOODCUTOFF.HUMANOID],SLIME)
  CheckStatLT([GOODCUTOFF.HUMANOID],50,RESISTPOISON)
  !HasItem("AMUL22",[GOODCUTOFF.HUMANOID])  // ~Periapt of Proof Against Poison~
  !HasItem("RING46",[GOODCUTOFF.HUMANOID])  // ~Ring of Anti-Venom~
  CheckStatGT([GOODCUTOFF.HUMANOID],-2,SAVEVSDEATH)
  !StateCheck([GOODCUTOFF.HUMANOID],STATE_POISONED)
  !StateCheck([GOODCUTOFF.HUMANOID],STATE_NOT_TARGETABLE)
  !CheckSpellState([GOODCUTOFF.HUMANOID],SI_TRANSMUTATION)
  !StateCheck([GOODCUTOFF.HUMANOID],STATE_IMPROVEDINVISIBILITY)
  CheckStatLT([GOODCUTOFF.HUMANOID],1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT([GOODCUTOFF.HUMANOID],1,WIZARD_SPELL_TURNING)
  !CheckStat([GOODCUTOFF.HUMANOID],1,WIZARD_SPELL_TRAP)
  !CheckStat([GOODCUTOFF.HUMANOID],1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT([GOODCUTOFF.HUMANOID],50,MAGICDAMAGERESISTANCE)
  !HasItem("MORSWORD",[GOODCUTOFF.HUMANOID])  // Mordenkainen's Sword
  See([GOODCUTOFF.HUMANOID])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(CLERIC_DOLOROUS_DECAY)  // SPPR610.SPL (Dolorous Decay)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !General(LastSeenBy(Myself),UNDEAD)
  !General(LastSeenBy(Myself),PLANT)
  !Race(LastSeenBy(Myself),DEMONIC)
  !Race(LastSeenBy(Myself),TROLL)
  !Race(LastSeenBy(Myself),SLIME)
  CheckStatLT(LastSeenBy(Myself),50,RESISTPOISON)
  !HasItem("AMUL22",LastSeenBy(Myself))  // ~Periapt of Proof Against Poison~
  !HasItem("RING46",LastSeenBy(Myself))  // ~Ring of Anti-Venom~
  CheckStatGT(LastSeenBy(Myself),-2,SAVEVSDEATH)
  !StateCheck(LastSeenBy(Myself),STATE_POISONED)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckSpellState(LastSeenBy(Myself),SI_TRANSMUTATION)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),50,MAGICDAMAGERESISTANCE)
  !HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
  CheckStatLT(Myself,40,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  OR(2)
    CheckStatLT(Myself,1,SANCTUARY)
    HPPercentGT(Myself,80)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),CLERIC_DOLOROUS_DECAY)  // SPPR610.SPL (Dolorous Decay)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Hold Person
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_HoldTimer","LOCALS")
  HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  !Kit(SixthNearestEnemyOf(Myself),INQUISITOR)
  !Kit(SixthNearestEnemyOf(Myself),UNDEADHUNTER)
  !HasItem("MORSWORD",SixthNearestEnemyOf(Myself))  // Mordenkainen's Sword
  !HasItemEquiped("RING09",SixthNearestEnemyOf(Myself))  // Edventar's Gift
  !HasItemEquipedReal("SW2H06",SixthNearestEnemyOf(Myself))  // Spider's Bane +2
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !Gender(SixthNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(SixthNearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(SixthNearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(SixthNearestEnemyOf(Myself),MINSC_BERSERK)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_HARMLESS)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,CLERIC_FREE_ACTION)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  !CheckStatGT(SixthNearestEnemyOf(Myself),25,RESISTMAGIC)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_HoldTimer","LOCALS")
  HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  !Kit(FifthNearestEnemyOf(Myself),INQUISITOR)
  !Kit(FifthNearestEnemyOf(Myself),UNDEADHUNTER)
  !HasItem("MORSWORD",FifthNearestEnemyOf(Myself))  // Mordenkainen's Sword
  !HasItemEquiped("RING09",FifthNearestEnemyOf(Myself))  // Edventar's Gift
  !HasItemEquipedReal("SW2H06",FifthNearestEnemyOf(Myself))  // Spider's Bane +2
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !Gender(FifthNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(FifthNearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(FifthNearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(FifthNearestEnemyOf(Myself),MINSC_BERSERK)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_HARMLESS)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,CLERIC_FREE_ACTION)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  !CheckStatGT(FifthNearestEnemyOf(Myself),25,RESISTMAGIC)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_HoldTimer","LOCALS")
  HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  !Kit(FourthNearestEnemyOf(Myself),INQUISITOR)
  !Kit(FourthNearestEnemyOf(Myself),UNDEADHUNTER)
  !HasItem("MORSWORD",FourthNearestEnemyOf(Myself))  // Mordenkainen's Sword
  !HasItemEquiped("RING09",FourthNearestEnemyOf(Myself))  // Edventar's Gift
  !HasItemEquipedReal("SW2H06",FourthNearestEnemyOf(Myself))  // Spider's Bane +2
  !CheckSpellState(NearestEnemyOf(Myself),SI_ENCHANTMENT)
  !Gender(FourthNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(FourthNearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(FourthNearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(FourthNearestEnemyOf(Myself),MINSC_BERSERK)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_HARMLESS)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,CLERIC_FREE_ACTION)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  !CheckStatGT(FourthNearestEnemyOf(Myself),25,RESISTMAGIC)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_HoldTimer","LOCALS")
  HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  !Kit(ThirdNearestEnemyOf(Myself),INQUISITOR)
  !Kit(ThirdNearestEnemyOf(Myself),UNDEADHUNTER)
  !HasItem("MORSWORD",ThirdNearestEnemyOf(Myself))  // Mordenkainen's Sword
  !HasItemEquiped("RING09",ThirdNearestEnemyOf(Myself))  // Edventar's Gift
  !HasItemEquipedReal("SW2H06",ThirdNearestEnemyOf(Myself))  // Spider's Bane +2
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !Gender(ThirdNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),MINSC_BERSERK)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_HARMLESS)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,CLERIC_FREE_ACTION)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),25,RESISTMAGIC)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_HoldTimer","LOCALS")
  HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  !Kit(SecondNearestEnemyOf(Myself),INQUISITOR)
  !Kit(SecondNearestEnemyOf(Myself),UNDEADHUNTER)
  !HasItem("MORSWORD",SecondNearestEnemyOf(Myself))  // Mordenkainen's Sword
  !HasItemEquiped("RING09",SecondNearestEnemyOf(Myself))  // Edventar's Gift
  !HasItemEquipedReal("SW2H06",SecondNearestEnemyOf(Myself))  // Spider's Bane +2
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !Gender(SecondNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(SecondNearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(SecondNearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(SecondNearestEnemyOf(Myself),MINSC_BERSERK)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_HARMLESS)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,CLERIC_FREE_ACTION)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  !CheckStatGT(SecondNearestEnemyOf(Myself),25,RESISTMAGIC)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_HoldTimer","LOCALS")
  HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  !Kit(NearestEnemyOf(Myself),INQUISITOR)
  !Kit(NearestEnemyOf(Myself),UNDEADHUNTER)
  !HasItem("MORSWORD",NearestEnemyOf(Myself))  // Mordenkainen's Sword
  !HasItemEquiped("RING09",NearestEnemyOf(Myself))  // Edventar's Gift
  !HasItemEquipedReal("SW2H06",NearestEnemyOf(Myself))  // Spider's Bane +2
  !CheckSpellState(NearestEnemyOf(Myself),SI_ENCHANTMENT)
  !Gender(NearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(NearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(NearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(NearestEnemyOf(Myself),MINSC_BERSERK)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(NearestEnemyOf(Myself),STATE_HARMLESS)
  !CheckStatGT(NearestEnemyOf(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckStatGT(NearestEnemyOf(Myself),0,CLERIC_FREE_ACTION)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  !CheckStatGT(NearestEnemyOf(Myself),25,RESISTMAGIC)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_HoldTimer","LOCALS")
  HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !Kit(LastSeenBy(Myself),INQUISITOR)
  !Kit(LastSeenBy(Myself),UNDEADHUNTER)
  !HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
  !HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
  !HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2
  !CheckSpellState(LastSeenBy(Myself),SI_ENCHANTMENT)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),MINSC_BERSERK)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,40,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  OR(2)
    CheckStatLT(Myself,1,SANCTUARY)
    HPPercentGT(Myself,80)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_HoldTimer","LOCALS",12)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_CONJURE_EARTH_ELEMENTAL)  // SPPR702.SPL (Conjure Earth Elemental)
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_CONJURE_EARTH_ELEMENTAL)  // SPPR702.SPL (Conjure Earth Elemental)
END

/////////////////////////////////////////////////////////////////////
// Attack
/////////////////////////////////////////////////////////////////////
IF
  OR(6)
    See(Player1)
    See(Player2)
    See(Player3)
    See(Player4)
    See(Player5)
    See(Player6)
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  CheckStatLT(NearestEnemyOf(Myself),1,SANCTUARY)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,SANCTUARY)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,SANCTUARY)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,SANCTUARY)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,SANCTUARY)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,SANCTUARY)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(NearestEnemyOf(Myself),1,SANCTUARY)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,SANCTUARY)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,SANCTUARY)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,SANCTUARY)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,SANCTUARY)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,SANCTUARY)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(NearestEnemyOf(Myself),1,SANCTUARY)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,SANCTUARY)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,SANCTUARY)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,SANCTUARY)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,SANCTUARY)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,SANCTUARY)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
  !StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(NearestEnemyOf(Myself),1,SANCTUARY)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

// EEex - Is Moving Check 1

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,SANCTUARY)
  Range(SixthNearestEnemyOf(Myself),5)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,SANCTUARY)
  Range(FifthNearestEnemyOf(Myself),5)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,SANCTUARY)
  Range(FourthNearestEnemyOf(Myself),5)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,SANCTUARY)
  Range(ThirdNearestEnemyOf(Myself),5)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,SANCTUARY)
  Range(SecondNearestEnemyOf(Myself),5)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
  !StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(NearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(NearestEnemyOf(Myself),1,SANCTUARY)
  Range(NearestEnemyOf(Myself),5)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

// EEex - Is Moving Check 2

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  StateCheck(SixthNearestEnemyOf(Myself),STATE_IMMOBILE)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,SANCTUARY)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
  StateCheck(FifthNearestEnemyOf(Myself),STATE_IMMOBILE)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,SANCTUARY)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
  StateCheck(FourthNearestEnemyOf(Myself),STATE_IMMOBILE)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,SANCTUARY)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
  StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMMOBILE)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,SANCTUARY)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
  StateCheck(SecondNearestEnemyOf(Myself),STATE_IMMOBILE)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,SANCTUARY)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
  StateCheck(NearestEnemyOf(Myself),STATE_IMMOBILE)
  CheckStatLT(NearestEnemyOf(Myself),1,SANCTUARY)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

// EEex - Target Caster (Melee)

IF
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  WeaponEffectiveVs(LastSeenBy(Myself),MAINHAND)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  OR(2)
    CheckStatLT(Myself,1,SANCTUARY)
    HPPercentGT(Myself,49)
THEN
  RESPONSE #100
    SetGlobal("MO_AttackedSomeone","LOCALS",1)
    AttackReevaluate(LastSeenBy(Myself),30)
END

IF
  !Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  Allegiance(LastSeenBy(Myself),ENEMY)
  WeaponEffectiveVs(LastSeenBy(Myself),MAINHAND)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  OR(2)
    CheckStatLT(Myself,1,SANCTUARY)
    HPPercentGT(Myself,49)
THEN
  RESPONSE #100
    SetGlobal("MO_AttackedSomeone","LOCALS",1)
    AttackReevaluate(LastSeenBy(Myself),30)
END



