IF
    NumberOfTimesTalkedTo(0)
    See([PC])
THEN
    RESPONSE #100
        Wait(1)
        StartDialogueNoSet([PC])
END

IF
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
    HaveSpell(ASSASSIN_POISON)  // SPCL423.SPL (Poison Weapon)
    !Difficulty(EASIEST)
    !CheckStat(Myself,4,SCRIPTINGSTATE4)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Myself,ASSASSIN_POISON)  // SPCL423.SPL (Poison Weapon)
END

