/////////////////////////////////////////////////////////////////////
// Rakshasa Cloud
/////////////////////////////////////////////////////////////////////
IF
    See(NearestEnemyOf(Myself))
    Global("RakCloud","GLOBAL",0)
THEN
    RESPONSE #30
        ForceSpell(NearestEnemyOf(Myself),WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
        SetGlobal("RakCloud","GLOBAL",1)
    RESPONSE #30
        ForceSpell(NearestEnemyOf(Myself),WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
        SetGlobal("RakCloud","GLOBAL",1)
    RESPONSE #40
        Continue()
END

/////////////////////////////////////////////////////////////////////
// Lightning Bolt 
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_LightningBoltTimer","LOCALS")
  Global("RakshasaBolt","LOCALS",0)
  !HasItemEquiped("CLCK24",SixthNearestEnemyOf(Myself)) // Cloak of reflection
  !HasItemEquiped("CLCK26",SixthNearestEnemyOf(Myself)) // Cloak of Mirroring
  CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTELECTRICITY)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_LightningBoltTimer","LOCALS")
  Global("RakshasaBolt","LOCALS",0)
  !HasItemEquiped("CLCK24",FifthNearestEnemyOf(Myself)) // Cloak of reflection
  !HasItemEquiped("CLCK26",FifthNearestEnemyOf(Myself)) // Cloak of Mirroring
  CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTELECTRICITY)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_LightningBoltTimer","LOCALS")
  Global("RakshasaBolt","LOCALS",0)
  !HasItemEquiped("CLCK24",FourthNearestEnemyOf(Myself)) // Cloak of reflection
  !HasItemEquiped("CLCK26",FourthNearestEnemyOf(Myself)) // Cloak of Mirroring
  CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTELECTRICITY)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_LightningBoltTimer","LOCALS")
  Global("RakshasaBolt","LOCALS",0)
  !HasItemEquiped("CLCK24",ThirdNearestEnemyOf(Myself)) // Cloak of reflection
  !HasItemEquiped("CLCK26",ThirdNearestEnemyOf(Myself)) // Cloak of Mirroring
  CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTELECTRICITY)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_LightningBoltTimer","LOCALS")
  Global("RakshasaBolt","LOCALS",0)
  !HasItemEquiped("CLCK24",SecondNearestEnemyOf(Myself)) // Cloak of reflection
  !HasItemEquiped("CLCK26",SecondNearestEnemyOf(Myself)) // Cloak of Mirroring
  CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTELECTRICITY)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_LightningBoltTimer","LOCALS")
  Global("RakshasaBolt","LOCALS",0)
  !HasItemEquiped("CLCK24",NearestEnemyOf(Myself)) // Cloak of reflection
  !HasItemEquiped("CLCK26",NearestEnemyOf(Myself)) // Cloak of Mirroring
  CheckStatLT(NearestEnemyOf(Myself),50,RESISTELECTRICITY)
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_LightningBoltTimer","LOCALS")
  Global("RakshasaBolt","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !HasItemEquiped("CLCK24",LastSeenBy(Myself)) // Cloak of reflection
  !HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
  CheckStatLT(LastSeenBy(Myself),50,RESISTELECTRICITY)
  !CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobal("RakshasaBolt","LOCALS",1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_LightningBoltTimer","LOCALS",12)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Fireball
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("RakshasaBall","LOCALS",0)
  !Range(ThirdFarthestEnemyOf(Myself),12)
  !CheckSpellState(ThirdFarthestEnemyOf(Myself),SI_EVOCATION)
  CheckStat(ThirdFarthestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(ThirdFarthestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(ThirdFarthestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(ThirdFarthestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(ThirdFarthestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdFarthestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdFarthestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdFarthestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(ThirdFarthestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(ThirdFarthestEnemyOf(Myself),50,RESISTFIRE)
  See(ThirdFarthestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("RakshasaBall","LOCALS",0)
  !Range(SecondFarthestEnemyOf(Myself),12)
  !CheckSpellState(SecondFarthestEnemyOf(Myself),SI_EVOCATION)
  CheckStat(SecondFarthestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(SecondFarthestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(SecondFarthestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(SecondFarthestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SecondFarthestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondFarthestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondFarthestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondFarthestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(SecondFarthestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SecondFarthestEnemyOf(Myself),50,RESISTFIRE)
  See(SecondFarthestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("RakshasaBall","LOCALS",0)
  !Range(FarthestEnemyOf(Myself),12)
  !CheckSpellState(FarthestEnemyOf(Myself),SI_EVOCATION)
  CheckStat(FarthestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(FarthestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(FarthestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(FarthestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FarthestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FarthestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FarthestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FarthestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(FarthestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FarthestEnemyOf(Myself),50,RESISTFIRE)
  See(FarthestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  LevelPartyLT(12)
  Global("RakshasaBall","LOCALS",0)
  See(LastSeenBy(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !Range(LastSeenBy(Myself),12)
  !CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobal("RakshasaBall","LOCALS",1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FIREBALL)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Flame Arrow 
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_FLAME_ARROW)
  !HasItemEquiped("CLCK26",SixthNearestEnemyOf(Myself)) // Cloak of Mirroring
  !HasItemEquiped("shld24",SixthNearestEnemyOf(Myself))
  !Gender(SixthNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(SixthNearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_MISSILES)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_CONJURATION)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SixthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  !CheckStatGT(SixthNearestEnemyOf(Myself),25,RESISTMAGIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),80,RESISTFIRE)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_FLAME_ARROW)
  !HasItemEquiped("CLCK26",FifthNearestEnemyOf(Myself)) // Cloak of Mirroring
  !HasItemEquiped("shld24",FifthNearestEnemyOf(Myself))
  !Gender(FifthNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(FifthNearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_MISSILES)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_CONJURATION)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FifthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  !CheckStatGT(FifthNearestEnemyOf(Myself),25,RESISTMAGIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),80,RESISTFIRE)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_FLAME_ARROW)
  !HasItemEquiped("CLCK26",FourthNearestEnemyOf(Myself)) // Cloak of Mirroring
  !HasItemEquiped("shld24",FourthNearestEnemyOf(Myself))
  !Gender(FourthNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(FourthNearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_MISSILES)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_CONJURATION)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FourthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  !CheckStatGT(FourthNearestEnemyOf(Myself),25,RESISTMAGIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),80,RESISTFIRE)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_FLAME_ARROW)
  !HasItemEquiped("CLCK26",ThirdNearestEnemyOf(Myself)) // Cloak of Mirroring
  !HasItemEquiped("shld24",ThirdNearestEnemyOf(Myself))
  !Gender(ThirdNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_MISSILES)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_CONJURATION)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),25,RESISTMAGIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),80,RESISTFIRE)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_FLAME_ARROW)
  !HasItemEquiped("CLCK26",SecondNearestEnemyOf(Myself)) // Cloak of Mirroring
  !HasItemEquiped("shld24",SecondNearestEnemyOf(Myself))
  !Gender(SecondNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(SecondNearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_MISSILES)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_CONJURATION)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SecondNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  !CheckStatGT(SecondNearestEnemyOf(Myself),25,RESISTMAGIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),80,RESISTFIRE)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_FLAME_ARROW)
  !HasItemEquiped("CLCK26",NearestEnemyOf(Myself)) // Cloak of Mirroring
  !HasItemEquiped("shld24",NearestEnemyOf(Myself))
  !Gender(NearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(NearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_MISSILES)
  !CheckStatGT(NearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(NearestEnemyOf(Myself),SI_CONJURATION)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(NearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(NearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  !CheckStatGT(NearestEnemyOf(Myself),25,RESISTMAGIC)
  CheckStatLT(NearestEnemyOf(Myself),80,RESISTFIRE)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_FLAME_ARROW)
  !HasItemEquiped("CLCK26",SixthNearestEnemyOf(Myself)) // Cloak of Mirroring
  !HasItemEquiped("shld24",SixthNearestEnemyOf(Myself))
  !Gender(SixthNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(SixthNearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_MISSILES)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_CONJURATION)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SixthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  !CheckStatGT(SixthNearestEnemyOf(Myself),25,RESISTMAGIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),40,RESISTFIRE)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_FLAME_ARROW)
  !HasItemEquiped("CLCK26",FifthNearestEnemyOf(Myself)) // Cloak of Mirroring
  !HasItemEquiped("shld24",FifthNearestEnemyOf(Myself))
  !Gender(FifthNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(FifthNearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_MISSILES)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_CONJURATION)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FifthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  !CheckStatGT(FifthNearestEnemyOf(Myself),25,RESISTMAGIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),40,RESISTFIRE)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_FLAME_ARROW)
  !HasItemEquiped("CLCK26",FourthNearestEnemyOf(Myself)) // Cloak of Mirroring
  !HasItemEquiped("shld24",FourthNearestEnemyOf(Myself))
  !Gender(FourthNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(FourthNearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_MISSILES)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_CONJURATION)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FourthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  !CheckStatGT(FourthNearestEnemyOf(Myself),25,RESISTMAGIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),40,RESISTFIRE)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_FLAME_ARROW)
  !HasItemEquiped("CLCK26",ThirdNearestEnemyOf(Myself)) // Cloak of Mirroring
  !HasItemEquiped("shld24",ThirdNearestEnemyOf(Myself))
  !Gender(ThirdNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_MISSILES)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_CONJURATION)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),25,RESISTMAGIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),40,RESISTFIRE)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_FLAME_ARROW)
  !HasItemEquiped("CLCK26",SecondNearestEnemyOf(Myself)) // Cloak of Mirroring
  !HasItemEquiped("shld24",SecondNearestEnemyOf(Myself))
  !Gender(SecondNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(SecondNearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_MISSILES)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_CONJURATION)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SecondNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  !CheckStatGT(SecondNearestEnemyOf(Myself),25,RESISTMAGIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),40,RESISTFIRE)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_FLAME_ARROW)
  !HasItemEquiped("CLCK26",NearestEnemyOf(Myself)) // Cloak of Mirroring
  !HasItemEquiped("shld24",NearestEnemyOf(Myself))
  !Gender(NearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(NearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_MISSILES)
  !CheckStatGT(NearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(NearestEnemyOf(Myself),SI_CONJURATION)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(NearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(NearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  !CheckStatGT(NearestEnemyOf(Myself),25,RESISTMAGIC)
  CheckStatLT(NearestEnemyOf(Myself),40,RESISTFIRE)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_FLAME_ARROW)
  !HasItemEquiped("CLCK26",SixthNearestEnemyOf(Myself)) // Cloak of Mirroring
  !HasItemEquiped("shld24",SixthNearestEnemyOf(Myself))
  !Gender(SixthNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(SixthNearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_MISSILES)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_CONJURATION)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SixthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  !CheckStatGT(SixthNearestEnemyOf(Myself),25,RESISTMAGIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),10,RESISTFIRE)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_FLAME_ARROW)
  !HasItemEquiped("CLCK26",FifthNearestEnemyOf(Myself)) // Cloak of Mirroring
  !HasItemEquiped("shld24",FifthNearestEnemyOf(Myself))
  !Gender(FifthNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(FifthNearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_MISSILES)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_CONJURATION)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FifthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  !CheckStatGT(FifthNearestEnemyOf(Myself),25,RESISTMAGIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),10,RESISTFIRE)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_FLAME_ARROW)
  !HasItemEquiped("CLCK26",FourthNearestEnemyOf(Myself)) // Cloak of Mirroring
  !HasItemEquiped("shld24",FourthNearestEnemyOf(Myself))
  !Gender(FourthNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(FourthNearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_MISSILES)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_CONJURATION)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FourthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  !CheckStatGT(FourthNearestEnemyOf(Myself),25,RESISTMAGIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),10,RESISTFIRE)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_FLAME_ARROW)
  !HasItemEquiped("CLCK26",ThirdNearestEnemyOf(Myself)) // Cloak of Mirroring
  !HasItemEquiped("shld24",ThirdNearestEnemyOf(Myself))
  !Gender(ThirdNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_MISSILES)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_CONJURATION)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),25,RESISTMAGIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),10,RESISTFIRE)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_FLAME_ARROW)
  !HasItemEquiped("CLCK26",SecondNearestEnemyOf(Myself)) // Cloak of Mirroring
  !HasItemEquiped("shld24",SecondNearestEnemyOf(Myself))
  !Gender(SecondNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(SecondNearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_MISSILES)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_CONJURATION)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SecondNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  !CheckStatGT(SecondNearestEnemyOf(Myself),25,RESISTMAGIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),10,RESISTFIRE)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_FLAME_ARROW)
  !HasItemEquiped("CLCK26",NearestEnemyOf(Myself)) // Cloak of Mirroring
  !HasItemEquiped("shld24",NearestEnemyOf(Myself))
  !Gender(NearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(NearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_MISSILES)
  !CheckStatGT(NearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(NearestEnemyOf(Myself),SI_CONJURATION)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(NearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(NearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  !CheckStatGT(NearestEnemyOf(Myself),25,RESISTMAGIC)
  CheckStatLT(NearestEnemyOf(Myself),10,RESISTFIRE)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_FLAME_ARROW)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
  !HasItemEquiped("shld24",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(LastSeenBy(Myself),ENTROPY_SHIELD)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(LastSeenBy(Myself),80,RESISTFIRE)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Melf Acid Arrow 
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",SixthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SixthNearestEnemyOf(Myself))
  !Gender(SixthNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(SixthNearestEnemyOf(Myself),80,RESISTACID)
  CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SixthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",FifthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FifthNearestEnemyOf(Myself))
  !Gender(FifthNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(FifthNearestEnemyOf(Myself),80,RESISTACID)
  CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FifthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",FourthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FourthNearestEnemyOf(Myself))
  !Gender(FourthNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(FourthNearestEnemyOf(Myself),80,RESISTACID)
  CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FourthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",ThirdNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",ThirdNearestEnemyOf(Myself))
  !Gender(ThirdNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(ThirdNearestEnemyOf(Myself),80,RESISTACID)
  CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",SecondNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SecondNearestEnemyOf(Myself))
  !Gender(SecondNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(SecondNearestEnemyOf(Myself),80,RESISTACID)
  CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SecondNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",NearestEnemyOf(Myself))
  !HasItemEquiped("shld24",NearestEnemyOf(Myself))
  !Gender(NearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(NearestEnemyOf(Myself),80,RESISTACID)
  CheckStatLT(NearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(NearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(NearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(NearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",SixthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SixthNearestEnemyOf(Myself))
  !Gender(SixthNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(SixthNearestEnemyOf(Myself),40,RESISTACID)
  CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SixthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",FifthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FifthNearestEnemyOf(Myself))
  !Gender(FifthNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(FifthNearestEnemyOf(Myself),40,RESISTACID)
  CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FifthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",FourthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FourthNearestEnemyOf(Myself))
  !Gender(FourthNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(FourthNearestEnemyOf(Myself),40,RESISTACID)
  CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FourthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",ThirdNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",ThirdNearestEnemyOf(Myself))
  !Gender(ThirdNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(ThirdNearestEnemyOf(Myself),40,RESISTACID)
  CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",SecondNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SecondNearestEnemyOf(Myself))
  !Gender(SecondNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(SecondNearestEnemyOf(Myself),40,RESISTACID)
  CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SecondNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",NearestEnemyOf(Myself))
  !HasItemEquiped("shld24",NearestEnemyOf(Myself))
  !Gender(NearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(NearestEnemyOf(Myself),40,RESISTACID)
  CheckStatLT(NearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(NearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(NearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(NearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",SixthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SixthNearestEnemyOf(Myself))
  !Gender(SixthNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(SixthNearestEnemyOf(Myself),10,RESISTACID)
  CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SixthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",FifthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FifthNearestEnemyOf(Myself))
  !Gender(FifthNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(FifthNearestEnemyOf(Myself),10,RESISTACID)
  CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FifthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",FourthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FourthNearestEnemyOf(Myself))
  !Gender(FourthNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(FourthNearestEnemyOf(Myself),10,RESISTACID)
  CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FourthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",ThirdNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",ThirdNearestEnemyOf(Myself))
  !Gender(ThirdNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(ThirdNearestEnemyOf(Myself),10,RESISTACID)
  CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",SecondNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SecondNearestEnemyOf(Myself))
  !Gender(SecondNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(SecondNearestEnemyOf(Myself),10,RESISTACID)
  CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SecondNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",NearestEnemyOf(Myself))
  !HasItemEquiped("shld24",NearestEnemyOf(Myself))
  !Gender(NearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(NearestEnemyOf(Myself),10,RESISTACID)
  CheckStatLT(NearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(NearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(NearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(NearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !HasItem("clck26",LastSeenBy(Myself))
  !HasItemEquiped("shld24",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),80,RESISTACID)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(LastSeenBy(Myself),ENTROPY_SHIELD)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_AcidArrowTimer","LOCALS",30)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Orb 
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_CHROMATIC_ORB)
  !HasItemEquiped("CLCK26",SixthNearestEnemyOf(Myself)) // Cloak of Mirroring
  CheckStatGT(SixthNearestEnemyOf(Myself),6,SAVEVSSPELL)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_CHROMATIC_ORB)
  !HasItemEquiped("CLCK26",FifthNearestEnemyOf(Myself)) // Cloak of Mirroring
  CheckStatGT(FifthNearestEnemyOf(Myself),6,SAVEVSSPELL)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_CHROMATIC_ORB)
  !HasItemEquiped("CLCK26",FourthNearestEnemyOf(Myself)) // Cloak of Mirroring
  CheckStatGT(FourthNearestEnemyOf(Myself),6,SAVEVSSPELL)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_CHROMATIC_ORB)
  !HasItemEquiped("CLCK26",ThirdNearestEnemyOf(Myself)) // Cloak of Mirroring
  CheckStatGT(ThirdNearestEnemyOf(Myself),6,SAVEVSSPELL)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_CHROMATIC_ORB)
  !HasItemEquiped("CLCK26",SecondNearestEnemyOf(Myself)) // Cloak of Mirroring
  CheckStatGT(SecondNearestEnemyOf(Myself),6,SAVEVSSPELL)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_CHROMATIC_ORB)
  !HasItemEquiped("CLCK26",NearestEnemyOf(Myself)) // Cloak of Mirroring
  CheckStatGT(NearestEnemyOf(Myself),6,SAVEVSSPELL)
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(NearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_CHROMATIC_ORB)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
  CheckStatGT(LastSeenBy(Myself),6,SAVEVSSPELL)
  !CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Magic Missile
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",SixthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SixthNearestEnemyOf(Myself))
  CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),80,MAGICDAMAGERESISTANCE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SixthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(SixthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",FifthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FifthNearestEnemyOf(Myself))
  CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),80,MAGICDAMAGERESISTANCE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FifthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(FifthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",FourthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FourthNearestEnemyOf(Myself))
  CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),80,MAGICDAMAGERESISTANCE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FourthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(FourthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",ThirdNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",ThirdNearestEnemyOf(Myself))
  CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),80,MAGICDAMAGERESISTANCE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",SecondNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SecondNearestEnemyOf(Myself))
  CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),80,MAGICDAMAGERESISTANCE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SecondNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(SecondNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",NearestEnemyOf(Myself))
  !HasItemEquiped("shld24",NearestEnemyOf(Myself))
  CheckStatLT(NearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(NearestEnemyOf(Myself),80,MAGICDAMAGERESISTANCE)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(NearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(NearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",SixthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SixthNearestEnemyOf(Myself))
  CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),40,MAGICDAMAGERESISTANCE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SixthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(SixthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",FifthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FifthNearestEnemyOf(Myself))
  CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),40,MAGICDAMAGERESISTANCE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FifthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(FifthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",FourthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FourthNearestEnemyOf(Myself))
  CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),40,MAGICDAMAGERESISTANCE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FourthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(FourthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",ThirdNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",ThirdNearestEnemyOf(Myself))
  CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),40,MAGICDAMAGERESISTANCE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",SecondNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SecondNearestEnemyOf(Myself))
  CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),40,MAGICDAMAGERESISTANCE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SecondNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(SecondNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",NearestEnemyOf(Myself))
  !HasItemEquiped("shld24",NearestEnemyOf(Myself))
  CheckStatLT(NearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(NearestEnemyOf(Myself),40,MAGICDAMAGERESISTANCE)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(NearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(NearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",SixthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SixthNearestEnemyOf(Myself))
  CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),10,MAGICDAMAGERESISTANCE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SixthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(SixthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",FifthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FifthNearestEnemyOf(Myself))
  CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),10,MAGICDAMAGERESISTANCE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FifthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(FifthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",FourthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FourthNearestEnemyOf(Myself))
  CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),10,MAGICDAMAGERESISTANCE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FourthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(FourthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",ThirdNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",ThirdNearestEnemyOf(Myself))
  CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),10,MAGICDAMAGERESISTANCE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",SecondNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SecondNearestEnemyOf(Myself))
  CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),10,MAGICDAMAGERESISTANCE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SecondNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(SecondNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",NearestEnemyOf(Myself))
  !HasItemEquiped("shld24",NearestEnemyOf(Myself))
  CheckStatLT(NearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(NearestEnemyOf(Myself),10,MAGICDAMAGERESISTANCE)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(NearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(NearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  See(LastSeenBy(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !HasItemEquiped("clck26",LastSeenBy(Myself))
  !HasItemEquiped("shld24",LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  CheckStatLT(LastSeenBy(Myself),80,MAGICDAMAGERESISTANCE)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(LastSeenBy(Myself),ENTROPY_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SHIELD)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Attack
/////////////////////////////////////////////////////////////////////
IF
  OR(6)
    See(Player1)
    See(Player2)
    See(Player3)
    See(Player4)
    See(Player5)
    See(Player6)
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  CheckStatLT(NearestEnemyOf(Myself),1,SANCTUARY)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,SANCTUARY)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,SANCTUARY)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,SANCTUARY)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,SANCTUARY)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,SANCTUARY)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(NearestEnemyOf(Myself),1,SANCTUARY)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,SANCTUARY)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,SANCTUARY)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,SANCTUARY)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,SANCTUARY)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,SANCTUARY)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(NearestEnemyOf(Myself),1,SANCTUARY)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,SANCTUARY)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,SANCTUARY)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,SANCTUARY)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,SANCTUARY)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,SANCTUARY)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
  !StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(NearestEnemyOf(Myself),1,SANCTUARY)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

// EEex - Is Moving Check 1

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,SANCTUARY)
  Range(SixthNearestEnemyOf(Myself),5)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,SANCTUARY)
  Range(FifthNearestEnemyOf(Myself),5)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,SANCTUARY)
  Range(FourthNearestEnemyOf(Myself),5)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,SANCTUARY)
  Range(ThirdNearestEnemyOf(Myself),5)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,SANCTUARY)
  Range(SecondNearestEnemyOf(Myself),5)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
  !StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(NearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(NearestEnemyOf(Myself),1,SANCTUARY)
  Range(NearestEnemyOf(Myself),5)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

// EEex - Is Moving Check 2

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  StateCheck(SixthNearestEnemyOf(Myself),STATE_IMMOBILE)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,SANCTUARY)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
  StateCheck(FifthNearestEnemyOf(Myself),STATE_IMMOBILE)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,SANCTUARY)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
  StateCheck(FourthNearestEnemyOf(Myself),STATE_IMMOBILE)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,SANCTUARY)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
  StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMMOBILE)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,SANCTUARY)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
  StateCheck(SecondNearestEnemyOf(Myself),STATE_IMMOBILE)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,SANCTUARY)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
  StateCheck(NearestEnemyOf(Myself),STATE_IMMOBILE)
  CheckStatLT(NearestEnemyOf(Myself),1,SANCTUARY)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

// EEex - Target Caster (Melee)

IF
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  WeaponEffectiveVs(LastSeenBy(Myself),MAINHAND)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  OR(2)
    CheckStatLT(Myself,1,SANCTUARY)
    HPPercentGT(Myself,49)
THEN
  RESPONSE #100
    SetGlobal("MO_AttackedSomeone","LOCALS",1)
    AttackReevaluate(LastSeenBy(Myself),30)
END

IF
  !Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  Allegiance(LastSeenBy(Myself),ENEMY)
  WeaponEffectiveVs(LastSeenBy(Myself),MAINHAND)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  OR(2)
    CheckStatLT(Myself,1,SANCTUARY)
    HPPercentGT(Myself,49)
THEN
  RESPONSE #100
    SetGlobal("MO_AttackedSomeone","LOCALS",1)
    AttackReevaluate(LastSeenBy(Myself),30)
END



