IF
    See(NearestEnemyOf(Myself))
    Global("SpellTrigger","LOCALS",0)
    !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
    RESPONSE #100
        DisplayString(Myself,39968)  // Spell Trigger—Fired
        DisplayString(Myself,43046)  // Spell Trigger—Mislead
        ReallyForceSpell(Myself,WIZARD_MISLEAD)  // SPWI607.SPL (Mislead)
        SetGlobal("SpellTrigger","LOCALS",1)
END

/////////////////////////////////////////////////////////////////////
// Stinking Cloud
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CloudTimer","LOCALS")
  HaveSpell(WIZARD_STINKING_CLOUD)
  !Range(SixthNearestEnemyOf(Myself),10)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_HARMLESS)
  !CheckStatGT(SixthNearestEnemyOf(Myself),25,RESISTMAGIC)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CloudTimer","LOCALS")
  HaveSpell(WIZARD_STINKING_CLOUD)
  !Range(FifthNearestEnemyOf(Myself),10)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_HARMLESS)
  !CheckStatGT(FifthNearestEnemyOf(Myself),25,RESISTMAGIC)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CloudTimer","LOCALS")
  HaveSpell(WIZARD_STINKING_CLOUD)
  !Range(FourthNearestEnemyOf(Myself),10)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_HARMLESS)
  !CheckStatGT(FourthNearestEnemyOf(Myself),25,RESISTMAGIC)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CloudTimer","LOCALS")
  HaveSpell(WIZARD_STINKING_CLOUD)
  !Range(ThirdNearestEnemyOf(Myself),10)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_HARMLESS)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),25,RESISTMAGIC)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CloudTimer","LOCALS")
  HaveSpell(WIZARD_STINKING_CLOUD)
  !Range(SecondNearestEnemyOf(Myself),10)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_HARMLESS)
  !CheckStatGT(SecondNearestEnemyOf(Myself),25,RESISTMAGIC)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CloudTimer","LOCALS")
  HaveSpell(WIZARD_STINKING_CLOUD)
  !Range(NearestEnemyOf(Myself),10)
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(NearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(NearestEnemyOf(Myself),STATE_HARMLESS)
  !CheckStatGT(NearestEnemyOf(Myself),25,RESISTMAGIC)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CloudTimer","LOCALS")
  HaveSpell(WIZARD_STINKING_CLOUD)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !Range(LastSeenBy(Myself),10)
  !CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_CloudTimer","LOCALS",30)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Cone of Cold
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ConeColdTimer","LOCALS")
  HaveSpell(WIZARD_CONE_OF_COLD)
  Range(SixthNearestEnemyOf(Myself),4)
  !HasItemEquiped("CLCK26",SixthNearestEnemyOf(Myself)) // Cloak of Mirroring
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SixthNearestEnemyOf(Myself),80,RESISTMAGIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),80,RESISTCOLD)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ConeColdTimer","LOCALS")
  HaveSpell(WIZARD_CONE_OF_COLD)
  Range(FifthNearestEnemyOf(Myself),4)
  !HasItemEquiped("CLCK26",FifthNearestEnemyOf(Myself)) // Cloak of Mirroring
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FifthNearestEnemyOf(Myself),80,RESISTMAGIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),80,RESISTCOLD)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ConeColdTimer","LOCALS")
  HaveSpell(WIZARD_CONE_OF_COLD)
  Range(FourthNearestEnemyOf(Myself),4)
  !HasItemEquiped("CLCK26",FourthNearestEnemyOf(Myself)) // Cloak of Mirroring
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FourthNearestEnemyOf(Myself),80,RESISTMAGIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),80,RESISTCOLD)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ConeColdTimer","LOCALS")
  HaveSpell(WIZARD_CONE_OF_COLD)
  Range(ThirdNearestEnemyOf(Myself),4)
  !HasItemEquiped("CLCK26",ThirdNearestEnemyOf(Myself)) // Cloak of Mirroring
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),80,RESISTMAGIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),80,RESISTCOLD)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ConeColdTimer","LOCALS")
  HaveSpell(WIZARD_CONE_OF_COLD)
  Range(SecondNearestEnemyOf(Myself),4)
  !HasItemEquiped("CLCK26",SecondNearestEnemyOf(Myself)) // Cloak of Mirroring
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SecondNearestEnemyOf(Myself),80,RESISTMAGIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),80,RESISTCOLD)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ConeColdTimer","LOCALS")
  HaveSpell(WIZARD_CONE_OF_COLD)
  Range(NearestEnemyOf(Myself),4)
  !HasItemEquiped("CLCK26",NearestEnemyOf(Myself)) // Cloak of Mirroring
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(NearestEnemyOf(Myself),80,RESISTMAGIC)
  CheckStatLT(NearestEnemyOf(Myself),80,RESISTCOLD)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ConeColdTimer","LOCALS")
  HaveSpell(WIZARD_CONE_OF_COLD)
  Range(SixthNearestEnemyOf(Myself),4)
  !HasItemEquiped("CLCK26",SixthNearestEnemyOf(Myself)) // Cloak of Mirroring
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTCOLD)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ConeColdTimer","LOCALS")
  HaveSpell(WIZARD_CONE_OF_COLD)
  Range(FifthNearestEnemyOf(Myself),4)
  !HasItemEquiped("CLCK26",FifthNearestEnemyOf(Myself)) // Cloak of Mirroring
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTCOLD)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ConeColdTimer","LOCALS")
  HaveSpell(WIZARD_CONE_OF_COLD)
  Range(FourthNearestEnemyOf(Myself),4)
  !HasItemEquiped("CLCK26",FourthNearestEnemyOf(Myself)) // Cloak of Mirroring
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTCOLD)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ConeColdTimer","LOCALS")
  HaveSpell(WIZARD_CONE_OF_COLD)
  Range(ThirdNearestEnemyOf(Myself),4)
  !HasItemEquiped("CLCK26",ThirdNearestEnemyOf(Myself)) // Cloak of Mirroring
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTCOLD)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ConeColdTimer","LOCALS")
  HaveSpell(WIZARD_CONE_OF_COLD)
  Range(SecondNearestEnemyOf(Myself),4)
  !HasItemEquiped("CLCK26",SecondNearestEnemyOf(Myself)) // Cloak of Mirroring
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTCOLD)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ConeColdTimer","LOCALS")
  HaveSpell(WIZARD_CONE_OF_COLD)
  Range(NearestEnemyOf(Myself),4)
  !HasItemEquiped("CLCK26",NearestEnemyOf(Myself)) // Cloak of Mirroring
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(NearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(NearestEnemyOf(Myself),50,RESISTCOLD)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ConeColdTimer","LOCALS")
  HaveSpell(WIZARD_CONE_OF_COLD)
  Range(SixthNearestEnemyOf(Myself),4)
  !HasItemEquiped("CLCK26",SixthNearestEnemyOf(Myself)) // Cloak of Mirroring
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SixthNearestEnemyOf(Myself),20,RESISTMAGIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),20,RESISTCOLD)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ConeColdTimer","LOCALS")
  HaveSpell(WIZARD_CONE_OF_COLD)
  Range(FifthNearestEnemyOf(Myself),4)
  !HasItemEquiped("CLCK26",FifthNearestEnemyOf(Myself)) // Cloak of Mirroring
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FifthNearestEnemyOf(Myself),20,RESISTMAGIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),20,RESISTCOLD)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ConeColdTimer","LOCALS")
  HaveSpell(WIZARD_CONE_OF_COLD)
  Range(FourthNearestEnemyOf(Myself),4)
  !HasItemEquiped("CLCK26",FourthNearestEnemyOf(Myself)) // Cloak of Mirroring
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FourthNearestEnemyOf(Myself),20,RESISTMAGIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),20,RESISTCOLD)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ConeColdTimer","LOCALS")
  HaveSpell(WIZARD_CONE_OF_COLD)
  Range(ThirdNearestEnemyOf(Myself),4)
  !HasItemEquiped("CLCK26",ThirdNearestEnemyOf(Myself)) // Cloak of Mirroring
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),20,RESISTMAGIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),20,RESISTCOLD)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ConeColdTimer","LOCALS")
  HaveSpell(WIZARD_CONE_OF_COLD)
  Range(SecondNearestEnemyOf(Myself),4)
  !HasItemEquiped("CLCK26",SecondNearestEnemyOf(Myself)) // Cloak of Mirroring
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SecondNearestEnemyOf(Myself),20,RESISTMAGIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),20,RESISTCOLD)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ConeColdTimer","LOCALS")
  HaveSpell(WIZARD_CONE_OF_COLD)
  Range(NearestEnemyOf(Myself),4)
  !HasItemEquiped("CLCK26",NearestEnemyOf(Myself)) // Cloak of Mirroring
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(NearestEnemyOf(Myself),20,RESISTMAGIC)
  CheckStatLT(NearestEnemyOf(Myself),20,RESISTCOLD)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ConeColdTimer","LOCALS")
  HaveSpell(WIZARD_CONE_OF_COLD)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),4)
  !HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
  !CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),80,RESISTMAGIC)
  CheckStatLT(LastSeenBy(Myself),80,RESISTCOLD)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_ConeColdTimer","LOCALS",12)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_CONE_OF_COLD)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Ice Storm
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_ICE_STORM)  // SPWI404.SPL (Ice Storm)
  !CheckStatGT(SixthNearestEnemyOf(Myself),35,RESISTCOLD)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_ICE_STORM)  // SPWI404.SPL (Ice Storm)
  !CheckStatGT(FifthNearestEnemyOf(Myself),35,RESISTCOLD)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_ICE_STORM)  // SPWI404.SPL (Ice Storm)
  !CheckStatGT(FourthNearestEnemyOf(Myself),35,RESISTCOLD)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_ICE_STORM)  // SPWI404.SPL (Ice Storm)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),35,RESISTCOLD)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_ICE_STORM)  // SPWI404.SPL (Ice Storm)
  !CheckStatGT(SecondNearestEnemyOf(Myself),35,RESISTCOLD)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_ICE_STORM)  // SPWI404.SPL (Ice Storm)
  !CheckStatGT(NearestEnemyOf(Myself),35,RESISTCOLD)
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_ICE_STORM)  // SPWI404.SPL (Ice Storm)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !CheckStatGT(LastSeenBy(Myself),35,RESISTCOLD)
  !CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_ICE_STORM)  // SPWI404.SPL (Ice Storm)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Lightning Bolt 
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_LightningBoltTimer","LOCALS")
  HaveSpell(WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Lightning Bolt)
  !HasItemEquiped("CLCK24",SixthNearestEnemyOf(Myself)) // Cloak of reflection
  !HasItemEquiped("CLCK26",SixthNearestEnemyOf(Myself)) // Cloak of Mirroring
  CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTELECTRICITY)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_LightningBoltTimer","LOCALS")
  HaveSpell(WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Lightning Bolt)
  !HasItemEquiped("CLCK24",FifthNearestEnemyOf(Myself)) // Cloak of reflection
  !HasItemEquiped("CLCK26",FifthNearestEnemyOf(Myself)) // Cloak of Mirroring
  CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTELECTRICITY)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_LightningBoltTimer","LOCALS")
  HaveSpell(WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Lightning Bolt)
  !HasItemEquiped("CLCK24",FourthNearestEnemyOf(Myself)) // Cloak of reflection
  !HasItemEquiped("CLCK26",FourthNearestEnemyOf(Myself)) // Cloak of Mirroring
  CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTELECTRICITY)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_LightningBoltTimer","LOCALS")
  HaveSpell(WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Lightning Bolt)
  !HasItemEquiped("CLCK24",ThirdNearestEnemyOf(Myself)) // Cloak of reflection
  !HasItemEquiped("CLCK26",ThirdNearestEnemyOf(Myself)) // Cloak of Mirroring
  CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTELECTRICITY)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_LightningBoltTimer","LOCALS")
  HaveSpell(WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Lightning Bolt)
  !HasItemEquiped("CLCK24",SecondNearestEnemyOf(Myself)) // Cloak of reflection
  !HasItemEquiped("CLCK26",SecondNearestEnemyOf(Myself)) // Cloak of Mirroring
  CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTELECTRICITY)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_LightningBoltTimer","LOCALS")
  HaveSpell(WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Lightning Bolt)
  !HasItemEquiped("CLCK24",NearestEnemyOf(Myself)) // Cloak of reflection
  !HasItemEquiped("CLCK26",NearestEnemyOf(Myself)) // Cloak of Mirroring
  CheckStatLT(NearestEnemyOf(Myself),50,RESISTELECTRICITY)
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_LightningBoltTimer","LOCALS")
  HaveSpell(WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Lightning Bolt)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !HasItemEquiped("CLCK24",LastSeenBy(Myself)) // Cloak of reflection
  !HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
  CheckStatLT(LastSeenBy(Myself),50,RESISTELECTRICITY)
  !CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_LightningBoltTimer","LOCALS",12)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Chain Lightning 
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChainLightningTimer","LOCALS")
  HaveSpell(WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
  NumCreatureGT([GOODCUTOFF],2)
  !HasItemEquiped("clck26",SixthNearestEnemyOf(Myself))  // Cloak of Mirroring
  !HasItemEquiped("clck24",SixthNearestEnemyOf(Myself))  // Cloak of Reflection
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_HARMLESS)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),80,RESISTELECTRICITY)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChainLightningTimer","LOCALS")
  HaveSpell(WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
  NumCreatureGT([GOODCUTOFF],2)
  !HasItemEquiped("clck26",FifthNearestEnemyOf(Myself))  // Cloak of Mirroring
  !HasItemEquiped("clck24",FifthNearestEnemyOf(Myself))  // Cloak of Reflection
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_HARMLESS)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),80,RESISTELECTRICITY)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChainLightningTimer","LOCALS")
  HaveSpell(WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
  NumCreatureGT([GOODCUTOFF],2)
  !HasItemEquiped("clck26",FourthNearestEnemyOf(Myself))  // Cloak of Mirroring
  !HasItemEquiped("clck24",FourthNearestEnemyOf(Myself))  // Cloak of Reflection
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_HARMLESS)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),80,RESISTELECTRICITY)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChainLightningTimer","LOCALS")
  HaveSpell(WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
  NumCreatureGT([GOODCUTOFF],2)
  !HasItemEquiped("clck26",ThirdNearestEnemyOf(Myself))  // Cloak of Mirroring
  !HasItemEquiped("clck24",ThirdNearestEnemyOf(Myself))  // Cloak of Reflection
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_HARMLESS)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),80,RESISTELECTRICITY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChainLightningTimer","LOCALS")
  HaveSpell(WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
  NumCreatureGT([GOODCUTOFF],2)
  !HasItemEquiped("clck26",SecondNearestEnemyOf(Myself))  // Cloak of Mirroring
  !HasItemEquiped("clck24",SecondNearestEnemyOf(Myself))  // Cloak of Reflection
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_HARMLESS)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),80,RESISTELECTRICITY)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChainLightningTimer","LOCALS")
  HaveSpell(WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
  NumCreatureGT([GOODCUTOFF],2)
  !HasItemEquiped("clck26",NearestEnemyOf(Myself))  // Cloak of Mirroring
  !HasItemEquiped("clck24",NearestEnemyOf(Myself))  // Cloak of Reflection
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(NearestEnemyOf(Myself),STATE_HARMLESS)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(NearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(NearestEnemyOf(Myself),80,RESISTELECTRICITY)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChainLightningTimer","LOCALS")
  HaveSpell(WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
  NumCreatureGT([GOODCUTOFF],2)
  !HasItemEquiped("clck26",SixthNearestEnemyOf(Myself))  // Cloak of Mirroring
  !HasItemEquiped("clck24",SixthNearestEnemyOf(Myself))  // Cloak of Reflection
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_HARMLESS)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTELECTRICITY)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChainLightningTimer","LOCALS")
  HaveSpell(WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
  NumCreatureGT([GOODCUTOFF],2)
  !HasItemEquiped("clck26",FifthNearestEnemyOf(Myself))  // Cloak of Mirroring
  !HasItemEquiped("clck24",FifthNearestEnemyOf(Myself))  // Cloak of Reflection
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_HARMLESS)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTELECTRICITY)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChainLightningTimer","LOCALS")
  HaveSpell(WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
  NumCreatureGT([GOODCUTOFF],2)
  !HasItemEquiped("clck26",FourthNearestEnemyOf(Myself))  // Cloak of Mirroring
  !HasItemEquiped("clck24",FourthNearestEnemyOf(Myself))  // Cloak of Reflection
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_HARMLESS)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTELECTRICITY)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChainLightningTimer","LOCALS")
  HaveSpell(WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
  NumCreatureGT([GOODCUTOFF],2)
  !HasItemEquiped("clck26",ThirdNearestEnemyOf(Myself))  // Cloak of Mirroring
  !HasItemEquiped("clck24",ThirdNearestEnemyOf(Myself))  // Cloak of Reflection
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_HARMLESS)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTELECTRICITY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChainLightningTimer","LOCALS")
  HaveSpell(WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
  NumCreatureGT([GOODCUTOFF],2)
  !HasItemEquiped("clck26",SecondNearestEnemyOf(Myself))  // Cloak of Mirroring
  !HasItemEquiped("clck24",SecondNearestEnemyOf(Myself))  // Cloak of Reflection
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_HARMLESS)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTELECTRICITY)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChainLightningTimer","LOCALS")
  HaveSpell(WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
  NumCreatureGT([GOODCUTOFF],2)
  !HasItemEquiped("clck26",NearestEnemyOf(Myself))  // Cloak of Mirroring
  !HasItemEquiped("clck24",NearestEnemyOf(Myself))  // Cloak of Reflection
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(NearestEnemyOf(Myself),STATE_HARMLESS)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(NearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(NearestEnemyOf(Myself),50,RESISTELECTRICITY)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChainLightningTimer","LOCALS")
  HaveSpell(WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
  NumCreatureGT([GOODCUTOFF],2)
  !HasItemEquiped("clck26",SixthNearestEnemyOf(Myself))  // Cloak of Mirroring
  !HasItemEquiped("clck24",SixthNearestEnemyOf(Myself))  // Cloak of Reflection
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_HARMLESS)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SixthNearestEnemyOf(Myself),20,RESISTMAGIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),20,RESISTELECTRICITY)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChainLightningTimer","LOCALS")
  HaveSpell(WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
  NumCreatureGT([GOODCUTOFF],2)
  !HasItemEquiped("clck26",FifthNearestEnemyOf(Myself))  // Cloak of Mirroring
  !HasItemEquiped("clck24",FifthNearestEnemyOf(Myself))  // Cloak of Reflection
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_HARMLESS)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FifthNearestEnemyOf(Myself),20,RESISTMAGIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),20,RESISTELECTRICITY)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChainLightningTimer","LOCALS")
  HaveSpell(WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
  NumCreatureGT([GOODCUTOFF],2)
  !HasItemEquiped("clck26",FourthNearestEnemyOf(Myself))  // Cloak of Mirroring
  !HasItemEquiped("clck24",FourthNearestEnemyOf(Myself))  // Cloak of Reflection
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_HARMLESS)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FourthNearestEnemyOf(Myself),20,RESISTMAGIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),20,RESISTELECTRICITY)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChainLightningTimer","LOCALS")
  HaveSpell(WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
  NumCreatureGT([GOODCUTOFF],2)
  !HasItemEquiped("clck26",ThirdNearestEnemyOf(Myself))  // Cloak of Mirroring
  !HasItemEquiped("clck24",ThirdNearestEnemyOf(Myself))  // Cloak of Reflection
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_HARMLESS)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),20,RESISTMAGIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),20,RESISTELECTRICITY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChainLightningTimer","LOCALS")
  HaveSpell(WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
  NumCreatureGT([GOODCUTOFF],2)
  !HasItemEquiped("clck26",SecondNearestEnemyOf(Myself))  // Cloak of Mirroring
  !HasItemEquiped("clck24",SecondNearestEnemyOf(Myself))  // Cloak of Reflection
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_HARMLESS)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SecondNearestEnemyOf(Myself),20,RESISTMAGIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),20,RESISTELECTRICITY)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChainLightningTimer","LOCALS")
  HaveSpell(WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
  NumCreatureGT([GOODCUTOFF],2)
  !HasItemEquiped("clck26",NearestEnemyOf(Myself))  // Cloak of Mirroring
  !HasItemEquiped("clck24",NearestEnemyOf(Myself))  // Cloak of Reflection
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(NearestEnemyOf(Myself),STATE_HARMLESS)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(NearestEnemyOf(Myself),20,RESISTMAGIC)
  CheckStatLT(NearestEnemyOf(Myself),20,RESISTELECTRICITY)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChainLightningTimer","LOCALS")
  HaveSpell(WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  NumCreatureGT([GOODCUTOFF],2)
  !HasItemEquiped("clck26",LastSeenBy(Myself))  // Cloak of Mirroring
  !HasItemEquiped("clck24",LastSeenBy(Myself))  // Cloak of Reflection
  !CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  CheckStatLT(LastSeenBy(Myself),80,RESISTELECTRICITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_ChainLightningTimer","LOCALS",12)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Magic Missile
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",SixthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SixthNearestEnemyOf(Myself))
  CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),80,MAGICDAMAGERESISTANCE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SixthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(SixthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",FifthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FifthNearestEnemyOf(Myself))
  CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),80,MAGICDAMAGERESISTANCE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FifthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(FifthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",FourthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FourthNearestEnemyOf(Myself))
  CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),80,MAGICDAMAGERESISTANCE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FourthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(FourthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",ThirdNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",ThirdNearestEnemyOf(Myself))
  CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),80,MAGICDAMAGERESISTANCE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",SecondNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SecondNearestEnemyOf(Myself))
  CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),80,MAGICDAMAGERESISTANCE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SecondNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(SecondNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",NearestEnemyOf(Myself))
  !HasItemEquiped("shld24",NearestEnemyOf(Myself))
  CheckStatLT(NearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(NearestEnemyOf(Myself),80,MAGICDAMAGERESISTANCE)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(NearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(NearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",SixthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SixthNearestEnemyOf(Myself))
  CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),40,MAGICDAMAGERESISTANCE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SixthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(SixthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",FifthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FifthNearestEnemyOf(Myself))
  CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),40,MAGICDAMAGERESISTANCE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FifthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(FifthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",FourthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FourthNearestEnemyOf(Myself))
  CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),40,MAGICDAMAGERESISTANCE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FourthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(FourthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",ThirdNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",ThirdNearestEnemyOf(Myself))
  CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),40,MAGICDAMAGERESISTANCE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",SecondNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SecondNearestEnemyOf(Myself))
  CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),40,MAGICDAMAGERESISTANCE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SecondNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(SecondNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",NearestEnemyOf(Myself))
  !HasItemEquiped("shld24",NearestEnemyOf(Myself))
  CheckStatLT(NearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(NearestEnemyOf(Myself),40,MAGICDAMAGERESISTANCE)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(NearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(NearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",SixthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SixthNearestEnemyOf(Myself))
  CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),10,MAGICDAMAGERESISTANCE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SixthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(SixthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",FifthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FifthNearestEnemyOf(Myself))
  CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),10,MAGICDAMAGERESISTANCE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FifthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(FifthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",FourthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FourthNearestEnemyOf(Myself))
  CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),10,MAGICDAMAGERESISTANCE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FourthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(FourthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",ThirdNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",ThirdNearestEnemyOf(Myself))
  CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),10,MAGICDAMAGERESISTANCE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",SecondNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SecondNearestEnemyOf(Myself))
  CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),10,MAGICDAMAGERESISTANCE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SecondNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(SecondNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",NearestEnemyOf(Myself))
  !HasItemEquiped("shld24",NearestEnemyOf(Myself))
  CheckStatLT(NearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(NearestEnemyOf(Myself),10,MAGICDAMAGERESISTANCE)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(NearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(NearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  See(LastSeenBy(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !HasItemEquiped("clck26",LastSeenBy(Myself))
  !HasItemEquiped("shld24",LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  CheckStatLT(LastSeenBy(Myself),80,MAGICDAMAGERESISTANCE)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(LastSeenBy(Myself),ENTROPY_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SHIELD)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Scorcher
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_AGANNAZAR_SCORCHER)
  !HasItemEquiped("CLCK26",SixthNearestEnemyOf(Myself)) // Cloak of Mirroring
  !Gender(SixthNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  !CheckStatGT(SixthNearestEnemyOf(Myself),25,RESISTMAGIC)
  !CheckStatGT(SixthNearestEnemyOf(Myself),25,RESISTFIRE)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_AGANNAZAR_SCORCHER)
  !HasItemEquiped("CLCK26",FifthNearestEnemyOf(Myself)) // Cloak of Mirroring
  !Gender(FifthNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  !CheckStatGT(FifthNearestEnemyOf(Myself),25,RESISTMAGIC)
  !CheckStatGT(FifthNearestEnemyOf(Myself),25,RESISTFIRE)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_AGANNAZAR_SCORCHER)
  !HasItemEquiped("CLCK26",FourthNearestEnemyOf(Myself)) // Cloak of Mirroring
  !Gender(FourthNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  !CheckStatGT(FourthNearestEnemyOf(Myself),25,RESISTMAGIC)
  !CheckStatGT(FourthNearestEnemyOf(Myself),25,RESISTFIRE)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_AGANNAZAR_SCORCHER)
  !HasItemEquiped("CLCK26",ThirdNearestEnemyOf(Myself)) // Cloak of Mirroring
  !Gender(ThirdNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),25,RESISTMAGIC)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),25,RESISTFIRE)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_AGANNAZAR_SCORCHER)
  !HasItemEquiped("CLCK26",SecondNearestEnemyOf(Myself)) // Cloak of Mirroring
  !Gender(SecondNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  !CheckStatGT(SecondNearestEnemyOf(Myself),25,RESISTMAGIC)
  !CheckStatGT(SecondNearestEnemyOf(Myself),25,RESISTFIRE)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_AGANNAZAR_SCORCHER)
  !HasItemEquiped("CLCK26",NearestEnemyOf(Myself)) // Cloak of Mirroring
  !Gender(NearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(NearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  !CheckStatGT(NearestEnemyOf(Myself),25,RESISTMAGIC)
  !CheckStatGT(NearestEnemyOf(Myself),25,RESISTFIRE)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_AGANNAZAR_SCORCHER)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTFIRE)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_AGANNAZAR_SCORCHER)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Attack
/////////////////////////////////////////////////////////////////////
IF
  See([GOODCUTOFF])
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  OR(6)
    See(Player1)
    See(Player2)
    See(Player3)
    See(Player4)
    See(Player5)
    See(Player6)
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !Allegiance(Myself,ENEMY)
  !CheckSpellState(SixthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",SixthNearestEnemyOf(Myself))
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  !Range(SixthNearestEnemyOf(Myself),5)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !Allegiance(Myself,ENEMY)
  !CheckSpellState(FifthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",FifthNearestEnemyOf(Myself))
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  !Range(FifthNearestEnemyOf(Myself),5)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !Allegiance(Myself,ENEMY)
  !CheckSpellState(FourthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",FourthNearestEnemyOf(Myself))
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  !Range(FourthNearestEnemyOf(Myself),5)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !Allegiance(Myself,ENEMY)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",ThirdNearestEnemyOf(Myself))
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  !Range(ThirdNearestEnemyOf(Myself),5)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !Allegiance(Myself,ENEMY)
  !CheckSpellState(SecondNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",SecondNearestEnemyOf(Myself))
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  !Range(SecondNearestEnemyOf(Myself),5)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !Allegiance(Myself,ENEMY)
  !CheckSpellState(NearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(NearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",NearestEnemyOf(Myself))
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  !Range(NearestEnemyOf(Myself),5)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !Allegiance(Myself,ENEMY)
  !CheckSpellState(SixthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",SixthNearestEnemyOf(Myself))
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  !Range(SixthNearestEnemyOf(Myself),5)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !Allegiance(Myself,ENEMY)
  !CheckSpellState(FifthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",FifthNearestEnemyOf(Myself))
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
  !Range(FifthNearestEnemyOf(Myself),5)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !Allegiance(Myself,ENEMY)
  !CheckSpellState(FourthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",FourthNearestEnemyOf(Myself))
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
  !Range(FourthNearestEnemyOf(Myself),5)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !Allegiance(Myself,ENEMY)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",ThirdNearestEnemyOf(Myself))
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
  !Range(ThirdNearestEnemyOf(Myself),5)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !Allegiance(Myself,ENEMY)
  !CheckSpellState(SecondNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",SecondNearestEnemyOf(Myself))
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
  !Range(SecondNearestEnemyOf(Myself),5)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !Allegiance(Myself,ENEMY)
  !CheckSpellState(NearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(NearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",NearestEnemyOf(Myself))
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
  !Range(NearestEnemyOf(Myself),5)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  Allegiance(Myself,ENEMY)
  !CheckSpellState(SixthNearest([GOODCUTOFF]),ENTROPY_SHIELD)
  !CheckStatGT(SixthNearest([GOODCUTOFF]),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",SixthNearest([GOODCUTOFF])) // Shield of Reflection
  WeaponEffectiveVs(SixthNearest([GOODCUTOFF]),MAINHAND)
  WeaponCanDamage(SixthNearest([GOODCUTOFF]),MAINHAND)
  !Range(SixthNearest([GOODCUTOFF]),5)
  See(SixthNearest([GOODCUTOFF]))
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  !CheckSpellState(FifthNearest([GOODCUTOFF]),ENTROPY_SHIELD)
  !CheckStatGT(FifthNearest([GOODCUTOFF]),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",FifthNearest([GOODCUTOFF])) // Shield of Reflection
  WeaponEffectiveVs(FifthNearest([GOODCUTOFF]),MAINHAND)
  WeaponCanDamage(FifthNearest([GOODCUTOFF]),MAINHAND)
  !Range(FifthNearest([GOODCUTOFF]),5)
  See(FifthNearest([GOODCUTOFF]))
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  !CheckSpellState(FourthNearest([GOODCUTOFF]),ENTROPY_SHIELD)
  !CheckStatGT(FourthNearest([GOODCUTOFF]),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",FourthNearest([GOODCUTOFF])) // Shield of Reflection
  WeaponEffectiveVs(FourthNearest([GOODCUTOFF]),MAINHAND)
  WeaponCanDamage(FourthNearest([GOODCUTOFF]),MAINHAND)
  !Range(FourthNearest([GOODCUTOFF]),5)
  See(FourthNearest([GOODCUTOFF]))
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  !CheckSpellState(ThirdNearest([GOODCUTOFF]),ENTROPY_SHIELD)
  !CheckStatGT(ThirdNearest([GOODCUTOFF]),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",ThirdNearest([GOODCUTOFF])) // Shield of Reflection
  WeaponEffectiveVs(ThirdNearest([GOODCUTOFF]),MAINHAND)
  WeaponCanDamage(ThirdNearest([GOODCUTOFF]),MAINHAND)
  !Range(ThirdNearest([GOODCUTOFF]),5)
  See(ThirdNearest([GOODCUTOFF]))
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  !CheckSpellState(SecondNearest([GOODCUTOFF]),ENTROPY_SHIELD)
  !CheckStatGT(SecondNearest([GOODCUTOFF]),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",SecondNearest([GOODCUTOFF])) // Shield of Reflection
  WeaponEffectiveVs(SecondNearest([GOODCUTOFF]),MAINHAND)
  WeaponCanDamage(SecondNearest([GOODCUTOFF]),MAINHAND)
  !Range(SecondNearest([GOODCUTOFF]),5)
  See(SecondNearest([GOODCUTOFF]))
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  !CheckSpellState([GOODCUTOFF],ENTROPY_SHIELD)
  !CheckStatGT([GOODCUTOFF],0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",[GOODCUTOFF]) // Shield of Reflection
  WeaponEffectiveVs([GOODCUTOFF],MAINHAND)
  WeaponCanDamage([GOODCUTOFF],MAINHAND)
  !Range([GOODCUTOFF],5)
  See([GOODCUTOFF])
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(EASY)
  !CheckSpellState(SixthNearest([GOODCUTOFF]),ENTROPY_SHIELD)
  !CheckStatGT(SixthNearest([GOODCUTOFF]),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",SixthNearest([GOODCUTOFF])) // Shield of Reflection
  WeaponEffectiveVs(SixthNearest([GOODCUTOFF]),MAINHAND)
  WeaponCanDamage(SixthNearest([GOODCUTOFF]),MAINHAND)
  //CheckStatGT(SixthNearest([GOODCUTOFF]),-5,ACMISSILEMOD)
  CheckStatLT(SixthNearest([GOODCUTOFF]),1,STONESKINS)
  CheckStatLT(SixthNearest([GOODCUTOFF]),100,RESISTMISSILE)
  !Range(SixthNearest([GOODCUTOFF]),5)
  See(SixthNearest([GOODCUTOFF]))
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(EASY)
  !CheckSpellState(FifthNearest([GOODCUTOFF]),ENTROPY_SHIELD)
  !CheckStatGT(FifthNearest([GOODCUTOFF]),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",FifthNearest([GOODCUTOFF])) // Shield of Reflection
  WeaponEffectiveVs(FifthNearest([GOODCUTOFF]),MAINHAND)
  WeaponCanDamage(FifthNearest([GOODCUTOFF]),MAINHAND)
  //CheckStatGT(FifthNearest([GOODCUTOFF]),-5,ACMISSILEMOD)
  CheckStatLT(FifthNearest([GOODCUTOFF]),1,STONESKINS)
  CheckStatLT(FifthNearest([GOODCUTOFF]),100,RESISTMISSILE)
  !Range(FifthNearest([GOODCUTOFF]),5)
  See(FifthNearest([GOODCUTOFF]))
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(EASY)
  !CheckSpellState(FourthNearest([GOODCUTOFF]),ENTROPY_SHIELD)
  !CheckStatGT(FourthNearest([GOODCUTOFF]),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",FourthNearest([GOODCUTOFF])) // Shield of Reflection
  WeaponEffectiveVs(FourthNearest([GOODCUTOFF]),MAINHAND)
  WeaponCanDamage(FourthNearest([GOODCUTOFF]),MAINHAND)
  //CheckStatGT(FourthNearest([GOODCUTOFF]),-5,ACMISSILEMOD)
  CheckStatLT(FourthNearest([GOODCUTOFF]),1,STONESKINS)
  CheckStatLT(FourthNearest([GOODCUTOFF]),100,RESISTMISSILE)
  !Range(FourthNearest([GOODCUTOFF]),5)
  See(FourthNearest([GOODCUTOFF]))
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(EASY)
  !CheckSpellState(ThirdNearest([GOODCUTOFF]),ENTROPY_SHIELD)
  !CheckStatGT(ThirdNearest([GOODCUTOFF]),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",ThirdNearest([GOODCUTOFF])) // Shield of Reflection
  WeaponEffectiveVs(ThirdNearest([GOODCUTOFF]),MAINHAND)
  WeaponCanDamage(ThirdNearest([GOODCUTOFF]),MAINHAND)
  //CheckStatGT(ThirdNearest([GOODCUTOFF]),-5,ACMISSILEMOD)
  CheckStatLT(ThirdNearest([GOODCUTOFF]),1,STONESKINS)
  CheckStatLT(ThirdNearest([GOODCUTOFF]),100,RESISTMISSILE)
  !Range(ThirdNearest([GOODCUTOFF]),5)
  See(ThirdNearest([GOODCUTOFF]))
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(EASY)
  !CheckSpellState(SecondNearest([GOODCUTOFF]),ENTROPY_SHIELD)
  !CheckStatGT(SecondNearest([GOODCUTOFF]),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",SecondNearest([GOODCUTOFF])) // Shield of Reflection
  WeaponEffectiveVs(SecondNearest([GOODCUTOFF]),MAINHAND)
  WeaponCanDamage(SecondNearest([GOODCUTOFF]),MAINHAND)
  //CheckStatGT(SecondNearest([GOODCUTOFF]),-5,ACMISSILEMOD)
  CheckStatLT(SecondNearest([GOODCUTOFF]),1,STONESKINS)
  CheckStatLT(SecondNearest([GOODCUTOFF]),100,RESISTMISSILE)
  !Range(SecondNearest([GOODCUTOFF]),5)
  See(SecondNearest([GOODCUTOFF]))
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(EASY)
  !CheckSpellState([GOODCUTOFF],ENTROPY_SHIELD)
  !CheckStatGT([GOODCUTOFF],0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",[GOODCUTOFF]) // Shield of Reflection
  WeaponEffectiveVs([GOODCUTOFF],MAINHAND)
  WeaponCanDamage([GOODCUTOFF],MAINHAND)
  //CheckStatGT([GOODCUTOFF],-5,ACMISSILEMOD)
  CheckStatLT([GOODCUTOFF],1,STONESKINS)
  CheckStatLT([GOODCUTOFF],100,RESISTMISSILE)
  !Range([GOODCUTOFF],5)
  See([GOODCUTOFF])
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(NORMAL)
  !CheckSpellState(WorstAC([PC]),ENTROPY_SHIELD)
  !CheckStatGT(WorstAC([PC]),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",WorstAC([PC])) // Shield of Reflection
  WeaponEffectiveVs(WorstAC([PC]),MAINHAND)
  WeaponCanDamage(WorstAC([PC]),MAINHAND)
  //CheckStatGT(WorstAC([PC]),-5,ACMISSILEMOD)
  CheckStatLT(WorstAC([PC]),1,STONESKINS)
  CheckStatLT(WorstAC([PC]),100,RESISTMISSILE)
  !StateCheck(WorstAC([PC]),STATE_CHARMED)
  !Range(WorstAC([PC]),5)
  See(WorstAC([PC]))
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(HARD)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),ENTROPY_SHIELD)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",SecondNearest([GOODCUTOFF.0.0.DRUID_ALL])) // Shield of Reflection
  WeaponEffectiveVs(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),MAINHAND)
  WeaponCanDamage(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),MAINHAND)
  CheckStatGT(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),-10,ACMISSILEMOD)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),1,STONESKINS)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),100,RESISTMISSILE)
  !Range(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),5)
  See(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]))
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(HARD)
  !CheckSpellState([GOODCUTOFF.0.0.DRUID_ALL],ENTROPY_SHIELD)
  !CheckStatGT([GOODCUTOFF.0.0.DRUID_ALL],0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",[GOODCUTOFF.0.0.DRUID_ALL]) // Shield of Reflection
  WeaponEffectiveVs([GOODCUTOFF.0.0.DRUID_ALL],MAINHAND)
  WeaponCanDamage([GOODCUTOFF.0.0.DRUID_ALL],MAINHAND)
  CheckStatGT([GOODCUTOFF.0.0.DRUID_ALL],-10,ACMISSILEMOD)
  CheckStatLT([GOODCUTOFF.0.0.DRUID_ALL],1,STONESKINS)
  CheckStatLT([GOODCUTOFF.0.0.DRUID_ALL],100,RESISTMISSILE)
  !Range([GOODCUTOFF.0.0.DRUID_ALL],5)
  See([GOODCUTOFF.0.0.DRUID_ALL])
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(HARD)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),ENTROPY_SHIELD)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL])) // Shield of Reflection
  WeaponEffectiveVs(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),MAINHAND)
  WeaponCanDamage(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),MAINHAND)
  CheckStatGT(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),-10,ACMISSILEMOD)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),1,STONESKINS)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),100,RESISTMISSILE)
  !Range(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),5)
  See(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]))
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(HARD)
  !CheckSpellState([GOODCUTOFF.0.0.CLERIC_ALL],ENTROPY_SHIELD)
  !CheckStatGT([GOODCUTOFF.0.0.CLERIC_ALL],0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",[GOODCUTOFF.0.0.CLERIC_ALL]) // Shield of Reflection
  WeaponEffectiveVs([GOODCUTOFF.0.0.CLERIC_ALL],MAINHAND)
  WeaponCanDamage([GOODCUTOFF.0.0.CLERIC_ALL],MAINHAND)
  CheckStatGT([GOODCUTOFF.0.0.CLERIC_ALL],-10,ACMISSILEMOD)
  CheckStatLT([GOODCUTOFF.0.0.CLERIC_ALL],1,STONESKINS)
  CheckStatLT([GOODCUTOFF.0.0.CLERIC_ALL],100,RESISTMISSILE)
  !Range([GOODCUTOFF.0.0.CLERIC_ALL],5)
  See([GOODCUTOFF.0.0.CLERIC_ALL])
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(HARD)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.THIEF]),ENTROPY_SHIELD)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.THIEF]),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",SecondNearest([GOODCUTOFF.0.0.THIEF])) // Shield of Reflection
  WeaponEffectiveVs(SecondNearest([GOODCUTOFF.0.0.THIEF]),MAINHAND)
  WeaponCanDamage(SecondNearest([GOODCUTOFF.0.0.THIEF]),MAINHAND)
  CheckStatGT(SecondNearest([GOODCUTOFF.0.0.THIEF]),-10,ACMISSILEMOD)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.THIEF]),1,STONESKINS)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.THIEF]),100,RESISTMISSILE)
  !Range(SecondNearest([GOODCUTOFF.0.0.THIEF]),5)
  See(SecondNearest([GOODCUTOFF.0.0.THIEF]))
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(HARD)
  !CheckSpellState([GOODCUTOFF.0.0.THIEF],ENTROPY_SHIELD)
  !CheckStatGT([GOODCUTOFF.0.0.THIEF],0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",[GOODCUTOFF.0.0.THIEF]) // Shield of Reflection
  WeaponEffectiveVs([GOODCUTOFF.0.0.THIEF],MAINHAND)
  WeaponCanDamage([GOODCUTOFF.0.0.THIEF],MAINHAND)
  CheckStatGT([GOODCUTOFF.0.0.THIEF],-10,ACMISSILEMOD)
  CheckStatLT([GOODCUTOFF.0.0.THIEF],1,STONESKINS)
  CheckStatLT([GOODCUTOFF.0.0.THIEF],100,RESISTMISSILE)
  !Range([GOODCUTOFF.0.0.THIEF],5)
  See([GOODCUTOFF.0.0.THIEF])
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(HARD)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),ENTROPY_SHIELD)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",SecondNearest([GOODCUTOFF.0.0.BARD_ALL])) // Shield of Reflection
  WeaponEffectiveVs(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),MAINHAND)
  WeaponCanDamage(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),MAINHAND)
  CheckStatGT(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),-10,ACMISSILEMOD)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),1,STONESKINS)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),100,RESISTMISSILE)
  !Range(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),5)
  See(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]))
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(HARD)
  !CheckSpellState([GOODCUTOFF.0.0.BARD_ALL],ENTROPY_SHIELD)
  !CheckStatGT([GOODCUTOFF.0.0.BARD_ALL],0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",[GOODCUTOFF.0.0.BARD_ALL]) // Shield of Reflection
  WeaponEffectiveVs([GOODCUTOFF.0.0.BARD_ALL],MAINHAND)
  WeaponCanDamage([GOODCUTOFF.0.0.BARD_ALL],MAINHAND)
  CheckStatGT([GOODCUTOFF.0.0.BARD_ALL],-10,ACMISSILEMOD)
  CheckStatLT([GOODCUTOFF.0.0.BARD_ALL],1,STONESKINS)
  CheckStatLT([GOODCUTOFF.0.0.BARD_ALL],100,RESISTMISSILE)
  !Range([GOODCUTOFF.0.0.BARD_ALL],5)
  See([GOODCUTOFF.0.0.BARD_ALL])
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(HARD)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),ENTROPY_SHIELD)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",SecondNearest([GOODCUTOFF.0.0.MAGE_ALL])) // Shield of Reflection
  WeaponEffectiveVs(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),MAINHAND)
  WeaponCanDamage(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),MAINHAND)
  CheckStatGT(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),-10,ACMISSILEMOD)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),1,STONESKINS)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),100,RESISTMISSILE)
  !Range(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),5)
  See(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]))
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(HARD)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE_ALL],ENTROPY_SHIELD)
  !CheckStatGT([GOODCUTOFF.0.0.MAGE_ALL],0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",[GOODCUTOFF.0.0.MAGE_ALL]) // Shield of Reflection
  WeaponEffectiveVs([GOODCUTOFF.0.0.MAGE_ALL],MAINHAND)
  WeaponCanDamage([GOODCUTOFF.0.0.MAGE_ALL],MAINHAND)
  CheckStatGT([GOODCUTOFF.0.0.MAGE_ALL],-10,ACMISSILEMOD)
  CheckStatLT([GOODCUTOFF.0.0.MAGE_ALL],1,STONESKINS)
  CheckStatLT([GOODCUTOFF.0.0.MAGE_ALL],100,RESISTMISSILE)
  !Range([GOODCUTOFF.0.0.MAGE_ALL],5)
  See([GOODCUTOFF.0.0.MAGE_ALL])
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(HARD)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE_THIEF],ENTROPY_SHIELD)
  !CheckStatGT([GOODCUTOFF.0.0.MAGE_THIEF],0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",[GOODCUTOFF.0.0.MAGE_THIEF]) // Shield of Reflection
  WeaponEffectiveVs([GOODCUTOFF.0.0.MAGE_THIEF],MAINHAND)
  WeaponCanDamage([GOODCUTOFF.0.0.MAGE_THIEF],MAINHAND)
  CheckStatGT([GOODCUTOFF.0.0.MAGE_THIEF],-10,ACMISSILEMOD)
  CheckStatLT([GOODCUTOFF.0.0.MAGE_THIEF],1,STONESKINS)
  CheckStatLT([GOODCUTOFF.0.0.MAGE_THIEF],100,RESISTMISSILE)
  !Range([GOODCUTOFF.0.0.MAGE_THIEF],5)
  See([GOODCUTOFF.0.0.MAGE_THIEF])
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(HARD)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE],ENTROPY_SHIELD)
  !CheckStatGT([GOODCUTOFF.0.0.MAGE],0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",[GOODCUTOFF.0.0.MAGE]) // Shield of Reflection
  WeaponEffectiveVs([GOODCUTOFF.0.0.MAGE],MAINHAND)
  WeaponCanDamage([GOODCUTOFF.0.0.MAGE],MAINHAND)
  CheckStatGT([GOODCUTOFF.0.0.MAGE],-10,ACMISSILEMOD)
  CheckStatLT([GOODCUTOFF.0.0.MAGE],1,STONESKINS)
  CheckStatLT([GOODCUTOFF.0.0.MAGE],100,RESISTMISSILE)
  !Range([GOODCUTOFF.0.0.MAGE],5)
  See([GOODCUTOFF.0.0.MAGE])
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(EASY)
  !CheckSpellState(ThirdNearest([GOODCUTOFF]),ENTROPY_SHIELD)
  !CheckStatGT(ThirdNearest([GOODCUTOFF]),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",ThirdNearest([GOODCUTOFF])) // Shield of Reflection
  WeaponEffectiveVs(ThirdNearest([GOODCUTOFF]),MAINHAND)
  WeaponCanDamage(ThirdNearest([GOODCUTOFF]),MAINHAND)
  CheckStatGT(ThirdNearest([GOODCUTOFF]),-5,ACMISSILEMOD)
  CheckStatLT(ThirdNearest([GOODCUTOFF]),1,STONESKINS)
  StateCheck(ThirdNearest([GOODCUTOFF]),STATE_IMMOBILE)
  CheckStatLT(ThirdNearest([GOODCUTOFF]),100,RESISTMISSILE)
  !Range(ThirdNearest([GOODCUTOFF]),5)
  See(ThirdNearest([GOODCUTOFF]))
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(EASY)
  !CheckSpellState(SecondNearest([GOODCUTOFF]),ENTROPY_SHIELD)
  !CheckStatGT(SecondNearest([GOODCUTOFF]),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",SecondNearest([GOODCUTOFF])) // Shield of Reflection
  WeaponEffectiveVs(SecondNearest([GOODCUTOFF]),MAINHAND)
  WeaponCanDamage(SecondNearest([GOODCUTOFF]),MAINHAND)
  CheckStatGT(SecondNearest([GOODCUTOFF]),-5,ACMISSILEMOD)
  CheckStatLT(SecondNearest([GOODCUTOFF]),1,STONESKINS)
  StateCheck(SecondNearest([GOODCUTOFF]),STATE_IMMOBILE)
  CheckStatLT(SecondNearest([GOODCUTOFF]),100,RESISTMISSILE)
  !Range(SecondNearest([GOODCUTOFF]),5)
  See(SecondNearest([GOODCUTOFF]))
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(EASY)
  !CheckSpellState([GOODCUTOFF],ENTROPY_SHIELD)
  !CheckStatGT([GOODCUTOFF],0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",[GOODCUTOFF]) // Shield of Reflection
  WeaponEffectiveVs([GOODCUTOFF],MAINHAND)
  WeaponCanDamage([GOODCUTOFF],MAINHAND)
  CheckStatGT([GOODCUTOFF],-5,ACMISSILEMOD)
  CheckStatLT([GOODCUTOFF],1,STONESKINS)
  StateCheck([GOODCUTOFF],STATE_IMMOBILE)
  CheckStatLT([GOODCUTOFF],100,RESISTMISSILE)
  !Range([GOODCUTOFF],5)
  See([GOODCUTOFF])
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(EASY)
  !CheckSpellState(Player6,ENTROPY_SHIELD)
  !CheckStatGT(Player6,0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",Player6) // Shield of Reflection
  WeaponEffectiveVs(Player6,MAINHAND)
  WeaponCanDamage(Player6,MAINHAND)
  StateCheck(Player6,STATE_IMMOBILE)
  CheckStatLT(Player6,100,RESISTMISSILE)
  !Range(Player6,5)
  See(Player6)
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(EASY)
  !CheckSpellState(Player5,ENTROPY_SHIELD)
  !CheckStatGT(Player5,0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",Player5) // Shield of Reflection
  WeaponEffectiveVs(Player5,MAINHAND)
  WeaponCanDamage(Player5,MAINHAND)
  StateCheck(Player5,STATE_IMMOBILE)
  CheckStatLT(Player5,100,RESISTMISSILE)
  !Range(Player5,5)
  See(Player5)
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(EASY)
  !CheckSpellState(Player4,ENTROPY_SHIELD)
  !CheckStatGT(Player4,0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",Player4) // Shield of Reflection
  WeaponEffectiveVs(Player4,MAINHAND)
  WeaponCanDamage(Player4,MAINHAND)
  StateCheck(Player4,STATE_IMMOBILE)
  CheckStatLT(Player4,100,RESISTMISSILE)
  !Range(Player4,5)
  See(Player4)
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(EASY)
  !CheckSpellState(Player3,ENTROPY_SHIELD)
  !CheckStatGT(Player3,0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",Player3) // Shield of Reflection
  WeaponEffectiveVs(Player3,MAINHAND)
  WeaponCanDamage(Player3,MAINHAND)
  StateCheck(Player3,STATE_IMMOBILE)
  CheckStatLT(Player3,100,RESISTMISSILE)
  !Range(Player3,5)
  See(Player3)
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(EASY)
  !CheckSpellState(Player2,ENTROPY_SHIELD)
  !CheckStatGT(Player2,0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",Player2) // Shield of Reflection
  WeaponEffectiveVs(Player2,MAINHAND)
  WeaponCanDamage(Player2,MAINHAND)
  StateCheck(Player2,STATE_IMMOBILE)
  CheckStatLT(Player2,100,RESISTMISSILE)
  !Range(Player2,5)
  See(Player2)
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(EASY)
  !CheckSpellState(Player1,ENTROPY_SHIELD)
  !CheckStatGT(Player1,0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",Player1) // Shield of Reflection
  WeaponEffectiveVs(Player1,MAINHAND)
  WeaponCanDamage(Player1,MAINHAND)
  StateCheck(Player1,STATE_IMMOBILE)
  CheckStatLT(Player1,100,RESISTMISSILE)
  !Range(Player1,5)
  See(Player1)
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(HARD)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),ENTROPY_SHIELD)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",SecondNearest([GOODCUTOFF.0.0.DRUID_ALL])) // Shield of Reflection
  WeaponEffectiveVs(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),MAINHAND)
  WeaponCanDamage(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),MAINHAND)
  CheckStatGT(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),-5,ACMISSILEMOD)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),1,STONESKINS)
  StateCheck(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),STATE_IMMOBILE)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),100,RESISTMISSILE)
  !Range(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),5)
  See(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]))
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(HARD)
  !CheckSpellState([GOODCUTOFF.0.0.DRUID_ALL],ENTROPY_SHIELD)
  !CheckStatGT([GOODCUTOFF.0.0.DRUID_ALL],0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",[GOODCUTOFF.0.0.DRUID_ALL]) // Shield of Reflection
  WeaponEffectiveVs([GOODCUTOFF.0.0.DRUID_ALL],MAINHAND)
  WeaponCanDamage([GOODCUTOFF.0.0.DRUID_ALL],MAINHAND)
  CheckStatGT([GOODCUTOFF.0.0.DRUID_ALL],-5,ACMISSILEMOD)
  CheckStatLT([GOODCUTOFF.0.0.DRUID_ALL],1,STONESKINS)
  StateCheck([GOODCUTOFF.0.0.DRUID_ALL],STATE_IMMOBILE)
  CheckStatLT([GOODCUTOFF.0.0.DRUID_ALL],100,RESISTMISSILE)
  !Range([GOODCUTOFF.0.0.DRUID_ALL],5)
  See([GOODCUTOFF.0.0.DRUID_ALL])
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(HARD)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),ENTROPY_SHIELD)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL])) // Shield of Reflection
  WeaponEffectiveVs(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),MAINHAND)
  WeaponCanDamage(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),MAINHAND)
  CheckStatGT(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),-5,ACMISSILEMOD)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),1,STONESKINS)
  StateCheck(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),STATE_IMMOBILE)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),100,RESISTMISSILE)
  !Range(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),5)
  See(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]))
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(HARD)
  !CheckSpellState([GOODCUTOFF.0.0.CLERIC_ALL],ENTROPY_SHIELD)
  !CheckStatGT([GOODCUTOFF.0.0.CLERIC_ALL],0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",[GOODCUTOFF.0.0.CLERIC_ALL]) // Shield of Reflection
  WeaponEffectiveVs([GOODCUTOFF.0.0.CLERIC_ALL],MAINHAND)
  WeaponCanDamage([GOODCUTOFF.0.0.CLERIC_ALL],MAINHAND)
  CheckStatGT([GOODCUTOFF.0.0.CLERIC_ALL],-5,ACMISSILEMOD)
  CheckStatLT([GOODCUTOFF.0.0.CLERIC_ALL],1,STONESKINS)
  StateCheck([GOODCUTOFF.0.0.CLERIC_ALL],STATE_IMMOBILE)
  CheckStatLT([GOODCUTOFF.0.0.CLERIC_ALL],100,RESISTMISSILE)
  !Range([GOODCUTOFF.0.0.CLERIC_ALL],5)
  See([GOODCUTOFF.0.0.CLERIC_ALL])
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(HARD)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),ENTROPY_SHIELD)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",SecondNearest([GOODCUTOFF.0.0.BARD_ALL])) // Shield of Reflection
  WeaponEffectiveVs(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),MAINHAND)
  WeaponCanDamage(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),MAINHAND)
  CheckStatGT(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),-5,ACMISSILEMOD)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),1,STONESKINS)
  StateCheck(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),STATE_IMMOBILE)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),100,RESISTMISSILE)
  !Range(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),5)
  See(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]))
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(HARD)
  !CheckSpellState([GOODCUTOFF.0.0.BARD_ALL],ENTROPY_SHIELD)
  !CheckStatGT([GOODCUTOFF.0.0.BARD_ALL],0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",[GOODCUTOFF.0.0.BARD_ALL]) // Shield of Reflection
  WeaponEffectiveVs([GOODCUTOFF.0.0.BARD_ALL],MAINHAND)
  WeaponCanDamage([GOODCUTOFF.0.0.BARD_ALL],MAINHAND)
  CheckStatGT([GOODCUTOFF.0.0.BARD_ALL],-5,ACMISSILEMOD)
  CheckStatLT([GOODCUTOFF.0.0.BARD_ALL],1,STONESKINS)
  StateCheck([GOODCUTOFF.0.0.BARD_ALL],STATE_IMMOBILE)
  CheckStatLT([GOODCUTOFF.0.0.BARD_ALL],100,RESISTMISSILE)
  !Range([GOODCUTOFF.0.0.BARD_ALL],5)
  See([GOODCUTOFF.0.0.BARD_ALL])
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(HARD)
  !CheckSpellState(ThirdNearest([GOODCUTOFF.0.0.MAGE_ALL]),ENTROPY_SHIELD)
  !CheckStatGT(ThirdNearest([GOODCUTOFF.0.0.MAGE_ALL]),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",ThirdNearest([GOODCUTOFF.0.0.MAGE_ALL])) // Shield of Reflection
  WeaponEffectiveVs(ThirdNearest([GOODCUTOFF.0.0.MAGE_ALL]),MAINHAND)
  WeaponCanDamage(ThirdNearest([GOODCUTOFF.0.0.MAGE_ALL]),MAINHAND)
  CheckStatGT(ThirdNearest([GOODCUTOFF.0.0.MAGE_ALL]),-5,ACMISSILEMOD)
  CheckStatLT(ThirdNearest([GOODCUTOFF.0.0.MAGE_ALL]),1,STONESKINS)
  StateCheck(ThirdNearest([GOODCUTOFF.0.0.MAGE_ALL]),STATE_IMMOBILE)
  CheckStatLT(ThirdNearest([GOODCUTOFF.0.0.MAGE_ALL]),100,RESISTMISSILE)
  !Range(ThirdNearest([GOODCUTOFF.0.0.MAGE_ALL]),5)
  See(ThirdNearest([GOODCUTOFF.0.0.MAGE_ALL]))
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(HARD)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),ENTROPY_SHIELD)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",SecondNearest([GOODCUTOFF.0.0.MAGE_ALL])) // Shield of Reflection
  WeaponEffectiveVs(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),MAINHAND)
  WeaponCanDamage(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),MAINHAND)
  CheckStatGT(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),-5,ACMISSILEMOD)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),1,STONESKINS)
  StateCheck(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),STATE_IMMOBILE)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),100,RESISTMISSILE)
  !Range(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),5)
  See(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]))
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  DifficultyGT(HARD)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE_ALL],ENTROPY_SHIELD)
  !CheckStatGT([GOODCUTOFF.0.0.MAGE_ALL],0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",[GOODCUTOFF.0.0.MAGE_ALL]) // Shield of Reflection
  WeaponEffectiveVs([GOODCUTOFF.0.0.MAGE_ALL],MAINHAND)
  WeaponCanDamage([GOODCUTOFF.0.0.MAGE_ALL],MAINHAND)
  CheckStatGT([GOODCUTOFF.0.0.MAGE_ALL],-5,ACMISSILEMOD)
  CheckStatLT([GOODCUTOFF.0.0.MAGE_ALL],1,STONESKINS)
  StateCheck([GOODCUTOFF.0.0.MAGE_ALL],STATE_IMMOBILE)
  CheckStatLT([GOODCUTOFF.0.0.MAGE_ALL],100,RESISTMISSILE)
  !Range([GOODCUTOFF.0.0.MAGE_ALL],5)
  See([GOODCUTOFF.0.0.MAGE_ALL])
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  WeaponEffectiveVs(LastSeenBy(Myself),MAINHAND)
  Allegiance(Myself,ENEMY)
  !Range(LastSeenBy(Myself),5)
  !CheckSpellState(LastSeenBy(Myself),ENTROPY_SHIELD)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",LastSeenBy(Myself))  // Reflection Shield +1
  IsWeaponRanged(Myself)
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself),30)
END

IF
  See(LastSeenBy(Myself))
  Allegiance(LastSeenBy(Myself),ENEMY)
  WeaponEffectiveVs(LastSeenBy(Myself),MAINHAND)
  !Allegiance(Myself,ENEMY)
  !Range(LastSeenBy(Myself),5)
  !CheckSpellState(LastSeenBy(Myself),ENTROPY_SHIELD)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !HasItemEquiped("SHLD24",LastSeenBy(Myself))  // Reflection Shield +1
  IsWeaponRanged(Myself)
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself),30)
END

/////////////////////////////////////////////////////////////////////
// Unable to Attack w/ Ranged weapon, Switch to Melee
/////////////////////////////////////////////////////////////////////
IF 
  !GlobalTimerNotExpired("MO_AttackingTimer","LOCALS")
  IsWeaponRanged(Myself)
  !HasItem("melfmet",Myself)  // Melf's Minute Meteor
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    Continue()
END

IF
  OR(6)
    See(Player1)
    See(Player2)
    See(Player3)
    See(Player4)
    See(Player5)
    See(Player6)
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
  !StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  Range(SixthNearestEnemyOf(Myself),5)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  Range(FifthNearestEnemyOf(Myself),5)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  Range(FourthNearestEnemyOf(Myself),5)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  Range(ThirdNearestEnemyOf(Myself),5)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  Range(SecondNearestEnemyOf(Myself),5)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
  !StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(NearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  Range(NearestEnemyOf(Myself),5)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  StateCheck(SixthNearestEnemyOf(Myself),STATE_IMMOBILE)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
  StateCheck(FifthNearestEnemyOf(Myself),STATE_IMMOBILE)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
  StateCheck(FourthNearestEnemyOf(Myself),STATE_IMMOBILE)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
  StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMMOBILE)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
  StateCheck(SecondNearestEnemyOf(Myself),STATE_IMMOBILE)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
  StateCheck(NearestEnemyOf(Myself),STATE_IMMOBILE)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  WeaponEffectiveVs(LastSeenBy(Myself),MAINHAND)
  Allegiance(Myself,ENEMY)
  OR(3)
    !HaveAnySpells()
    Range(LastSeenBy(Myself),5)
    CheckStatGT(Myself,1,NUMBEROFATTACKS)
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself),30)
END

IF
  See(LastSeenBy(Myself))
  Allegiance(LastSeenBy(Myself),ENEMY)
  WeaponEffectiveVs(LastSeenBy(Myself),MAINHAND)
  !Allegiance(Myself,ENEMY)
  OR(3)
    !HaveAnySpells()
    Range(LastSeenBy(Myself),5)
    CheckStatGT(Myself,1,NUMBEROFATTACKS)
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself),30)
END

