IF
    GlobalTimerExpired("AC#PP_Investigate","GLOBAL")
    Global("AC#PPSpellCheckPoison","GLOBAL",2)
THEN
    RESPONSE #100
        CreateCreature("AC#PPEL4",[260.242],S)  // Alatoasz Berendim
        SetGlobal("AC#PPSpellCheckPoison","GLOBAL",3)
END

IF
Global("AC#PPSymbolQuest","GLOBAL",2)
Global("AC#PPSymbolQuest_C","GLOBAL",0)
THEN
RESPONSE #100
CreateCreature("AC#PPMON",[200.350],S) 
SetGlobal("AC#PPSymbolQuest_C","GLOBAL",1)
END
