IF
    Global("AC#PPSpellCheckPoison","GLOBAL",2)
THEN
    RESPONSE #100
        CreateCreature("AC#PPEL4",[260.242],S)  // Alatoasz Berendim
        SetGlobal("AC#PPSpellCheckPoison","GLOBAL",3)
END

IF
    Global("AC#PP_NewProblemsUnnohyr","GLOBAL",1)
    Global("AC#PP_MythUnnohyr","GLOBAL",7)
THEN
    RESPONSE #100
        CreateCreature("AC#PPMI",[370.240],S)  // Mismal Al'Visalle
        SetGlobal("AC#PP_MythUnnohyr","GLOBAL",8)
END

