IF
    Global("EnteredArea","ACPP11",0)  
THEN
    RESPONSE #100
        SetMusic(NIGHT,%AC#PP01%)
        SetMusic(DAY,%AC#PP01%)
        //SetAreaRestFlag(0)
        SetGlobal("EnteredArea","ACPP11",1)  
END

IF
    !GlobalTimerNotExpired("NoFightTimer","ACPP11")
THEN
    RESPONSE #100
        ApplySpellRES("AC#PPNF",Player1)  // No such index
        SetGlobalTimer("NoFightTimer","ACPP11",14)
END

