IF
	Global("Prep","ACPP73",0)
THEN
RESPONSE #100
	SetMusic(NIGHT,%AC#PP70%)
	SetMusic(DAY,%AC#PP70%)
	SetGlobal("Prep","ACPP73",1)
	Continue()
END

IF
  Global("AC#PPTowerGuardian","GLOBAL",3)
THEN
  RESPONSE #100
      CreateCreature("AC#PPOR2",[810.760],S)  // Wadal Hrun
      SetGlobal("AC#PPTowerGuardian","GLOBAL",4)
END

IF
Global("AC#PPChapter6Quest","GLOBAL",7)
THEN
RESPONSE #100
CreateCreature("AC#PPHEL",[2050.940],3)
SetGlobal("AC#PPChapter6Quest","GLOBAL",8)
END